import 'seed_data.dart';

const List<Map<String, Object>> _manualVocabularySeedExpansion = [
  {
    'id': 'v21',
    'german': 'die Gehaltsabrechnung',
    'phonetic': '/ge-halts-ab-rech-nung/',
    'english': 'Pay slip',
    'dari': 'Barg-e maash',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Bitte kontrollieren Sie Ihre Gehaltsabrechnung.',
    'context': 'Monthly statement of salary details.',
    'contextDari': 'Jozeyat-e maash-e mahanah.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v22',
    'german': 'der Lebenslauf',
    'phonetic': '/le-bens-lauf/',
    'english': 'Resume',
    'dari': 'CV',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Mein Lebenslauf ist aktuell.',
    'context': 'Document with professional experience.',
    'contextDari': 'Sanad-e tajroba-ye kari.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v23',
    'german': 'die Probezeit',
    'phonetic': '/pro-be-zeit/',
    'english': 'Probation period',
    'dari': 'dawra-ye azmayeshi',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Die Probezeit dauert sechs Monate.',
    'context': 'Initial trial period in a new job.',
    'contextDari': 'Dawra-ye ebtedaei-e arzyabi.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v24',
    'german': 'die Teamleitung',
    'phonetic': '/team-lai-tung/',
    'english': 'Team lead',
    'dari': 'sarparast-e team',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Die Teamleitung organisiert das Projekt.',
    'context': 'Person responsible for leading a team.',
    'contextDari': 'Fard-e masul-e hedayat-e team.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v25',
    'german': 'das Protokoll',
    'phonetic': '/pro-to-koll/',
    'english': 'Meeting minutes',
    'dari': 'sorat-e jalsa',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Das Protokoll wird nach dem Meeting verschickt.',
    'context': 'Written summary of a meeting.',
    'contextDari': 'Kholasa-ye maktoob-e jalsa.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v26',
    'german': 'die Teilnehmenden',
    'phonetic': '/tail-neh-men-den/',
    'english': 'Participants',
    'dari': 'eshterak-konandegan',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Alle Teilnehmenden sind puenktlich.',
    'context': 'People attending a meeting or event.',
    'contextDari': 'Afrad-e hazer dar jalsa.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v27',
    'german': 'die Abstimmung',
    'phonetic': '/ab-stim-mung/',
    'english': 'Vote or alignment',
    'dari': 'ray giri',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Wir brauchen eine Abstimmung im Team.',
    'context': 'Decision process by voting or alignment.',
    'contextDari': 'Faraayand-e tasmim giri dar team.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v28',
    'german': 'die Rueckfrage',
    'phonetic': '/ruek-fra-ge/',
    'english': 'Follow-up question',
    'dari': 'soal-e taqibi',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Ich habe noch eine Rueckfrage zum Budget.',
    'context': 'Additional question for clarification.',
    'contextDari': 'Soal-e ezafi baraye wazahat.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v29',
    'german': 'die Kostenstelle',
    'phonetic': '/kos-ten-shte-le/',
    'english': 'Cost center',
    'dari': 'markaz-e hazine',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Bitte die Kostenstelle auf der Rechnung eintragen.',
    'context': 'Accounting unit that tracks costs.',
    'contextDari': 'Vahed-e hesabdari baraye radyabi hazine.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v30',
    'german': 'die Steuer',
    'phonetic': '/sh-toy-er/',
    'english': 'Tax',
    'dari': 'malia',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Die Steuer wird monatlich berechnet.',
    'context': 'Mandatory payment to the government.',
    'contextDari': 'Pardakht-e ejbari be dowlat.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v31',
    'german': 'das Budget',
    'phonetic': '/bud-zhet/',
    'english': 'Budget',
    'dari': 'bodja',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Wir bleiben im Budget.',
    'context': 'Planned amount of money for a purpose.',
    'contextDari': 'Meqdar-e barname rizi shoda-ye pool.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v32',
    'german': 'die Liquiditaet',
    'phonetic': '/li-kwi-di-tet/',
    'english': 'Liquidity',
    'dari': 'naqdingi',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Die Liquiditaet des Unternehmens ist stabil.',
    'context': 'Available cash for short-term obligations.',
    'contextDari': 'Pool-e dar dastres baraye taahodat-e kotah moddat.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v33',
    'german': 'die Verlaengerung',
    'phonetic': '/fer-len-ge-rung/',
    'english': 'Extension',
    'dari': 'tamdid',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Wir beantragen eine Verlaengerung des Vertrags.',
    'context': 'Lengthening validity of a contract.',
    'contextDari': 'Toolani kardan-e moddat-e gharardad.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v34',
    'german': 'die Klausel',
    'phonetic': '/klau-zel/',
    'english': 'Clause',
    'dari': 'band-e gharardad',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Klausel regelt die Haftung.',
    'context': 'Specific legal condition in a contract.',
    'contextDari': 'Shart-e moshakhas-e hoqoqi dar gharardad.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v35',
    'german': 'die Unterschrift',
    'phonetic': '/un-ter-shrift/',
    'english': 'Signature',
    'dari': 'emza',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Unterschrift fehlt auf Seite zwei.',
    'context': 'Written sign to confirm agreement.',
    'contextDari': 'Alamat-e neveshtari baraye taeed-e tavafoq.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v36',
    'german': 'die Kuendigungsfrist',
    'phonetic': '/kuen-di-gungs-frist/',
    'english': 'Notice period',
    'dari': 'moddat-e etelaa-e faskh',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Kuendigungsfrist betraegt drei Monate.',
    'context': 'Time required before contract termination.',
    'contextDari': 'Moddat-e lazem pish az payan-e gharardad.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v37',
    'german': 'die Weiterleitung',
    'phonetic': '/vai-ter-lai-tung/',
    'english': 'Forwarding',
    'dari': 'erjaa',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Danke fuer die Weiterleitung der E-Mail.',
    'context': 'Sending an email or message to another person.',
    'contextDari': 'Ferestadan-e payam be shakhs-e digar.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v38',
    'german': 'die Dringlichkeit',
    'phonetic': '/dring-lich-kait/',
    'english': 'Urgency',
    'dari': 'foriat',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Bitte markieren Sie die Dringlichkeit.',
    'context': 'How urgent a task or request is.',
    'contextDari': 'Daraja-ye fawri boodan-e yek kar.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v39',
    'german': 'der Anhang',
    'phonetic': '/an-hang/',
    'english': 'Attachment',
    'dari': 'zamima',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Die Datei ist im Anhang.',
    'context': 'File attached to an email.',
    'contextDari': 'Fail-e zamima-ye email.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v40',
    'german': 'die Erreichbarkeit',
    'phonetic': '/er-rai-kh-bar-kait/',
    'english': 'Availability',
    'dari': 'dar dastres boodan',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Meine Erreichbarkeit ist von 9 bis 17 Uhr.',
    'context': 'Time when someone can be contacted.',
    'contextDari': 'Zamani ke mitawan ba kasi tamas gereft.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v41',
    'german': 'die Fehlermeldung',
    'phonetic': '/fey-ler-mel-dung/',
    'english': 'Error message',
    'dari': 'payam-e khata',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Ich bekomme eine Fehlermeldung beim Login.',
    'context': 'System notification about an error.',
    'contextDari': 'Ettelaa-e sistem darbare-ye khata.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v42',
    'german': 'die Wartung',
    'phonetic': '/var-tung/',
    'english': 'Maintenance',
    'dari': 'negahdari',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Die Wartung findet am Wochenende statt.',
    'context': 'Regular technical service and upkeep.',
    'contextDari': 'Khedmat-e fani-ye monazzam.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v43',
    'german': 'die Berechtigung',
    'phonetic': '/be-rekh-ti-gung/',
    'english': 'Permission',
    'dari': 'ejaza-ye dastresi',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Sie haben keine Berechtigung fuer diesen Bereich.',
    'context': 'Authorization to access system resources.',
    'contextDari': 'Ejaza-ye dastresi be manabe-e sistem.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v44',
    'german': 'die Datensicherung',
    'phonetic': '/da-ten-zi-khe-rung/',
    'english': 'Data backup',
    'dari': 'poshtiban giri-ye data',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Die Datensicherung laeuft jede Nacht.',
    'context': 'Creating copies of data for recovery.',
    'contextDari': 'Sakhtan-e noskha-ye poshtiban baraye bazyabi.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v45',
    'german': 'die Reichweite',
    'phonetic': '/rai-kh-vai-te/',
    'english': 'Reach',
    'dari': 'daman-e dastresi',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Die Kampagne hat hohe Reichweite.',
    'context': 'Number of people reached by content.',
    'contextDari': 'Tedad-e afrad-e dastresi yafta.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v46',
    'german': 'die Conversion-Rate',
    'phonetic': '/kon-ver-shn-ray-te/',
    'english': 'Conversion rate',
    'dari': 'narkh-e tabdil',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Unsere Conversion-Rate steigt kontinuierlich.',
    'context': 'Percentage of users completing target action.',
    'contextDari': 'Darsad-e karbaran-e anjam dahanda-ye hadaf.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v47',
    'german': 'der Vertrieb',
    'phonetic': '/fer-trieb/',
    'english': 'Sales department',
    'dari': 'bakhsh-e forosh',
    'category': 'Marketing',
    'tag': 'Sales',
    'example': 'Der Vertrieb praesentiert die Zahlen.',
    'context': 'Department responsible for selling products.',
    'contextDari': 'Bakhsh-e masul-e forosh-e mahsolat.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v48',
    'german': 'die Markenbekanntheit',
    'phonetic': '/mar-ken-be-kant-hait/',
    'english': 'Brand awareness',
    'dari': 'shenakht-e brand',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Wir wollen die Markenbekanntheit steigern.',
    'context': 'How well customers know a brand.',
    'contextDari': 'Mizan-e shenakhte shodan-e brand.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v49',
    'german': 'die Fachliteratur',
    'phonetic': '/fakh-li-te-ra-tur/',
    'english': 'Specialist literature',
    'dari': 'manabe-e takhasosi',
    'category': 'Bildung',
    'tag': 'Learning',
    'example': 'Ich lese Fachliteratur zum Thema Finanzen.',
    'context': 'Professional books and references.',
    'contextDari': 'Ketabha wa manabe-e herfei.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v50',
    'german': 'das Zertifikat',
    'phonetic': '/tser-ti-fi-kat/',
    'english': 'Certificate',
    'dari': 'tasdiq nama',
    'category': 'Bildung',
    'tag': 'Learning',
    'example': 'Nach dem Kurs bekomme ich ein Zertifikat.',
    'context': 'Official proof of completed training.',
    'contextDari': 'Madrak-e rasmi-ye takmil-e amozesh.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
];

const List<Map<String, Object>> _generatedVocabularyBlueprints = [
  {'german': 'der Onboarding-Prozess', 'english': 'Onboarding process', 'dari': 'farayand-e shoru', 'category': 'Bewerbung & Karriere', 'tag': 'HR', 'difficulty': 'medium'},
  {'german': 'die Stellenbeschreibung', 'english': 'Job description', 'dari': 'tozih-e vazifa', 'category': 'Bewerbung & Karriere', 'tag': 'HR', 'difficulty': 'easy'},
  {'german': 'das Kernteam', 'english': 'Core team', 'dari': 'team-e markazi', 'category': 'Meetings', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'der Tagesbericht', 'english': 'Daily report', 'dari': 'gozaresh-e rozana', 'category': 'Meetings', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Kostenanalyse', 'english': 'Cost analysis', 'dari': 'tahlil-e hazine', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'medium'},
  {'german': 'der Zahlungsplan', 'english': 'Payment plan', 'dari': 'barname-ye pardakht', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'easy'},
  {'german': 'die Haftung', 'english': 'Liability', 'dari': 'masuliyat-e hoqoqi', 'category': 'Vertrage', 'tag': 'Legal', 'difficulty': 'hard'},
  {'german': 'die Vertragsbedingung', 'english': 'Contract term', 'dari': 'shart-e gharardad', 'category': 'Vertrage', 'tag': 'Legal', 'difficulty': 'medium'},
  {'german': 'die Prioritaet', 'english': 'Priority', 'dari': 'awlawiat', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Ruecksprache', 'english': 'Consultation', 'dari': 'mashwera', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'medium'},
  {'german': 'die Zugriffsrolle', 'english': 'Access role', 'dari': 'naqsh-e dastresi', 'category': 'IT & Technik', 'tag': 'IT', 'difficulty': 'medium'},
  {'german': 'der Sicherheitscheck', 'english': 'Security check', 'dari': 'barresi-ye amniati', 'category': 'IT & Technik', 'tag': 'IT', 'difficulty': 'easy'},
  {'german': 'die Lead-Generierung', 'english': 'Lead generation', 'dari': 'tolid-e moshtari-ye jadid', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'hard'},
  {'german': 'der Marktanteil', 'english': 'Market share', 'dari': 'sahm-e bazar', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'medium'},
  {'german': 'der Lernpfad', 'english': 'Learning path', 'dari': 'masir-e amozesh', 'category': 'Bildung', 'tag': 'Learning', 'difficulty': 'easy'},
  {'german': 'die Abschlusspruefung', 'english': 'Final exam', 'dari': 'azmoon-e payani', 'category': 'Bildung', 'tag': 'Learning', 'difficulty': 'medium'},
  {'german': 'die Lieferkette', 'english': 'Supply chain', 'dari': 'zanjira-ye tamin', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'hard'},
  {'german': 'die Produktivitaet', 'english': 'Productivity', 'dari': 'bahrewari', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'das Zeitmanagement', 'english': 'Time management', 'dari': 'modiriat-e zaman', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Kundenbindung', 'english': 'Customer retention', 'dari': 'hefz-e moshtari', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'hard'},
];

final List<Map<String, Object>> vocabularySeedExpansion = [
  ..._manualVocabularySeedExpansion,
  ..._buildGeneratedVocabularySeed(),
];

const List<Map<String, Object>> _manualExerciseSeedExpansion = [
  {
    'id': 'e15',
    'type': 'multiple-choice',
    'question': 'Welches Wort passt zu: monatliche Zahlung an den Staat?',
    'options': ['die Steuer', 'die Frist', 'die Kampagne', 'der Vertrag'],
    'correctAnswer': 0,
    'topic': 'Finanzen',
    'level': 'A2',
  },
  {
    'id': 'e16',
    'type': 'multiple-choice',
    'question': "Was bedeutet 'der Lebenslauf'?",
    'options': ['invoice', 'resume', 'meeting', 'campaign'],
    'correctAnswer': 1,
    'topic': 'Bewerbung',
    'level': 'A1',
  },
  {
    'id': 'e17',
    'type': 'fill-in-blank',
    'question': 'Wir bleiben ___ Budget.',
    'options': ['im', 'in den', 'an', 'zu'],
    'correctAnswer': 0,
    'topic': 'Praepositionen',
    'level': 'A2',
  },
  {
    'id': 'e18',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Wartung' = ?",
    'options': ['maintenance', 'tax', 'extension', 'agenda'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'A2',
  },
  {
    'id': 'e19',
    'type': 'multiple-choice',
    'question': 'Die Probezeit dauert ___ Monate.',
    'options': ['sechs', 'sechzig', 'fuenfzehn', 'zweiundzwanzig'],
    'correctAnswer': 0,
    'topic': 'Bewerbung',
    'level': 'A2',
  },
  {
    'id': 'e20',
    'type': 'fill-in-blank',
    'question': 'Bitte senden Sie mir den Bericht ___ E-Mail.',
    'options': ['per', 'durch', 'von', 'gegen'],
    'correctAnswer': 0,
    'topic': 'Business',
    'level': 'B1',
  },
  {
    'id': 'e21',
    'type': 'sentence-order',
    'question': 'Ordnen Sie: wir / brauchen / heute / eine / Abstimmung',
    'options': [
      'Wir brauchen heute eine Abstimmung.',
      'Heute brauchen eine wir Abstimmung.',
      'Eine Abstimmung wir brauchen heute.',
      'Brauchen wir Abstimmung heute eine.'
    ],
    'correctAnswer': 0,
    'topic': 'Satzbau',
    'level': 'A2',
  },
  {
    'id': 'e22',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Berechtigung' = ?",
    'options': ['permission', 'deadline', 'offer', 'certificate'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'B1',
  },
  {
    'id': 'e23',
    'type': 'multiple-choice',
    'question': 'Welcher Ausdruck ist in einer E-Mail formell?',
    'options': ['Hi, was geht?', 'Sehr geehrte Damen und Herren', 'Yo, danke!', 'Hey Team'],
    'correctAnswer': 1,
    'topic': 'Business',
    'level': 'A1',
  },
  {
    'id': 'e24',
    'type': 'fill-in-blank',
    'question': 'Die Rechnung ist im ___.',
    'options': ['Anhang', 'Kampagne', 'Budget', 'Vertrieb'],
    'correctAnswer': 0,
    'topic': 'Office',
    'level': 'A1',
  },
  {
    'id': 'e25',
    'type': 'multiple-choice',
    'question': 'Was bedeutet "die Kuendigungsfrist"?',
    'options': ['notice period', 'brand awareness', 'cost center', 'pay slip'],
    'correctAnswer': 0,
    'topic': 'Vertraege',
    'level': 'B1',
  },
  {
    'id': 'e26',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Gehaltsabrechnung' = ?",
    'options': ['pay slip', 'resume', 'signature', 'urgency'],
    'correctAnswer': 0,
    'topic': 'Bewerbung',
    'level': 'A2',
  },
  {
    'id': 'e27',
    'type': 'multiple-choice',
    'question': 'Welches Wort gehoert zur Kategorie Marketing?',
    'options': ['die Markenbekanntheit', 'die Klausel', 'der Anhang', 'die Wartung'],
    'correctAnswer': 0,
    'topic': 'Marketing',
    'level': 'B1',
  },
  {
    'id': 'e28',
    'type': 'fill-in-blank',
    'question': 'Wir muessen die Daten regelmaessig ___.',
    'options': ['sichern', 'zahlen', 'kuendigen', 'einladen'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'A2',
  },
  {
    'id': 'e29',
    'type': 'sentence-order',
    'question': 'Ordnen Sie: bitte / den / im / speichern / Anhang / Bericht',
    'options': [
      'Bitte den Bericht im Anhang speichern.',
      'Im speichern den Anhang Bericht bitte.',
      'Bericht im den Anhang bitte speichern.',
      'Speichern bitte Anhang den im Bericht.'
    ],
    'correctAnswer': 0,
    'topic': 'Satzbau',
    'level': 'B1',
  },
  {
    'id': 'e30',
    'type': 'multiple-choice',
    'question': 'Welche Aussage ist korrekt?',
    'options': [
      'Die Conversion-Rate ist eine Steuer.',
      'Die Conversion-Rate misst Zielhandlungen.',
      'Die Conversion-Rate ist ein Vertrag.',
      'Die Conversion-Rate ist eine Frist.'
    ],
    'correctAnswer': 1,
    'topic': 'Marketing',
    'level': 'B2',
  },
];

final List<Map<String, Object>> exerciseSeedExpansion = [
  ..._manualExerciseSeedExpansion,
  ..._buildGeneratedExerciseSeed(),
];

List<Map<String, Object>> _buildGeneratedVocabularySeed() {
  return _generatedVocabularyBlueprints.asMap().entries.map((entry) {
    final id = 'v${51 + entry.key}';
    final row = entry.value;
    final german = row['german']! as String;
    final english = row['english']! as String;
    final dari = row['dari']! as String;

    return {
      'id': id,
      'german': german,
      'phonetic': _phoneticFromGerman(german),
      'english': english,
      'dari': dari,
      'category': row['category']! as String,
      'tag': row['tag']! as String,
      'example': 'Im Arbeitsalltag nutzen wir den Begriff $german.',
      'context': 'Business term for $english in workplace communication.',
      'contextDari': 'Istelah-e kari baraye $dari dar mohit-e kar.',
      'difficulty': row['difficulty']! as String,
      'isFavorite': false,
      'isDifficult': row['difficulty'] == 'hard',
    };
  }).toList();
}

String _phoneticFromGerman(String german) {
  final normalized = german
      .toLowerCase()
      .replaceAll('ae', 'a')
      .replaceAll('oe', 'o')
      .replaceAll('ue', 'u')
      .replaceAll(RegExp(r'[^a-z0-9 ]'), '')
      .trim()
      .replaceAll(RegExp(r'\s+'), '-');
  return '/$normalized/';
}

List<Map<String, Object>> _buildGeneratedExerciseSeed() {
  final vocabulary = [...vocabularySeed, ...vocabularySeedExpansion];
  final generated = <Map<String, Object>>[];
  final levelCycle = ['A1', 'A2', 'B1', 'B2'];

  final exerciseCount = vocabulary.length < 60 ? vocabulary.length : 60;
  for (var i = 0; i < exerciseCount; i++) {
    final current = vocabulary[i];
    final category = current['category']! as String;
    final level = levelCycle[i % levelCycle.length];
    final id = 'e${101 + i}';

    final currentGerman = current['german']! as String;
    final currentEnglish = current['english']! as String;

    final d1 = vocabulary[(i + 1) % vocabulary.length]['english']! as String;
    final d2 = vocabulary[(i + 2) % vocabulary.length]['english']! as String;
    final d3 = vocabulary[(i + 3) % vocabulary.length]['english']! as String;

    if (i % 4 == 0) {
      generated.add({
        'id': id,
        'type': 'multiple-choice',
        'question': "Was bedeutet '$currentGerman'?",
        'options': [currentEnglish, d1, d2, d3],
        'correctAnswer': 0,
        'topic': category,
        'level': level,
      });
      continue;
    }

    if (i % 4 == 1) {
      generated.add({
        'id': id,
        'type': 'matching',
        'question': "Welche Kombination ist richtig? '$currentGerman' = ?",
        'options': [currentEnglish, d1, d2, d3],
        'correctAnswer': 0,
        'topic': category,
        'level': level,
      });
      continue;
    }

    if (i % 4 == 2) {
      final g1 = vocabulary[(i + 1) % vocabulary.length]['german']! as String;
      final g2 = vocabulary[(i + 2) % vocabulary.length]['german']! as String;
      final g3 = vocabulary[(i + 3) % vocabulary.length]['german']! as String;
      generated.add({
        'id': id,
        'type': 'fill-in-blank',
        'question': 'Im Meeting sprechen wir ueber ___.',
        'options': [g1, currentGerman, g2, g3],
        'correctAnswer': 1,
        'topic': category,
        'level': level,
      });
      continue;
    }

    generated.add({
      'id': id,
      'type': 'sentence-order',
      'question': 'Ordnen Sie: wir / nutzen / im Buero / $currentGerman',
      'options': [
        'Wir nutzen im Buero $currentGerman.',
        'Im Buero nutzen wir $currentGerman.',
        '$currentGerman nutzen wir im Buero.',
        'Wir im Buero $currentGerman nutzen.'
      ],
      'correctAnswer': 0,
      'topic': category,
      'level': level,
    });
  }

  return generated;
}
