import 'seed_data.dart';

const List<Map<String, Object>> _manualVocabularySeedExpansion = [
  {
    'id': 'v21',
    'german': 'die Gehaltsabrechnung',
    'phonetic': '/ge-halts-ab-rech-nung/',
    'english': 'Pay slip',
    'dari': 'برگ معاش',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Bitte kontrollieren Sie Ihre Gehaltsabrechnung.',
    'context': 'Monthly statement of salary details.',
    'contextDari': 'جزئیات معاش ماهانه.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v22',
    'german': 'der Lebenslauf',
    'phonetic': '/le-bens-lauf/',
    'english': 'Resume',
    'dari': 'سی وی',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Mein Lebenslauf ist aktuell.',
    'context': 'Document with professional experience.',
    'contextDari': 'سند تجربه کاری.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v23',
    'german': 'die Probezeit',
    'phonetic': '/pro-be-zeit/',
    'english': 'Probation period',
    'dari': 'دوره آزمایشی',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Die Probezeit dauert sechs Monate.',
    'context': 'Initial trial period in a new job.',
    'contextDari': 'دوره ابتدایی ارزیابی.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v24',
    'german': 'die Teamleitung',
    'phonetic': '/team-lai-tung/',
    'english': 'Team lead',
    'dari': 'سرپرست تیم',
    'category': 'Bewerbung & Karriere',
    'tag': 'HR',
    'example': 'Die Teamleitung organisiert das Projekt.',
    'context': 'Person responsible for leading a team.',
    'contextDari': 'فرد مسئول هدایت تیم.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v25',
    'german': 'das Protokoll',
    'phonetic': '/pro-to-koll/',
    'english': 'Meeting minutes',
    'dari': 'صورت جلسه',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Das Protokoll wird nach dem Meeting verschickt.',
    'context': 'Written summary of a meeting.',
    'contextDari': 'خلاصه مکتوب جلسه.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v26',
    'german': 'die Teilnehmenden',
    'phonetic': '/tail-neh-men-den/',
    'english': 'Participants',
    'dari': 'اشتراک کنندگان',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Alle Teilnehmenden sind puenktlich.',
    'context': 'People attending a meeting or event.',
    'contextDari': 'افراد حاضر در جلسه.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v27',
    'german': 'die Abstimmung',
    'phonetic': '/ab-stim-mung/',
    'english': 'Vote or alignment',
    'dari': 'رای گیری',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Wir brauchen eine Abstimmung im Team.',
    'context': 'Decision process by voting or alignment.',
    'contextDari': 'فرایند تصمیم گیری در تیم.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v28',
    'german': 'die Rueckfrage',
    'phonetic': '/ruek-fra-ge/',
    'english': 'Follow-up question',
    'dari': 'سوال تعقیبی',
    'category': 'Meetings',
    'tag': 'Office',
    'example': 'Ich habe noch eine Rueckfrage zum Budget.',
    'context': 'Additional question for clarification.',
    'contextDari': 'سوال اضافی برای وضاحت.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v29',
    'german': 'die Kostenstelle',
    'phonetic': '/kos-ten-shte-le/',
    'english': 'Cost center',
    'dari': 'مرکز هزینه',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Bitte die Kostenstelle auf der Rechnung eintragen.',
    'context': 'Accounting unit that tracks costs.',
    'contextDari': 'واحد حسابداری برای ردیابی هزینه.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v30',
    'german': 'die Steuer',
    'phonetic': '/sh-toy-er/',
    'english': 'Tax',
    'dari': 'مالیه',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Die Steuer wird monatlich berechnet.',
    'context': 'Mandatory payment to the government.',
    'contextDari': 'پرداخت اجباری به دولت.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v31',
    'german': 'das Budget',
    'phonetic': '/bud-zhet/',
    'english': 'Budget',
    'dari': 'بودجه',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Wir bleiben im Budget.',
    'context': 'Planned amount of money for a purpose.',
    'contextDari': 'مقدار برنامه ریزی شده پول.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v32',
    'german': 'die Liquiditaet',
    'phonetic': '/li-kwi-di-tet/',
    'english': 'Liquidity',
    'dari': 'نقدینگی',
    'category': 'Finanzen',
    'tag': 'Finance',
    'example': 'Die Liquiditaet des Unternehmens ist stabil.',
    'context': 'Available cash for short-term obligations.',
    'contextDari': 'پول در دسترس برای تعهدات کوتاه مدت.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v33',
    'german': 'die Verlaengerung',
    'phonetic': '/fer-len-ge-rung/',
    'english': 'Extension',
    'dari': 'تمدید',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Wir beantragen eine Verlaengerung des Vertrags.',
    'context': 'Lengthening validity of a contract.',
    'contextDari': 'طولانی کردن مدت قرارداد.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v34',
    'german': 'die Klausel',
    'phonetic': '/klau-zel/',
    'english': 'Clause',
    'dari': 'بند قرارداد',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Klausel regelt die Haftung.',
    'context': 'Specific legal condition in a contract.',
    'contextDari': 'شرط مشخص حقوقی در قرارداد.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v35',
    'german': 'die Unterschrift',
    'phonetic': '/un-ter-shrift/',
    'english': 'Signature',
    'dari': 'امضا',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Unterschrift fehlt auf Seite zwei.',
    'context': 'Written sign to confirm agreement.',
    'contextDari': 'علامت نوشتاری برای تایید توافق.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v36',
    'german': 'die Kuendigungsfrist',
    'phonetic': '/kuen-di-gungs-frist/',
    'english': 'Notice period',
    'dari': 'مدت اطلاع فسخ',
    'category': 'Vertrage',
    'tag': 'Legal',
    'example': 'Die Kuendigungsfrist betraegt drei Monate.',
    'context': 'Time required before contract termination.',
    'contextDari': 'مدت لازم پیش از پایان قرارداد.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v37',
    'german': 'die Weiterleitung',
    'phonetic': '/vai-ter-lai-tung/',
    'english': 'Forwarding',
    'dari': 'ارجاع',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Danke fuer die Weiterleitung der E-Mail.',
    'context': 'Sending an email or message to another person.',
    'contextDari': 'فرستادن پیام به شخص دیگر.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v38',
    'german': 'die Dringlichkeit',
    'phonetic': '/dring-lich-kait/',
    'english': 'Urgency',
    'dari': 'فوریت',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Bitte markieren Sie die Dringlichkeit.',
    'context': 'How urgent a task or request is.',
    'contextDari': 'درجه فوری بودن یک کار.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v39',
    'german': 'der Anhang',
    'phonetic': '/an-hang/',
    'english': 'Attachment',
    'dari': 'ضمیمه',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Die Datei ist im Anhang.',
    'context': 'File attached to an email.',
    'contextDari': 'فایل ضمیمه ایمیل.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v40',
    'german': 'die Erreichbarkeit',
    'phonetic': '/er-rai-kh-bar-kait/',
    'english': 'Availability',
    'dari': 'در دسترس بودن',
    'category': 'Buro Kommunikation',
    'tag': 'Office',
    'example': 'Meine Erreichbarkeit ist von 9 bis 17 Uhr.',
    'context': 'Time when someone can be contacted.',
    'contextDari': 'زمانی که می توان با کسی تماس گرفت.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v41',
    'german': 'die Fehlermeldung',
    'phonetic': '/fey-ler-mel-dung/',
    'english': 'Error message',
    'dari': 'پیام خطا',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Ich bekomme eine Fehlermeldung beim Login.',
    'context': 'System notification about an error.',
    'contextDari': 'اطلاع سیستم درباره خطا.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v42',
    'german': 'die Wartung',
    'phonetic': '/var-tung/',
    'english': 'Maintenance',
    'dari': 'نگهداری',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Die Wartung findet am Wochenende statt.',
    'context': 'Regular technical service and upkeep.',
    'contextDari': 'خدمت فنی منظم.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v43',
    'german': 'die Berechtigung',
    'phonetic': '/be-rekh-ti-gung/',
    'english': 'Permission',
    'dari': 'اجازه دسترسی',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Sie haben keine Berechtigung fuer diesen Bereich.',
    'context': 'Authorization to access system resources.',
    'contextDari': 'اجازه دسترسی به منابع سیستم.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v44',
    'german': 'die Datensicherung',
    'phonetic': '/da-ten-zi-khe-rung/',
    'english': 'Data backup',
    'dari': 'پشتیبان گیری داده',
    'category': 'IT & Technik',
    'tag': 'IT',
    'example': 'Die Datensicherung laeuft jede Nacht.',
    'context': 'Creating copies of data for recovery.',
    'contextDari': 'ساختن نسخه پشتیبان برای بازیابی.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v45',
    'german': 'die Reichweite',
    'phonetic': '/rai-kh-vai-te/',
    'english': 'Reach',
    'dari': 'دامنه دسترسی',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Die Kampagne hat hohe Reichweite.',
    'context': 'Number of people reached by content.',
    'contextDari': 'تعداد افراد دسترسی یافته.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v46',
    'german': 'die Conversion-Rate',
    'phonetic': '/kon-ver-shn-ray-te/',
    'english': 'Conversion rate',
    'dari': 'نرخ تبدیل',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Unsere Conversion-Rate steigt kontinuierlich.',
    'context': 'Percentage of users completing target action.',
    'contextDari': 'درصد کاربران انجام دهنده هدف.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v47',
    'german': 'der Vertrieb',
    'phonetic': '/fer-trieb/',
    'english': 'Sales department',
    'dari': 'بخش فروش',
    'category': 'Marketing',
    'tag': 'Sales',
    'example': 'Der Vertrieb praesentiert die Zahlen.',
    'context': 'Department responsible for selling products.',
    'contextDari': 'بخش مسئول فروش محصولات.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v48',
    'german': 'die Markenbekanntheit',
    'phonetic': '/mar-ken-be-kant-hait/',
    'english': 'Brand awareness',
    'dari': 'شناخت برند',
    'category': 'Marketing',
    'tag': 'Marketing',
    'example': 'Wir wollen die Markenbekanntheit steigern.',
    'context': 'How well customers know a brand.',
    'contextDari': 'میزان شناخته شدن برند.',
    'difficulty': 'hard',
    'isFavorite': false,
    'isDifficult': true,
  },
  {
    'id': 'v49',
    'german': 'die Fachliteratur',
    'phonetic': '/fakh-li-te-ra-tur/',
    'english': 'Specialist literature',
    'dari': 'منابع تخصصی',
    'category': 'Bildung',
    'tag': 'Learning',
    'example': 'Ich lese Fachliteratur zum Thema Finanzen.',
    'context': 'Professional books and references.',
    'contextDari': 'کتاب ها و منابع حرفه ای.',
    'difficulty': 'medium',
    'isFavorite': false,
    'isDifficult': false,
  },
  {
    'id': 'v50',
    'german': 'das Zertifikat',
    'phonetic': '/tser-ti-fi-kat/',
    'english': 'Certificate',
    'dari': 'تصدیق نامه',
    'category': 'Bildung',
    'tag': 'Learning',
    'example': 'Nach dem Kurs bekomme ich ein Zertifikat.',
    'context': 'Official proof of completed training.',
    'contextDari': 'مدرک رسمی تکمیل آموزش.',
    'difficulty': 'easy',
    'isFavorite': false,
    'isDifficult': false,
  },
];

const List<Map<String, Object>> _generatedVocabularyBlueprints = [
  {'german': 'der Onboarding-Prozess', 'english': 'Onboarding process', 'dari': 'فرایند شروع', 'category': 'Bewerbung & Karriere', 'tag': 'HR', 'difficulty': 'medium'},
  {'german': 'die Stellenbeschreibung', 'english': 'Job description', 'dari': 'توضیح وظیفه', 'category': 'Bewerbung & Karriere', 'tag': 'HR', 'difficulty': 'easy'},
  {'german': 'das Kernteam', 'english': 'Core team', 'dari': 'تیم مرکزی', 'category': 'Meetings', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'der Tagesbericht', 'english': 'Daily report', 'dari': 'گزارش روزانه', 'category': 'Meetings', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Kostenanalyse', 'english': 'Cost analysis', 'dari': 'تحلیل هزینه', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'medium'},
  {'german': 'der Zahlungsplan', 'english': 'Payment plan', 'dari': 'برنامه پرداخت', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'easy'},
  {'german': 'die Haftung', 'english': 'Liability', 'dari': 'مسؤولیت حقوقی', 'category': 'Vertrage', 'tag': 'Legal', 'difficulty': 'hard'},
  {'german': 'die Vertragsbedingung', 'english': 'Contract term', 'dari': 'شرط قرارداد', 'category': 'Vertrage', 'tag': 'Legal', 'difficulty': 'medium'},
  {'german': 'die Prioritaet', 'english': 'Priority', 'dari': 'اولویت', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Ruecksprache', 'english': 'Consultation', 'dari': 'مشوره', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'medium'},
  {'german': 'die Zugriffsrolle', 'english': 'Access role', 'dari': 'نقش دسترسی', 'category': 'IT & Technik', 'tag': 'IT', 'difficulty': 'medium'},
  {'german': 'der Sicherheitscheck', 'english': 'Security check', 'dari': 'بررسی امنیتی', 'category': 'IT & Technik', 'tag': 'IT', 'difficulty': 'easy'},
  {'german': 'die Lead-Generierung', 'english': 'Lead generation', 'dari': 'تولید مشتری جدید', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'hard'},
  {'german': 'der Marktanteil', 'english': 'Market share', 'dari': 'سهم بازار', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'medium'},
  {'german': 'der Lernpfad', 'english': 'Learning path', 'dari': 'مسیر آموزش', 'category': 'Bildung', 'tag': 'Learning', 'difficulty': 'easy'},
  {'german': 'die Abschlusspruefung', 'english': 'Final exam', 'dari': 'آزمون پایانی', 'category': 'Bildung', 'tag': 'Learning', 'difficulty': 'medium'},
  {'german': 'die Lieferkette', 'english': 'Supply chain', 'dari': 'زنجیره تامین', 'category': 'Finanzen', 'tag': 'Finance', 'difficulty': 'hard'},
  {'german': 'die Produktivitaet', 'english': 'Productivity', 'dari': 'بهره وری', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'das Zeitmanagement', 'english': 'Time management', 'dari': 'مدیریت زمان', 'category': 'Buro Kommunikation', 'tag': 'Office', 'difficulty': 'easy'},
  {'german': 'die Kundenbindung', 'english': 'Customer retention', 'dari': 'حفظ مشتری', 'category': 'Marketing', 'tag': 'Marketing', 'difficulty': 'hard'},
];

const _businessDomainSeedStart = 200;
const List<Map<String, String>> _businessDomainVocabularyBatch1Blueprints = [
  {
    'german': 'die Abteilung',
    'english': 'department',
    'dari': 'بخش',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Bereich',
    'english': 'division',
    'dari': 'حوزه',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Einheit',
    'english': 'unit',
    'dari': 'واحد',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Niederlassung',
    'english': 'branch office',
    'dari': 'شعبه',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Zentrale',
    'english': 'headquarters',
    'dari': 'مرکز اصلی',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'das Tochterunternehmen',
    'english': 'subsidiary',
    'dari': 'شرکت تابعه',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Muttergesellschaft',
    'english': 'parent company',
    'dari': 'شرکت مادر',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Unternehmensgruppe',
    'english': 'corporate group',
    'dari': 'گروه شرکتی',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Holding',
    'english': 'holding company',
    'dari': 'هولدینگ',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'hard',
  },
  {
    'german': 'das Organigramm',
    'english': 'org chart',
    'dari': 'چارت سازمانی',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Hierarchie',
    'english': 'hierarchy',
    'dari': 'سلسله مراتب',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Leitungsebene',
    'english': 'management level',
    'dari': 'سطح مدیریت',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Vorstand',
    'english': 'board of directors',
    'dari': 'هیئت مدیره',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'die Geschaeftsleitung',
    'english': 'executive management',
    'dari': 'مدیریت ارشد',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'die Geschaeftsfuehrung',
    'english': 'company management',
    'dari': 'مدیریت شرکت',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Geschaeftsbereich',
    'english': 'business unit',
    'dari': 'حوزه کسب و کار',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Standort',
    'english': 'site location',
    'dari': 'محل',
    'category': 'Unternehmensstruktur',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Rechtsform',
    'english': 'legal form',
    'dari': 'نوع حقوقی',
    'category': 'Unternehmensstruktur',
    'tag': 'Legal',
    'difficulty': 'hard',
  },
  {
    'german': 'die Konzernstruktur',
    'english': 'corporate structure',
    'dari': 'ساختار کنسرن',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'hard',
  },
  {
    'german': 'die Berichtslinie',
    'english': 'reporting line',
    'dari': 'خط گزارش دهی',
    'category': 'Unternehmensstruktur',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Geschaeftsfuehrer',
    'english': 'managing director',
    'dari': 'مدیرعامل',
    'category': 'Berufsrollen',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Projektmanager',
    'english': 'project manager',
    'dari': 'مدیر پروژه',
    'category': 'Berufsrollen',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Produktmanager',
    'english': 'product manager',
    'dari': 'مدیر محصول',
    'category': 'Berufsrollen',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Vertriebsleiter',
    'english': 'sales manager',
    'dari': 'مدیر فروش',
    'category': 'Berufsrollen',
    'tag': 'Sales',
    'difficulty': 'medium',
  },
  {
    'german': 'der Marketingleiter',
    'english': 'marketing manager',
    'dari': 'مدیر بازاریابی',
    'category': 'Berufsrollen',
    'tag': 'Marketing',
    'difficulty': 'medium',
  },
  {
    'german': 'der Finanzleiter',
    'english': 'finance manager',
    'dari': 'مدیر مالی',
    'category': 'Berufsrollen',
    'tag': 'Finance',
    'difficulty': 'medium',
  },
  {
    'german': 'der Personalreferent',
    'english': 'HR specialist',
    'dari': 'کارشناس منابع انسانی',
    'category': 'Berufsrollen',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'der Buchhalter',
    'english': 'accountant',
    'dari': 'حسابدار',
    'category': 'Berufsrollen',
    'tag': 'Finance',
    'difficulty': 'easy',
  },
  {
    'german': 'der Controller',
    'english': 'financial controller',
    'dari': 'کنترولر مالی',
    'category': 'Berufsrollen',
    'tag': 'Finance',
    'difficulty': 'hard',
  },
  {
    'german': 'der Einkaeufer',
    'english': 'buyer',
    'dari': 'مسؤول خرید',
    'category': 'Berufsrollen',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Lagerleiter',
    'english': 'warehouse manager',
    'dari': 'مدیر انبار',
    'category': 'Berufsrollen',
    'tag': 'Logistics',
    'difficulty': 'medium',
  },
  {
    'german': 'der Kundenbetreuer',
    'english': 'account manager',
    'dari': 'مسؤول مشتری',
    'category': 'Berufsrollen',
    'tag': 'Sales',
    'difficulty': 'medium',
  },
  {
    'german': 'der Berater',
    'english': 'consultant',
    'dari': 'مشاور',
    'category': 'Berufsrollen',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Analyst',
    'english': 'analyst',
    'dari': 'تحلیلگر',
    'category': 'Berufsrollen',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Ingenieur',
    'english': 'engineer',
    'dari': 'مهندس',
    'category': 'Berufsrollen',
    'tag': 'Engineering',
    'difficulty': 'easy',
  },
  {
    'german': 'die Sekretaerin',
    'english': 'secretary',
    'dari': 'منشی',
    'category': 'Berufsrollen',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Sachbearbeiter',
    'english': 'clerk',
    'dari': 'کارشناس اداری',
    'category': 'Berufsrollen',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Qualitaetsmanager',
    'english': 'quality manager',
    'dari': 'مدیر کیفیت',
    'category': 'Berufsrollen',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Teamleiter',
    'english': 'team lead',
    'dari': 'سرپرست تیم',
    'category': 'Berufsrollen',
    'tag': 'Management',
    'difficulty': 'medium',
  },
  {
    'german': 'der Softwareentwickler',
    'english': 'software developer',
    'dari': 'توسعه دهنده نرم افزار',
    'category': 'Berufsrollen',
    'tag': 'IT',
    'difficulty': 'medium',
  },
  {
    'german': 'die Vakanz',
    'english': 'vacancy',
    'dari': 'سمت خالی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Bewerbungsunterlagen',
    'english': 'application documents',
    'dari': 'مدارک درخواست',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'das Anschreiben',
    'english': 'cover letter',
    'dari': 'نامه پوششی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'das Auswahlverfahren',
    'english': 'selection process',
    'dari': 'فرایند انتخاب',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'hard',
  },
  {
    'german': 'der Bewerber',
    'english': 'applicant',
    'dari': 'متقاضی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Bewerberin',
    'english': 'female applicant',
    'dari': 'متقاضی زن',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'das Assessment-Center',
    'english': 'assessment center',
    'dari': 'مرکز ارزیابی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'hard',
  },
  {
    'german': 'die Probeaufgabe',
    'english': 'trial task',
    'dari': 'وظیفه آزمایشی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'die Einstellung',
    'english': 'hiring',
    'dari': 'استخدام',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Zusage',
    'english': 'acceptance',
    'dari': 'پذیرش',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Absage',
    'english': 'rejection',
    'dari': 'رد',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Vertragsunterzeichnung',
    'english': 'contract signing',
    'dari': 'امضای قرارداد',
    'category': 'Recruiting',
    'tag': 'Legal',
    'difficulty': 'hard',
  },
  {
    'german': 'die Gehaltsvorstellung',
    'english': 'salary expectation',
    'dari': 'انتظار معاش',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'die Verfuegbarkeit',
    'english': 'availability',
    'dari': 'دسترس پذیری',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'das Eintrittsdatum',
    'english': 'start date',
    'dari': 'تاریخ شروع',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Probearbeit',
    'english': 'trial work',
    'dari': 'کار آزمایشی',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'die Referenz',
    'english': 'reference',
    'dari': 'مرجع',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'die Empfehlung',
    'english': 'recommendation',
    'dari': 'توصیه',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'die Einarbeitung',
    'english': 'onboarding training',
    'dari': 'آموزش اولیه',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'medium',
  },
  {
    'german': 'das Bewerbungsformular',
    'english': 'application form',
    'dari': 'فرم درخواست',
    'category': 'Recruiting',
    'tag': 'HR',
    'difficulty': 'easy',
  },
  {
    'german': 'der Schreibtisch',
    'english': 'desk',
    'dari': 'میز تحریر',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Bueroarbeitsplatz',
    'english': 'workstation',
    'dari': 'محل کار اداری',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Konferenzraum',
    'english': 'conference room',
    'dari': 'اتاق کنفرانس',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Teekueche',
    'english': 'pantry',
    'dari': 'آشپزخانه کوچک',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Kopierer',
    'english': 'copier',
    'dari': 'کاپی کننده',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Drucker',
    'english': 'printer',
    'dari': 'چاپگر',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'das Whiteboard',
    'english': 'whiteboard',
    'dari': 'وایت بورد',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Beamer',
    'english': 'projector',
    'dari': 'پروژکتور',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Empfang',
    'english': 'reception',
    'dari': 'پذیرش',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Poststelle',
    'english': 'mail room',
    'dari': 'بخش پست',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Aktenordner',
    'english': 'binder',
    'dari': 'کلایزر',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Aktenschrank',
    'english': 'filing cabinet',
    'dari': 'کمد دوسیه',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Steckdose',
    'english': 'power outlet',
    'dari': 'پریز برق',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Klimaanlage',
    'english': 'air conditioning',
    'dari': 'کولر',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Zugangskarte',
    'english': 'access card',
    'dari': 'کارت دسترسی',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Besucherausweis',
    'english': 'visitor badge',
    'dari': 'کارت مهمان',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Pausenraum',
    'english': 'break room',
    'dari': 'اتاق استراحت',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Hausordnung',
    'english': 'office rules',
    'dari': 'قوانین داخلی',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'das Bueroinventar',
    'english': 'office equipment',
    'dari': 'اثاثیه اداری',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Sitzordnung',
    'english': 'seating plan',
    'dari': 'چیدمان صندلی',
    'category': 'Bueroumgebung',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Aufgabe',
    'english': 'task',
    'dari': 'وظیفه',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'der Auftrag',
    'english': 'assignment',
    'dari': 'دستور کار',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Verantwortlichkeit',
    'english': 'responsibility',
    'dari': 'مسؤولیت',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Zuweisung',
    'english': 'assignment allocation',
    'dari': 'تخصیص',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Bearbeitung',
    'english': 'processing',
    'dari': 'رسیدگی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Recherche',
    'english': 'research',
    'dari': 'تحقیق',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Analyse',
    'english': 'analysis',
    'dari': 'تحلیل',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Freigabe',
    'english': 'approval',
    'dari': 'تایید',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'der Bericht',
    'english': 'report',
    'dari': 'گزارش',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Priorisierung',
    'english': 'prioritization',
    'dari': 'اولویت بندی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Kontrolle',
    'english': 'review',
    'dari': 'کنترول',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Umsetzung',
    'english': 'implementation',
    'dari': 'اجرا',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Terminierung',
    'english': 'scheduling',
    'dari': 'زمان بندی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Korrektur',
    'english': 'correction',
    'dari': 'اصلاح',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'easy',
  },
  {
    'german': 'die Auswertung',
    'english': 'evaluation',
    'dari': 'ارزیابی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Archivierung',
    'english': 'archiving',
    'dari': 'آرشیف',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Ablage',
    'english': 'filing',
    'dari': 'بایگانی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Ueberarbeitung',
    'english': 'revision',
    'dari': 'بازنگری',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Dokumentation',
    'english': 'documentation',
    'dari': 'مستندسازی',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
  {
    'german': 'die Nachverfolgung',
    'english': 'follow-up',
    'dari': 'پیگیری',
    'category': 'Arbeitsaufgaben',
    'tag': 'Office',
    'difficulty': 'medium',
  },
];

final List<Map<String, Object>> vocabularySeedExpansion = [
  ..._manualVocabularySeedExpansion,
  ..._buildGeneratedVocabularySeed(),
  ..._buildVocabularySeedFromBlueprints(
    _businessDomainSeedStart,
    _businessDomainVocabularyBatch1Blueprints,
  ),
];

const List<Map<String, Object>> _manualExerciseSeedExpansion = [
  {
    'id': 'e15',
    'type': 'multiple-choice',
    'question': 'Welches Wort passt zu: monatliche Zahlung an den Staat?',
    'options': ['die Steuer', 'die Frist', 'die Kampagne', 'der Vertrag'],
    'correctAnswer': 0,
    'topic': 'Finanzen',
    'level': 'A2',
  },
  {
    'id': 'e16',
    'type': 'multiple-choice',
    'question': "Was bedeutet 'der Lebenslauf'?",
    'options': ['invoice', 'resume', 'meeting', 'campaign'],
    'correctAnswer': 1,
    'topic': 'Bewerbung',
    'level': 'A1',
  },
  {
    'id': 'e17',
    'type': 'fill-in-blank',
    'question': 'Wir bleiben ___ Budget.',
    'options': ['im', 'in den', 'an', 'zu'],
    'correctAnswer': 0,
    'topic': 'Praepositionen',
    'level': 'A2',
  },
  {
    'id': 'e18',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Wartung' = ?",
    'options': ['maintenance', 'tax', 'extension', 'agenda'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'A2',
  },
  {
    'id': 'e19',
    'type': 'multiple-choice',
    'question': 'Die Probezeit dauert ___ Monate.',
    'options': ['sechs', 'sechzig', 'fuenfzehn', 'zweiundzwanzig'],
    'correctAnswer': 0,
    'topic': 'Bewerbung',
    'level': 'A2',
  },
  {
    'id': 'e20',
    'type': 'fill-in-blank',
    'question': 'Bitte senden Sie mir den Bericht ___ E-Mail.',
    'options': ['per', 'durch', 'von', 'gegen'],
    'correctAnswer': 0,
    'topic': 'Business',
    'level': 'B1',
  },
  {
    'id': 'e21',
    'type': 'sentence-order',
    'question': 'Ordnen Sie: wir / brauchen / heute / eine / Abstimmung',
    'options': [
      'Wir brauchen heute eine Abstimmung.',
      'Heute brauchen eine wir Abstimmung.',
      'Eine Abstimmung wir brauchen heute.',
      'Brauchen wir Abstimmung heute eine.'
    ],
    'correctAnswer': 0,
    'topic': 'Satzbau',
    'level': 'A2',
  },
  {
    'id': 'e22',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Berechtigung' = ?",
    'options': ['permission', 'deadline', 'offer', 'certificate'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'B1',
  },
  {
    'id': 'e23',
    'type': 'multiple-choice',
    'question': 'Welcher Ausdruck ist in einer E-Mail formell?',
    'options': ['Hi, was geht?', 'Sehr geehrte Damen und Herren', 'Yo, danke!', 'Hey Team'],
    'correctAnswer': 1,
    'topic': 'Business',
    'level': 'A1',
  },
  {
    'id': 'e24',
    'type': 'fill-in-blank',
    'question': 'Die Rechnung ist im ___.',
    'options': ['Anhang', 'Kampagne', 'Budget', 'Vertrieb'],
    'correctAnswer': 0,
    'topic': 'Office',
    'level': 'A1',
  },
  {
    'id': 'e25',
    'type': 'multiple-choice',
    'question': 'Was bedeutet "die Kuendigungsfrist"?',
    'options': ['notice period', 'brand awareness', 'cost center', 'pay slip'],
    'correctAnswer': 0,
    'topic': 'Vertraege',
    'level': 'B1',
  },
  {
    'id': 'e26',
    'type': 'matching',
    'question': "Welche Kombination ist richtig? 'die Gehaltsabrechnung' = ?",
    'options': ['pay slip', 'resume', 'signature', 'urgency'],
    'correctAnswer': 0,
    'topic': 'Bewerbung',
    'level': 'A2',
  },
  {
    'id': 'e27',
    'type': 'multiple-choice',
    'question': 'Welches Wort gehoert zur Kategorie Marketing?',
    'options': ['die Markenbekanntheit', 'die Klausel', 'der Anhang', 'die Wartung'],
    'correctAnswer': 0,
    'topic': 'Marketing',
    'level': 'B1',
  },
  {
    'id': 'e28',
    'type': 'fill-in-blank',
    'question': 'Wir muessen die Daten regelmaessig ___.',
    'options': ['sichern', 'zahlen', 'kuendigen', 'einladen'],
    'correctAnswer': 0,
    'topic': 'IT',
    'level': 'A2',
  },
  {
    'id': 'e29',
    'type': 'sentence-order',
    'question': 'Ordnen Sie: bitte / den / im / speichern / Anhang / Bericht',
    'options': [
      'Bitte den Bericht im Anhang speichern.',
      'Im speichern den Anhang Bericht bitte.',
      'Bericht im den Anhang bitte speichern.',
      'Speichern bitte Anhang den im Bericht.'
    ],
    'correctAnswer': 0,
    'topic': 'Satzbau',
    'level': 'B1',
  },
  {
    'id': 'e30',
    'type': 'multiple-choice',
    'question': 'Welche Aussage ist korrekt?',
    'options': [
      'Die Conversion-Rate ist eine Steuer.',
      'Die Conversion-Rate misst Zielhandlungen.',
      'Die Conversion-Rate ist ein Vertrag.',
      'Die Conversion-Rate ist eine Frist.'
    ],
    'correctAnswer': 1,
    'topic': 'Marketing',
    'level': 'B2',
  },
];

final List<Map<String, Object>> exerciseSeedExpansion = [
  ..._manualExerciseSeedExpansion,
  ..._buildGeneratedExerciseSeed(),
];

List<Map<String, Object>> _buildGeneratedVocabularySeed() {
  return _generatedVocabularyBlueprints.asMap().entries.map((entry) {
    final id = 'v${51 + entry.key}';
    final row = entry.value;
    final german = row['german']! as String;
    final english = row['english']! as String;
    final dari = row['dari']! as String;

    return {
      'id': id,
      'german': german,
      'phonetic': _phoneticFromGerman(german),
      'english': english,
      'dari': dari,
      'category': row['category']! as String,
      'tag': row['tag']! as String,
      'example': 'Im Arbeitsalltag nutzen wir den Begriff $german.',
      'context': 'Business term for $english in workplace communication.',
      'contextDari': 'اصطلاح کاری برای $dari در محیط کار.',
      'difficulty': row['difficulty']! as String,
      'isFavorite': false,
      'isDifficult': row['difficulty'] == 'hard',
    };
  }).toList();
}

List<Map<String, Object>> _buildVocabularySeedFromBlueprints(
  int startId,
  List<Map<String, String>> blueprints,
) {
  return blueprints.asMap().entries.map((entry) {
    final id = 'v${startId + entry.key}';
    final row = entry.value;
    final german = row['german']!;
    final english = row['english']!;
    final dari = row['dari']!;
    final difficulty = row['difficulty']!;

    return {
      'id': id,
      'german': german,
      'phonetic': _phoneticFromGerman(german),
      'english': english,
      'dari': dari,
      'category': row['category']!,
      'tag': row['tag']!,
      'example': 'Im Arbeitsalltag ist $german wichtig.',
      'context': 'Common business term for $english.',
      'contextDari': 'اصطلاح رایج در محیط کار برای $dari.',
      'difficulty': difficulty,
      'isFavorite': false,
      'isDifficult': difficulty == 'hard',
    };
  }).toList();
}

String _phoneticFromGerman(String german) {
  final normalized = german
      .toLowerCase()
      .replaceAll('ae', 'a')
      .replaceAll('oe', 'o')
      .replaceAll('ue', 'u')
      .replaceAll(RegExp(r'[^a-z0-9 ]'), '')
      .trim()
      .replaceAll(RegExp(r'\s+'), '-');
  return '/$normalized/';
}

List<Map<String, Object>> _buildGeneratedExerciseSeed() {
  final vocabulary = [...vocabularySeed, ...vocabularySeedExpansion];
  final generated = <Map<String, Object>>[];
  final levelCycle = ['A1', 'A2', 'B1', 'B2'];

  final exerciseCount = vocabulary.length < 60 ? vocabulary.length : 60;
  for (var i = 0; i < exerciseCount; i++) {
    final current = vocabulary[i];
    final category = current['category']! as String;
    final level = levelCycle[i % levelCycle.length];
    final id = 'e${101 + i}';

    final currentGerman = current['german']! as String;
    final currentEnglish = current['english']! as String;

    final d1 = vocabulary[(i + 1) % vocabulary.length]['english']! as String;
    final d2 = vocabulary[(i + 2) % vocabulary.length]['english']! as String;
    final d3 = vocabulary[(i + 3) % vocabulary.length]['english']! as String;

    if (i % 4 == 0) {
      generated.add({
        'id': id,
        'type': 'multiple-choice',
        'question': "Was bedeutet '$currentGerman'?",
        'options': [currentEnglish, d1, d2, d3],
        'correctAnswer': 0,
        'topic': category,
        'level': level,
      });
      continue;
    }

    if (i % 4 == 1) {
      generated.add({
        'id': id,
        'type': 'matching',
        'question': "Welche Kombination ist richtig? '$currentGerman' = ?",
        'options': [currentEnglish, d1, d2, d3],
        'correctAnswer': 0,
        'topic': category,
        'level': level,
      });
      continue;
    }

    if (i % 4 == 2) {
      final g1 = vocabulary[(i + 1) % vocabulary.length]['german']! as String;
      final g2 = vocabulary[(i + 2) % vocabulary.length]['german']! as String;
      final g3 = vocabulary[(i + 3) % vocabulary.length]['german']! as String;
      generated.add({
        'id': id,
        'type': 'fill-in-blank',
        'question': 'Im Meeting sprechen wir ueber ___.',
        'options': [g1, currentGerman, g2, g3],
        'correctAnswer': 1,
        'topic': category,
        'level': level,
      });
      continue;
    }

    generated.add({
      'id': id,
      'type': 'sentence-order',
      'question': 'Ordnen Sie: wir / nutzen / im Buero / $currentGerman',
      'options': [
        'Wir nutzen im Buero $currentGerman.',
        'Im Buero nutzen wir $currentGerman.',
        '$currentGerman nutzen wir im Buero.',
        'Wir im Buero $currentGerman nutzen.'
      ],
      'correctAnswer': 0,
      'topic': category,
      'level': level,
    });
  }

  return generated;
}
