// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7dBObfAx6mcFPyczn79VHCzpWKX895Q',
    appId: '1:67274485975:web:efb489ba6e62c3d2cdc092',
    messagingSenderId: '67274485975',
    projectId: 'deutschlernen-7aaf5',
    authDomain: 'deutschlernen-7aaf5.firebaseapp.com',
    storageBucket: 'deutschlernen-7aaf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9xpjMwrP8AI3n5KftWoy4HAdNxrary0',
    appId: '1:67274485975:android:9cc00762a54a0ca4cdc092',
    messagingSenderId: '67274485975',
    projectId: 'deutschlernen-7aaf5',
    storageBucket: 'deutschlernen-7aaf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPO8GfuRGFHFOjdW-Orq4HCRtCiPgB3NM',
    appId: '1:67274485975:ios:e5e13a9ad4a0e468cdc092',
    messagingSenderId: '67274485975',
    projectId: 'deutschlernen-7aaf5',
    storageBucket: 'deutschlernen-7aaf5.firebasestorage.app',
    iosBundleId: 'com.example.deutschlernenMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPO8GfuRGFHFOjdW-Orq4HCRtCiPgB3NM',
    appId: '1:67274485975:ios:e5e13a9ad4a0e468cdc092',
    messagingSenderId: '67274485975',
    projectId: 'deutschlernen-7aaf5',
    storageBucket: 'deutschlernen-7aaf5.firebasestorage.app',
    iosBundleId: 'com.example.deutschlernenMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR7dBObfAx6mcFPyczn79VHCzpWKX895Q',
    appId: '1:67274485975:web:e118254697fc8797cdc092',
    messagingSenderId: '67274485975',
    projectId: 'deutschlernen-7aaf5',
    authDomain: 'deutschlernen-7aaf5.firebaseapp.com',
    storageBucket: 'deutschlernen-7aaf5.firebasestorage.app',
  );
}
