import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

// ─── Models ───────────────────────────────────────────────────────────────────
class VocabWord {
  VocabWord(
      {required this.id,
      required this.german,
      required this.phonetic,
      required this.english,
      required this.dari,
      required this.category,
      required this.tag,
      required this.example,
      required this.context,
      required this.contextDari,
      required this.difficulty,
      this.isFavorite = false,
      this.isDifficult = false});
  final String id,
      german,
      phonetic,
      english,
      dari,
      category,
      tag,
      example,
      context,
      contextDari;
  String difficulty;
  bool isFavorite, isDifficult;
}

class BizCategory {
  const BizCategory(
      {required this.name,
      required this.icon,
      required this.gradient,
      required this.count});
  final String name, icon;
  final List<Color> gradient;
  final int count;
}

const _categories = [
  BizCategory(
      name: 'Bewerbung & Karriere',
      icon: '💼',
      gradient: [Color(0xFF6366F1), Color(0xFF4F46E5)],
      count: 12),
  BizCategory(
      name: 'Meetings',
      icon: '🤝',
      gradient: [Color(0xFF0EA5E9), Color(0xFF0284C7)],
      count: 8),
  BizCategory(
      name: 'Finanzen',
      icon: '💰',
      gradient: [Color(0xFF22C55E), Color(0xFF15803D)],
      count: 10),
  BizCategory(
      name: 'Büro Kommunikation',
      icon: '📧',
      gradient: [Color(0xFFF59E0B), Color(0xFFD97706)],
      count: 9),
  BizCategory(
      name: 'IT & Technik',
      icon: '💻',
      gradient: [Color(0xFF8B5CF6), Color(0xFF7C3AED)],
      count: 6),
  BizCategory(
      name: 'Verträge',
      icon: '📋',
      gradient: [Color(0xFFEC4899), Color(0xFFDB2777)],
      count: 6),
  BizCategory(
      name: 'Marketing',
      icon: '📢',
      gradient: [Color(0xFFF97316), Color(0xFFEA580C)],
      count: 7),
  BizCategory(
      name: 'Bildung',
      icon: '🎓',
      gradient: [Color(0xFF14B8A6), Color(0xFF0D9488)],
      count: 12),
];

// Sample words — replace with Riverpod provider
final _sampleWords = [
  VocabWord(
      id: 'v1',
      german: 'die Bewerbung',
      phonetic: '/bəˈvɛʁbʊŋ/',
      english: 'Application (job)',
      dari: 'درخواستی',
      category: 'Bewerbung & Karriere',
      tag: 'HR',
      example: 'Ich schicke meine Bewerbung morgen ab.',
      difficulty: 'easy',
      context: 'Used when applying for a job position.',
      contextDari: 'هنگام درخواست دادن برای موقعیت کاری'),
  VocabWord(
      id: 'v2',
      german: 'das Vorstellungsgespräch',
      phonetic: '/ˈfoːɐ̯ʃtɛlʊŋsɡəˌʃpʁɛːç/',
      english: 'Job interview',
      dari: 'مصاحبه کاری',
      category: 'Bewerbung & Karriere',
      tag: 'HR',
      example: 'Mein Vorstellungsgespräch ist am Montag.',
      difficulty: 'medium',
      context: 'The formal meeting between employer and candidate.',
      contextDari: 'ملاقات رسمی بین کارفرما و کاندید'),
  VocabWord(
      id: 'v3',
      german: 'die Besprechung',
      phonetic: '/bəˈʃpʁɛçʊŋ/',
      english: 'Meeting',
      dari: 'جلسه',
      category: 'Meetings',
      tag: 'Office',
      example: 'Die Besprechung beginnt um 10 Uhr.',
      difficulty: 'easy',
      context: 'A formal meeting in a business setting.',
      contextDari: 'یک جلسه رسمی در محیط کاری',
      isFavorite: true),
  VocabWord(
      id: 'v4',
      german: 'der Umsatz',
      phonetic: '/ˈʊmzats/',
      english: 'Revenue / Turnover',
      dari: 'عواید',
      category: 'Finanzen',
      tag: 'Finance',
      example: 'Der Umsatz ist dieses Quartal gestiegen.',
      difficulty: 'medium',
      context: 'Total revenue generated by a company.',
      contextDari: 'مجموع عواید تولید شده توسط یک شرکت'),
  VocabWord(
      id: 'v5',
      german: 'die Rechnung',
      phonetic: '/ˈʁɛçnʊŋ/',
      english: 'Invoice / Bill',
      dari: 'فاکتور',
      category: 'Finanzen',
      tag: 'Finance',
      example: 'Bitte senden Sie mir die Rechnung.',
      difficulty: 'easy',
      context: 'A document requesting payment.',
      contextDari: 'سندی که درخواست پرداخت می‌کند'),
  VocabWord(
      id: 'v6',
      german: 'der Vertrag',
      phonetic: '/fɛɐ̯ˈtʁaːk/',
      english: 'Contract',
      dari: 'قرارداد',
      category: 'Verträge',
      tag: 'Legal',
      example: 'Wir müssen den Vertrag unterschreiben.',
      difficulty: 'easy',
      context: 'A legally binding agreement.',
      contextDari: 'یک توافقنامه قانونی',
      isFavorite: true),
];

final _phrases = [
  (
    german: 'Sehr geehrte Damen und Herren',
    english: 'Dear Sir or Madam',
    dari: 'خانم‌ها و آقایان محترم',
    tag: 'Formal'
  ),
  (
    german: 'Mit freundlichen Grüßen',
    english: 'Kind regards',
    dari: 'با احترام',
    tag: 'Formal'
  ),
  (
    german: 'Könnten Sie mir bitte helfen?',
    english: 'Could you please help me?',
    dari: 'آیا می‌توانید کمکم کنید؟',
    tag: 'Polite'
  ),
  (
    german: 'Ich möchte mich vorstellen',
    english: 'I would like to introduce myself',
    dari: 'می‌خواهم خودم را معرفی کنم',
    tag: 'Meeting'
  ),
  (
    german: 'Wie besprochen...',
    english: 'As discussed...',
    dari: 'طوری که بحث شد...',
    tag: 'Email'
  ),
  (
    german: 'Im Anhang finden Sie...',
    english: 'Please find attached...',
    dari: 'در پیوست می‌یابید...',
    tag: 'Email'
  ),
];

// ─── VocabularyPage ───────────────────────────────────────────────────────────
class VocabularyPage extends ConsumerStatefulWidget {
  const VocabularyPage({super.key});
  @override
  ConsumerState<VocabularyPage> createState() => _VocabularyPageState();
}

class _VocabularyPageState extends ConsumerState<VocabularyPage> {
  String _tab = 'words';
  String _search = '';
  String? _selectedCategory;
  bool _flashcardMode = false;
  VocabWord? _selectedWord;
  int _flashcardIndex = 0;
  bool _isFlipped = false;
  bool _isDari = false;

  final _tabs = const [
    ('words', 'Wörter'),
    ('phrases', 'Phrasen'),
    ('favorites', 'Favoriten'),
    ('difficult', 'Schwierig'),
  ];

  late final List<VocabWord> _words = _sampleWords
      .map((w) => VocabWord(
            id: w.id,
            german: w.german,
            phonetic: w.phonetic,
            english: w.english,
            dari: w.dari,
            category: w.category,
            tag: w.tag,
            example: w.example,
            context: w.context,
            contextDari: w.contextDari,
            difficulty: w.difficulty,
            isFavorite: w.isFavorite,
            isDifficult: w.isDifficult,
          ))
      .toList();

  List<VocabWord> get _filtered {
    return _words.where((w) {
      if (_tab == 'favorites' && !w.isFavorite) return false;
      if (_tab == 'difficult' && !w.isDifficult) return false;
      if (_selectedCategory != null && w.category != _selectedCategory)
        return false;
      if (_search.isNotEmpty) {
        final s = _search.toLowerCase();
        if (!w.german.toLowerCase().contains(s) &&
            !w.english.toLowerCase().contains(s)) return false;
      }
      return true;
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    if (_flashcardMode) return _buildFlashcard(isDark);
    if (_selectedWord != null) return _buildWordDetail(isDark);
    return _buildMain(isDark);
  }

  // ── MAIN VIEW ─────────────────────────────────────────────────────────────
  Widget _buildMain(bool isDark) {
    final textPrimary = isDark ? Colors.white : const Color(0xFF111827);
    final textMuted =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF6B7280);
    final cardColor = isDark ? const Color(0xFF0F172A) : Colors.white;
    final tabBg = isDark ? const Color(0xFF1E293B) : const Color(0xFFF1F5F9);
    final filtered = _filtered;

    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(20, 24, 20, 16),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        // Header
        Row(children: [
          _BackButton(isDark: isDark, onTap: () => context.go('/')),
          const SizedBox(width: 12),
          Expanded(
              child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                Text('Wortschatz 📚',
                    style: TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.w600,
                        color: textPrimary)),
                Text('Wörter & Business',
                    style: TextStyle(fontSize: 12, color: textMuted)),
              ])),
          // Lang toggle
          GestureDetector(
            onTap: () => setState(() => _isDari = !_isDari),
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 7),
              decoration: BoxDecoration(
                color: cardColor,
                borderRadius: BorderRadius.circular(12),
                boxShadow: [
                  BoxShadow(
                      color: Colors.black.withOpacity(0.07),
                      blurRadius: 8,
                      offset: const Offset(0, 2))
                ],
              ),
              child: Row(children: [
                const Icon(Icons.translate_rounded,
                    size: 15, color: Color(0xFF3B82F6)),
                const SizedBox(width: 5),
                Text(_isDari ? 'دری' : 'EN',
                    style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w500,
                        color: textPrimary)),
              ]),
            ),
          ),
        ]),

        const SizedBox(height: 14),

        // Search bar
        Container(
          decoration: BoxDecoration(
            color: cardColor,
            borderRadius: BorderRadius.circular(16),
            boxShadow: [
              BoxShadow(
                  color: Colors.black.withOpacity(0.06),
                  blurRadius: 10,
                  offset: const Offset(0, 3))
            ],
          ),
          child: TextField(
            onChanged: (v) => setState(() => _search = v),
            style: TextStyle(
                fontSize: 14,
                color: isDark ? Colors.white : const Color(0xFF111827)),
            decoration: InputDecoration(
              hintText: 'Wort suchen...',
              hintStyle: TextStyle(color: textMuted, fontSize: 14),
              prefixIcon:
                  Icon(Icons.search_rounded, color: textMuted, size: 20),
              border: InputBorder.none,
              contentPadding:
                  const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            ),
          ),
        ),

        const SizedBox(height: 12),

        // Tabs
        Container(
          padding: const EdgeInsets.all(4),
          decoration: BoxDecoration(
              color: tabBg, borderRadius: BorderRadius.circular(16)),
          child: Row(
              children: _tabs.map((t) {
            final active = _tab == t.$1;
            return Expanded(
              child: GestureDetector(
                onTap: () => setState(() {
                  _tab = t.$1;
                  _selectedCategory = null;
                }),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  decoration: BoxDecoration(
                    color: active ? cardColor : Colors.transparent,
                    borderRadius: BorderRadius.circular(12),
                    boxShadow: active
                        ? [
                            BoxShadow(
                                color: Colors.black.withOpacity(0.07),
                                blurRadius: 6,
                                offset: const Offset(0, 2))
                          ]
                        : null,
                  ),
                  child: Center(
                      child: Text(t.$2,
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w500,
                            color: active ? const Color(0xFF2563EB) : textMuted,
                          ))),
                ),
              ),
            );
          }).toList()),
        ),

        const SizedBox(height: 16),

        // Category grid (words tab, no category selected)
        if (_tab == 'words' &&
            _selectedCategory == null &&
            _search.isEmpty) ...[
          Text('Business-Kategorien',
              style: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.w600,
                  color: textPrimary)),
          const SizedBox(height: 12),
          GridView.count(
            crossAxisCount: 2,
            crossAxisSpacing: 10,
            mainAxisSpacing: 10,
            childAspectRatio: 1.5,
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            children: _categories
                .map((cat) => GestureDetector(
                      onTap: () => setState(() => _selectedCategory = cat.name),
                      child: Container(
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                              colors: cat.gradient,
                              begin: Alignment.topLeft,
                              end: Alignment.bottomRight),
                          borderRadius: BorderRadius.circular(18),
                          boxShadow: [
                            BoxShadow(
                                color: cat.gradient.first.withOpacity(0.3),
                                blurRadius: 10,
                                offset: const Offset(0, 4))
                          ],
                        ),
                        child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(cat.icon,
                                  style: const TextStyle(fontSize: 22)),
                              Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(cat.name,
                                        style: const TextStyle(
                                            fontSize: 12,
                                            fontWeight: FontWeight.w600,
                                            color: Colors.white),
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis),
                                    Text('${cat.count} Wörter',
                                        style: TextStyle(
                                            fontSize: 10,
                                            color:
                                                Colors.white.withOpacity(0.7))),
                                  ]),
                            ]),
                      ),
                    ))
                .toList(),
          ),
          const SizedBox(height: 16),

          // Flashcard CTA
          GestureDetector(
            onTap: () => setState(() {
              _flashcardMode = true;
              _flashcardIndex = 0;
              _isFlipped = false;
            }),
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(vertical: 16),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                    colors: [Color(0xFF3B82F6), Color(0xFF9333EA)]),
                borderRadius: BorderRadius.circular(16),
                boxShadow: [
                  BoxShadow(
                      color: const Color(0xFF6366F1).withOpacity(0.3),
                      blurRadius: 12,
                      offset: const Offset(0, 4))
                ],
              ),
              child: const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text('🎴', style: TextStyle(fontSize: 18)),
                    SizedBox(width: 8),
                    Text('Flashcard-Modus starten',
                        style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: Colors.white)),
                  ]),
            ),
          ),
        ] else ...[
          // Category breadcrumb
          if (_selectedCategory != null && _tab == 'words')
            Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: Row(children: [
                GestureDetector(
                  onTap: () => setState(() => _selectedCategory = null),
                  child: const Text('Alle Kategorien',
                      style: TextStyle(fontSize: 13, color: Color(0xFF3B82F6))),
                ),
                const Icon(Icons.chevron_right_rounded,
                    size: 14, color: Color(0xFF94A3B8)),
                Text(_selectedCategory!,
                    style: TextStyle(fontSize: 13, color: textPrimary)),
              ]),
            ),

          // Phrases tab
          if (_tab == 'phrases')
            ..._phrases.map((p) => Padding(
                  padding: const EdgeInsets.only(bottom: 10),
                  child: Container(
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: cardColor,
                      borderRadius: BorderRadius.circular(16),
                      boxShadow: [
                        BoxShadow(
                            color: Colors.black.withOpacity(0.05),
                            blurRadius: 8,
                            offset: const Offset(0, 2))
                      ],
                    ),
                    child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(children: [
                            Expanded(
                                child: Text(p.german,
                                    style: TextStyle(
                                        fontSize: 14,
                                        fontWeight: FontWeight.w600,
                                        color: textPrimary))),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 8, vertical: 3),
                              decoration: BoxDecoration(
                                color: isDark
                                    ? const Color(0xFF1E3A5F)
                                    : const Color(0xFFEFF6FF),
                                borderRadius: BorderRadius.circular(100),
                              ),
                              child: Text(p.tag,
                                  style: const TextStyle(
                                      fontSize: 10, color: Color(0xFF3B82F6))),
                            ),
                          ]),
                          const SizedBox(height: 4),
                          Text(_isDari ? p.dari : p.english,
                              style: TextStyle(fontSize: 12, color: textMuted)),
                        ]),
                  ),
                ))
          else
            // Word list
            ...filtered.map((w) => Padding(
                  padding: const EdgeInsets.only(bottom: 10),
                  child: GestureDetector(
                    onTap: () => setState(() => _selectedWord = w),
                    child: Container(
                      padding: const EdgeInsets.all(14),
                      decoration: BoxDecoration(
                        color: cardColor,
                        borderRadius: BorderRadius.circular(16),
                        boxShadow: [
                          BoxShadow(
                              color: Colors.black.withOpacity(0.05),
                              blurRadius: 8,
                              offset: const Offset(0, 2))
                        ],
                      ),
                      child: Row(children: [
                        Expanded(
                            child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                              Row(children: [
                                Text(w.german,
                                    style: TextStyle(
                                        fontSize: 14,
                                        fontWeight: FontWeight.w600,
                                        color: textPrimary)),
                                const SizedBox(width: 8),
                                Text(w.phonetic,
                                    style: TextStyle(
                                        fontSize: 11, color: textMuted)),
                              ]),
                              const SizedBox(height: 3),
                              Text(_isDari ? w.dari : w.english,
                                  style: TextStyle(
                                      fontSize: 12, color: textMuted)),
                            ])),
                        Row(children: [
                          _DifficultyDot(w.difficulty),
                          const SizedBox(width: 8),
                          GestureDetector(
                            onTap: () =>
                                setState(() => w.isFavorite = !w.isFavorite),
                            child: Icon(
                                w.isFavorite
                                    ? Icons.favorite_rounded
                                    : Icons.favorite_outline_rounded,
                                size: 18,
                                color: w.isFavorite
                                    ? const Color(0xFFEF4444)
                                    : textMuted),
                          ),
                        ]),
                      ]),
                    ),
                  ),
                )),

          if (filtered.isEmpty && _tab != 'phrases')
            Center(
                child: Padding(
              padding: const EdgeInsets.only(top: 32),
              child: Text('Keine Wörter gefunden',
                  style: TextStyle(fontSize: 14, color: textMuted)),
            )),
        ],
        const SizedBox(height: 8),
      ]),
    );
  }

  // ── WORD DETAIL ───────────────────────────────────────────────────────────
  Widget _buildWordDetail(bool isDark) {
    final w = _selectedWord!;
    final textPrimary = isDark ? Colors.white : const Color(0xFF111827);
    final textMuted =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF6B7280);
    final cardColor = isDark ? const Color(0xFF0F172A) : Colors.white;
    final translation = _isDari ? w.dari : w.english;
    final context_ = _isDari ? w.contextDari : w.context;

    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(20, 24, 20, 16),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          _BackButton(
              isDark: isDark,
              onTap: () => setState(() => _selectedWord = null)),
          const Spacer(),
          GestureDetector(
            onTap: () => setState(() => w.isFavorite = !w.isFavorite),
            child: Container(
              width: 36,
              height: 36,
              decoration: BoxDecoration(
                color: isDark ? const Color(0xFF1E293B) : Colors.white,
                borderRadius: BorderRadius.circular(12),
                boxShadow: [
                  BoxShadow(
                      color: Colors.black.withOpacity(0.08),
                      blurRadius: 8,
                      offset: const Offset(0, 2))
                ],
              ),
              child: Icon(
                  w.isFavorite
                      ? Icons.favorite_rounded
                      : Icons.favorite_outline_rounded,
                  size: 18,
                  color: w.isFavorite ? const Color(0xFFEF4444) : textMuted),
            ),
          ),
        ]),
        const SizedBox(height: 16),

        // Header card (blue→purple)
        Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(vertical: 28, horizontal: 20),
          decoration: BoxDecoration(
            gradient: const LinearGradient(
                colors: [Color(0xFF3B82F6), Color(0xFF9333EA)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight),
            borderRadius: BorderRadius.circular(24),
          ),
          child: Column(children: [
            Text(w.german,
                style: const TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.w700,
                    color: Colors.white)),
            const SizedBox(height: 6),
            Text(w.phonetic,
                style: TextStyle(
                    fontSize: 14, color: Colors.white.withOpacity(0.6))),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(100)),
              child: const Icon(Icons.volume_up_rounded,
                  size: 20, color: Colors.white),
            ),
          ]),
        ),

        const SizedBox(height: 14),

        _DetailCard(
            cardColor: cardColor,
            title: 'Bedeutung',
            child: Text(translation,
                style: TextStyle(
                    fontSize: 15,
                    color: isDark
                        ? const Color(0xFFCBD5E1)
                        : const Color(0xFF374151)),
                textDirection:
                    _isDari ? TextDirection.rtl : TextDirection.ltr)),

        const SizedBox(height: 10),

        _DetailCard(
            cardColor: cardColor,
            title: 'Beispielsatz',
            child: Text('"${w.example}"',
                style: TextStyle(
                    fontSize: 14,
                    fontStyle: FontStyle.italic,
                    color: isDark
                        ? const Color(0xFFCBD5E1)
                        : const Color(0xFF374151)))),

        const SizedBox(height: 10),

        _DetailCard(
            cardColor: cardColor,
            title: 'Business-Kontext',
            child:
                Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Text(context_,
                  style: TextStyle(
                      fontSize: 14,
                      color: isDark
                          ? const Color(0xFFCBD5E1)
                          : const Color(0xFF374151)),
                  textDirection:
                      _isDari ? TextDirection.rtl : TextDirection.ltr),
              const SizedBox(height: 8),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: isDark
                      ? const Color(0xFF1E3A5F)
                      : const Color(0xFFEFF6FF),
                  borderRadius: BorderRadius.circular(100),
                ),
                child: Text(w.tag,
                    style: const TextStyle(
                        fontSize: 11, color: Color(0xFF2563EB))),
              ),
            ])),

        const SizedBox(height: 14),

        Row(children: [
          Expanded(
              child: GestureDetector(
            onTap: () => setState(() {
              _flashcardMode = true;
              _selectedWord = null;
              _flashcardIndex = 0;
              _isFlipped = false;
            }),
            child: Container(
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                    colors: [Color(0xFF3B82F6), Color(0xFF9333EA)]),
                borderRadius: BorderRadius.circular(14),
              ),
              child: const Center(
                  child: Text('Flashcard starten',
                      style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: Colors.white))),
            ),
          )),
        ]),
      ]),
    );
  }

  // ── FLASHCARD MODE ────────────────────────────────────────────────────────
  Widget _buildFlashcard(bool isDark) {
    final words = _filtered.isNotEmpty ? _filtered : _words;
    if (words.isEmpty) return const Center(child: Text('Keine Wörter'));
    final w = words[_flashcardIndex % words.length];
    final progress = (_flashcardIndex + 1) / words.length;
    final textMuted =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF6B7280);

    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 24, 20, 16),
      child: Column(children: [
        // Top bar
        Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
          _BackButton(
              isDark: isDark,
              onTap: () => setState(() {
                    _flashcardMode = false;
                    _flashcardIndex = 0;
                    _isFlipped = false;
                  })),
          Text('${_flashcardIndex + 1} / ${words.length}',
              style: TextStyle(fontSize: 13, color: textMuted)),
        ]),
        const SizedBox(height: 14),

        // Progress
        ClipRRect(
          borderRadius: BorderRadius.circular(100),
          child: LinearProgressIndicator(
            value: progress,
            minHeight: 8,
            backgroundColor:
                isDark ? const Color(0xFF1E293B) : const Color(0xFFE2E8F0),
            valueColor: const AlwaysStoppedAnimation(Color(0xFF3B82F6)),
          ),
        ),
        const SizedBox(height: 32),

        // Flashcard
        Expanded(
          child: GestureDetector(
            onTap: () => setState(() => _isFlipped = !_isFlipped),
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 300),
              transitionBuilder: (child, anim) =>
                  RotationYTransition(turns: anim, child: child),
              child: _isFlipped
                  ? _FlashcardBack(
                      key: const ValueKey('back'), word: w, isDari: _isDari)
                  : _FlashcardFront(key: const ValueKey('front'), word: w),
            ),
          ),
        ),

        const SizedBox(height: 20),

        // Difficulty buttons
        Row(children: [
          Expanded(
              child: _DiffBtn(
                  label: 'Schwer',
                  emoji: '❌',
                  bg: isDark
                      ? const Color(0xFF450A0A)
                      : const Color(0xFFFFF1F2),
                  fg: const Color(0xFFEF4444),
                  onTap: () => _nextFlashcard('hard', words.length))),
          const SizedBox(width: 10),
          Expanded(
              child: _DiffBtn(
                  label: 'Mittel',
                  emoji: '🤔',
                  bg: isDark
                      ? const Color(0xFF1C1A09)
                      : const Color(0xFFFEFCE8),
                  fg: const Color(0xFFF59E0B),
                  onTap: () => _nextFlashcard('medium', words.length))),
          const SizedBox(width: 10),
          Expanded(
              child: _DiffBtn(
                  label: 'Leicht',
                  emoji: '✅',
                  bg: isDark
                      ? const Color(0xFF052E16)
                      : const Color(0xFFF0FDF4),
                  fg: const Color(0xFF22C55E),
                  onTap: () => _nextFlashcard('easy', words.length))),
        ]),
        const SizedBox(height: 8),
      ]),
    );
  }

  void _nextFlashcard(String difficulty, int total) {
    final words = _filtered.isNotEmpty ? _filtered : _words;
    final w = words[_flashcardIndex % words.length];
    setState(() {
      w.difficulty = difficulty;
      _isFlipped = false;
      _flashcardIndex = (_flashcardIndex + 1) % total;
    });
  }
}

// ─── Shared widgets ───────────────────────────────────────────────────────────

class _BackButton extends StatelessWidget {
  const _BackButton({required this.isDark, required this.onTap});
  final bool isDark;
  final VoidCallback onTap;
  @override
  Widget build(BuildContext context) => GestureDetector(
        onTap: onTap,
        child: Container(
          width: 36,
          height: 36,
          decoration: BoxDecoration(
            color: isDark ? const Color(0xFF1E293B) : Colors.white,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                  color: Colors.black.withOpacity(0.08),
                  blurRadius: 8,
                  offset: const Offset(0, 2))
            ],
          ),
          child: Icon(Icons.arrow_back_ios_new_rounded,
              size: 16,
              color:
                  isDark ? const Color(0xFF94A3B8) : const Color(0xFF374151)),
        ),
      );
}

class _DifficultyDot extends StatelessWidget {
  const _DifficultyDot(this.difficulty);
  final String difficulty;
  @override
  Widget build(BuildContext context) {
    final color = difficulty == 'easy'
        ? const Color(0xFF22C55E)
        : difficulty == 'hard'
            ? const Color(0xFFEF4444)
            : const Color(0xFFF59E0B);
    return Container(
        width: 8,
        height: 8,
        decoration: BoxDecoration(color: color, shape: BoxShape.circle));
  }
}

class _DetailCard extends StatelessWidget {
  const _DetailCard(
      {required this.cardColor, required this.title, required this.child});
  final Color cardColor;
  final String title;
  final Widget child;
  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: cardColor,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withOpacity(0.05),
              blurRadius: 8,
              offset: const Offset(0, 2))
        ],
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(title,
            style: TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w600,
                color: isDark
                    ? const Color(0xFF94A3B8)
                    : const Color(0xFF6B7280))),
        const SizedBox(height: 6),
        child,
      ]),
    );
  }
}

class _FlashcardFront extends StatelessWidget {
  const _FlashcardFront({super.key, required this.word});
  final VocabWord word;
  @override
  Widget build(BuildContext context) => Container(
        width: double.infinity,
        decoration: BoxDecoration(
          gradient: const LinearGradient(
              colors: [Color(0xFF3B82F6), Color(0xFF9333EA)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight),
          borderRadius: BorderRadius.circular(28),
          boxShadow: [
            BoxShadow(
                color: const Color(0xFF6366F1).withOpacity(0.3),
                blurRadius: 24,
                offset: const Offset(0, 10))
          ],
        ),
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          Text('Deutsch',
              style: TextStyle(
                  fontSize: 12, color: Colors.white.withOpacity(0.6))),
          const SizedBox(height: 12),
          Text(word.german,
              style: const TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.w700,
                  color: Colors.white),
              textAlign: TextAlign.center),
          const SizedBox(height: 8),
          Text(word.phonetic,
              style: TextStyle(
                  fontSize: 13, color: Colors.white.withOpacity(0.6))),
          const SizedBox(height: 24),
          Text('Tippen zum Umdrehen',
              style: TextStyle(
                  fontSize: 12, color: Colors.white.withOpacity(0.4))),
        ]),
      );
}

class _FlashcardBack extends StatelessWidget {
  const _FlashcardBack({super.key, required this.word, required this.isDari});
  final VocabWord word;
  final bool isDari;
  @override
  Widget build(BuildContext context) => Container(
        width: double.infinity,
        decoration: BoxDecoration(
          gradient: const LinearGradient(
              colors: [Color(0xFF22C55E), Color(0xFF0D9488)],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight),
          borderRadius: BorderRadius.circular(28),
          boxShadow: [
            BoxShadow(
                color: const Color(0xFF22C55E).withOpacity(0.3),
                blurRadius: 24,
                offset: const Offset(0, 10))
          ],
        ),
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          Text(isDari ? 'دری' : 'English',
              style: TextStyle(
                  fontSize: 12, color: Colors.white.withOpacity(0.6))),
          const SizedBox(height: 12),
          Text(isDari ? word.dari : word.english,
              style: const TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.w700,
                  color: Colors.white),
              textAlign: TextAlign.center),
          const SizedBox(height: 14),
          Container(
            margin: const EdgeInsets.symmetric(horizontal: 24),
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.2),
                borderRadius: BorderRadius.circular(16)),
            child: Text(word.example,
                style: TextStyle(
                    fontSize: 13, color: Colors.white.withOpacity(0.9)),
                textAlign: TextAlign.center),
          ),
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
            decoration: BoxDecoration(
                color: Colors.white.withOpacity(0.2),
                borderRadius: BorderRadius.circular(100)),
            child: Text(word.tag,
                style: const TextStyle(fontSize: 11, color: Colors.white)),
          ),
        ]),
      );
}

class _DiffBtn extends StatelessWidget {
  const _DiffBtn(
      {required this.label,
      required this.emoji,
      required this.bg,
      required this.fg,
      required this.onTap});
  final String label, emoji;
  final Color bg, fg;
  final VoidCallback onTap;
  @override
  Widget build(BuildContext context) => GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 14),
          decoration:
              BoxDecoration(color: bg, borderRadius: BorderRadius.circular(16)),
          child: Column(children: [
            Text(emoji, style: const TextStyle(fontSize: 20)),
            const SizedBox(height: 4),
            Text(label,
                style: TextStyle(
                    fontSize: 12, fontWeight: FontWeight.w500, color: fg)),
          ]),
        ),
      );
}

// Simple Y-rotation transition for flashcard flip
class RotationYTransition extends AnimatedWidget {
  const RotationYTransition(
      {super.key, required Animation<double> turns, required this.child})
      : super(listenable: turns);
  final Widget child;
  @override
  Widget build(BuildContext context) {
    final turns = (listenable as Animation<double>).value;
    return Transform(
      transform: Matrix4.rotationY((1 - turns) * 3.1416),
      alignment: Alignment.center,
      child: child,
    );
  }
}
