// ─── vocabulary_data_session2.dart ──────────────────────────────────────────
// Session 2 — 90 words across 4 categories
//
// HOW TO USE:
//   In vocabulary_data.dart, at the bottom of the `vocabularyData` list,
//   add:  ...vocabularyDataSession2,
//
// ─────────────────────────────────────────────────────────────────────────────

import 'vocabulary_data.dart';

final vocabularyDataSession2 = <VocabWord>[

  // ═══════════════════════════════════════════════════════════════════════════
  // IT & TECHNIK  (IT & Technology)  — 24 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'it01', german: 'das Passwort', phonetic: '/ˈpasvɔʁt/', english: 'Password', dari: 'پسورد / رمز عبور',
      category: 'IT & Technik', tag: 'Security',
      example: 'Bitte ändern Sie Ihr Passwort regelmäßig.',
      context: 'A secret word or code used to access a system.',
      contextDari: 'یک کلمه یا کد محرمانه برای دسترسی به یک سیستم.',
      difficulty: 'easy'),

  VocabWord(id: 'it02', german: 'der Benutzername', phonetic: '/bəˈnʊt͡sɐˌnaːmə/', english: 'Username / Login name', dari: 'نام کاربری / یوزرنیم',
      category: 'IT & Technik', tag: 'Security',
      example: 'Bitte geben Sie Ihren Benutzernamen ein.',
      context: 'The name used to identify a user when logging in.',
      contextDari: 'نامی که برای شناسایی کاربر هنگام ورود استفاده می‌شود.',
      difficulty: 'easy'),

  VocabWord(id: 'it03', german: 'die Cloud', phonetic: '/klaʊ̯d/', english: 'Cloud (storage/computing)', dari: 'کلاود / فضای ابری',
      category: 'IT & Technik', tag: 'Infrastructure',
      example: 'Die Dateien werden in der Cloud gespeichert.',
      context: 'Remote servers accessed via the internet for storage.',
      contextDari: 'سرورهای راه دور که از طریق اینترنت برای ذخیره‌سازی دسترسی دارند.',
      difficulty: 'easy'),

  VocabWord(id: 'it04', german: 'die Datensicherung', phonetic: '/ˈdaːtn̩ˌzɪçəʁʊŋ/', english: 'Data backup', dari: 'پشتیبان‌گیری / بکاپ',
      category: 'IT & Technik', tag: 'Data',
      example: 'Erstellen Sie täglich eine Datensicherung.',
      context: 'Copying data so it can be restored if lost.',
      contextDari: 'کپی کردن داده‌ها تا در صورت از دست رفتن بازیابی شود.',
      difficulty: 'medium'),

  VocabWord(id: 'it05', german: 'der Datenschutz', phonetic: '/ˈdaːtn̩ˌʃʊt͡s/', english: 'Data protection / Privacy', dari: 'حفاظت از داده / حریم خصوصی',
      category: 'IT & Technik', tag: 'Security',
      example: 'Der Datenschutz ist in Deutschland sehr wichtig.',
      context: 'Laws and practices to protect personal data (e.g. GDPR).',
      contextDari: 'قوانین و شیوه‌ها برای حفاظت از داده‌های شخصی (مثلاً GDPR).',
      difficulty: 'medium'),

  VocabWord(id: 'it06', german: 'die Firewall', phonetic: '/ˈfaɪ̯ɐˌvɔːl/', english: 'Firewall', dari: 'فایروال / دیوار آتش',
      category: 'IT & Technik', tag: 'Security',
      example: 'Die Firewall blockiert unerwünschte Verbindungen.',
      context: 'A system that monitors and controls network traffic.',
      contextDari: 'سیستمی که ترافیک شبکه را نظارت و کنترل می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'it07', german: 'das Update', phonetic: '/ˈʌpdeɪ̯t/', english: 'Update / Patch', dari: 'آپدیت / بروزرسانی',
      category: 'IT & Technik', tag: 'Software',
      example: 'Bitte installieren Sie das neueste Update.',
      context: 'A newer version of software that fixes or improves it.',
      contextDari: 'نسخه جدیدتر نرم‌افزاری که آن را اصلاح یا بهبود می‌دهد.',
      difficulty: 'easy'),

  VocabWord(id: 'it08', german: 'abstürzen', phonetic: '/ˈapˌʃtʏʁt͡sn̩/', english: 'To crash (program/system)', dari: 'کرش کردن / از کار افتادن',
      category: 'IT & Technik', tag: 'Software',
      example: 'Das Programm ist abgestürzt. Ich muss es neu starten.',
      context: 'When a computer program stops working unexpectedly.',
      contextDari: 'وقتی یک برنامه کامپیوتری به طور غیرمنتظره متوقف می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'it09', german: 'neu starten', phonetic: '/nɔɪ̯ ˈʃtaʁtn̩/', english: 'To restart / To reboot', dari: 'ریستارت کردن / دوباره روشن کردن',
      category: 'IT & Technik', tag: 'Hardware',
      example: 'Bitte starten Sie den Computer neu.',
      context: 'To restart a computer or device.',
      contextDari: 'ریستارت کردن یک کامپیوتر یا دستگاه.',
      difficulty: 'easy'),

  VocabWord(id: 'it10', german: 'herunterladen', phonetic: '/heˈʁʊntɐˌlaːdn̩/', english: 'To download', dari: 'دانلود کردن',
      category: 'IT & Technik', tag: 'Internet',
      example: 'Ich lade die Datei herunter.',
      context: 'To transfer data from the internet to your device.',
      contextDari: 'انتقال داده از اینترنت به دستگاه شما.',
      difficulty: 'easy'),

  VocabWord(id: 'it11', german: 'hochladen', phonetic: '/ˈhoːxˌlaːdn̩/', english: 'To upload', dari: 'آپلود کردن',
      category: 'IT & Technik', tag: 'Internet',
      example: 'Bitte laden Sie das Dokument hoch.',
      context: 'To send data from your device to the internet or a server.',
      contextDari: 'ارسال داده از دستگاه به اینترنت یا یک سرور.',
      difficulty: 'easy'),

  VocabWord(id: 'it12', german: 'die Schnittstelle', phonetic: '/ˈʃnɪtˌʃtɛlə/', english: 'Interface / API', dari: 'واسط / رابط / API',
      category: 'IT & Technik', tag: 'Development',
      example: 'Die beiden Systeme kommunizieren über eine Schnittstelle.',
      context: 'A point of connection between two systems.',
      contextDari: 'یک نقطه ارتباط بین دو سیستم.',
      difficulty: 'hard'),

  VocabWord(id: 'it13', german: 'das Netzwerk', phonetic: '/ˈnɛt͡svɛʁk/', english: 'Network', dari: 'شبکه',
      category: 'IT & Technik', tag: 'Infrastructure',
      example: 'Das interne Netzwerk ist ausgefallen.',
      context: 'A group of computers connected to share data.',
      contextDari: 'گروهی از کامپیوترهای متصل برای به اشتراک گذاری داده.',
      difficulty: 'easy'),

  VocabWord(id: 'it14', german: 'die Bandbreite', phonetic: '/ˈbanˌbʁaɪ̯tə/', english: 'Bandwidth', dari: 'پهنای باند / ظرفیت اینترنت',
      category: 'IT & Technik', tag: 'Internet',
      example: 'Wir brauchen mehr Bandbreite für das Video-Meeting.',
      context: 'The amount of data that can be transmitted in a given time.',
      contextDari: 'مقدار داده‌ای که در یک زمان معین می‌تواند منتقل شود.',
      difficulty: 'hard'),

  VocabWord(id: 'it15', german: 'das Betriebssystem', phonetic: '/bəˈtʁiːpsˌzʏsteːm/', english: 'Operating system (OS)', dari: 'سیستم عامل',
      category: 'IT & Technik', tag: 'Software',
      example: 'Windows ist das am meisten verwendete Betriebssystem.',
      context: 'The core software that manages a computer (Windows, Linux, macOS).',
      contextDari: 'نرم‌افزار اصلی که یک کامپیوتر را مدیریت می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'it16', german: 'der Arbeitsspeicher (RAM)', phonetic: '/ˈaʁbaɪ̯tsˌʃpaɪ̯çɐ/', english: 'RAM / Working memory', dari: 'رم / حافظه کاری',
      category: 'IT & Technik', tag: 'Hardware',
      example: 'Das Programm braucht viel Arbeitsspeicher.',
      context: 'Temporary memory used by the computer while running programs.',
      contextDari: 'حافظه موقت که کامپیوتر هنگام اجرای برنامه‌ها استفاده می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'it17', german: 'die Festplatte', phonetic: '/ˈfɛstˌplatə/', english: 'Hard drive', dari: 'هارد دیسک',
      category: 'IT & Technik', tag: 'Hardware',
      example: 'Die Festplatte ist voll.',
      context: 'Permanent storage inside a computer.',
      contextDari: 'ذخیره‌سازی دائمی داخل یک کامپیوتر.',
      difficulty: 'easy'),

  VocabWord(id: 'it18', german: 'verschlüsseln', phonetic: '/fɛɐ̯ˈʃlʏsln̩/', english: 'To encrypt', dari: 'رمزگذاری کردن / انکریپت کردن',
      category: 'IT & Technik', tag: 'Security',
      example: 'Alle Daten werden verschlüsselt übertragen.',
      context: 'To convert data into a coded form for security.',
      contextDari: 'تبدیل داده به یک فرم رمزگذاری شده برای امنیت.',
      difficulty: 'hard'),

  VocabWord(id: 'it19', german: 'der Support', phonetic: '/ˈzʊpɔʁt/', english: 'IT support / Help desk', dari: 'پشتیبانی / سپورت',
      category: 'IT & Technik', tag: 'Service',
      example: 'Bitte wenden Sie sich an den IT-Support.',
      context: 'A team that helps with technical problems.',
      contextDari: 'یک تیم که با مشکلات فنی کمک می‌کند.',
      difficulty: 'easy'),

  VocabWord(id: 'it20', german: 'der Helpdesk', phonetic: '/ˈhɛlpˌdɛsk/', english: 'Helpdesk / Service desk', dari: 'هلپ دسک / میز خدمات',
      category: 'IT & Technik', tag: 'Service',
      example: 'Der Helpdesk ist täglich von 8 bis 18 Uhr erreichbar.',
      context: 'A central point for users to get technical help.',
      contextDari: 'یک نقطه مرکزی برای کاربران که کمک فنی دریافت کنند.',
      difficulty: 'medium'),

  VocabWord(id: 'it21', german: 'die Lizenz', phonetic: '/liˈt͡sɛnt͡s/', english: 'Software licence', dari: 'لایسنس / مجوز نرم‌افزار',
      category: 'IT & Technik', tag: 'Software',
      example: 'Für dieses Programm benötigen Sie eine Lizenz.',
      context: 'A legal permission to use a piece of software.',
      contextDari: 'اجازه قانونی برای استفاده از یک نرم‌افزار.',
      difficulty: 'medium'),

  VocabWord(id: 'it22', german: 'die Datenbank', phonetic: '/ˈdaːtn̩baŋk/', english: 'Database', dari: 'پایگاه داده / دیتابیس',
      category: 'IT & Technik', tag: 'Development',
      example: 'Alle Kundendaten werden in der Datenbank gespeichert.',
      context: 'An organised collection of structured information.',
      contextDari: 'مجموعه‌ای سازماندهی شده از اطلاعات ساختاریافته.',
      difficulty: 'medium'),

  VocabWord(id: 'it23', german: 'der Server', phonetic: '/ˈzɛʁvɐ/', english: 'Server', dari: 'سرور',
      category: 'IT & Technik', tag: 'Infrastructure',
      example: 'Der Server ist überlastet.',
      context: 'A computer that provides data or services to other computers.',
      contextDari: 'کامپیوتری که داده یا خدمات را به کامپیوترهای دیگر ارائه می‌دهد.',
      difficulty: 'easy'),

  VocabWord(id: 'it24', german: 'die Fehlermeldung', phonetic: '/ˈfeːlɐˌmɛldʊŋ/', english: 'Error message', dari: 'پیام خطا / ارور',
      category: 'IT & Technik', tag: 'Software',
      example: 'Eine Fehlermeldung erscheint beim Starten des Programms.',
      context: 'A message shown when something goes wrong in a program.',
      contextDari: 'پیامی که هنگام بروز مشکل در یک برنامه نمایش داده می‌شود.',
      difficulty: 'medium'),

  // ═══════════════════════════════════════════════════════════════════════════
  // FINANZEN  (Finance & Accounting)  — 24 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'f01', german: 'die Rechnung', phonetic: '/ˈʁɛçnʊŋ/', english: 'Invoice / Bill', dari: 'فاکتور / صورتحساب',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Die Rechnung ist bis zum 30. fällig.',
      context: 'A document requesting payment for goods or services.',
      contextDari: 'سندی که درخواست پرداخت برای کالا یا خدمات می‌کند.',
      difficulty: 'easy'),

  VocabWord(id: 'f02', german: 'die Überweisung', phonetic: '/yːbɐˈvaɪ̯zʊŋ/', english: 'Bank transfer / Wire transfer', dari: 'انتقال بانکی / حواله',
      category: 'Finanzen', tag: 'Banking',
      example: 'Bitte veranlassen Sie die Überweisung heute.',
      context: 'Electronic transfer of money between bank accounts.',
      contextDari: 'انتقال الکترونیکی پول بین حساب‌های بانکی.',
      difficulty: 'medium'),

  VocabWord(id: 'f03', german: 'die Mehrwertsteuer (MwSt)', phonetic: '/ˈmeːɐ̯vɛʁtˌʃtɔɪ̯ɐ/', english: 'VAT / Sales tax', dari: 'مالیات بر ارزش افزوده / VAT',
      category: 'Finanzen', tag: 'Tax',
      example: 'Der Preis versteht sich inklusive 19% Mehrwertsteuer.',
      context: 'A tax added to most goods and services in Germany (19% or 7%).',
      contextDari: 'مالیاتی که به اکثر کالاها و خدمات در آلمان اضافه می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'f04', german: 'der Steuerberater', phonetic: '/ˈʃtɔɪ̯ɐbəˌʁaːtɐ/', english: 'Tax advisor / Accountant', dari: 'مشاور مالیاتی / حسابدار',
      category: 'Finanzen', tag: 'Tax',
      example: 'Ich gehe zum Steuerberater für die Steuererklärung.',
      context: 'A professional who gives advice on taxes.',
      contextDari: 'یک متخصص که مشاوره مالیاتی می‌دهد.',
      difficulty: 'medium'),

  VocabWord(id: 'f05', german: 'die Steuererklärung', phonetic: '/ˈʃtɔɪ̯ɐɛɐ̯ˌklɛːʁʊŋ/', english: 'Tax return', dari: 'اظهارنامه مالیاتی',
      category: 'Finanzen', tag: 'Tax',
      example: 'Ich muss bis zum 31. Juli meine Steuererklärung abgeben.',
      context: 'An annual form submitted to declare income and pay tax.',
      contextDari: 'یک فرم سالانه که برای اعلام درآمد و پرداخت مالیات ارسال می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'f06', german: 'das Konto', phonetic: '/ˈkɔnto/', english: 'Bank account', dari: 'حساب بانکی',
      category: 'Finanzen', tag: 'Banking',
      example: 'Ich möchte ein Girokonto eröffnen.',
      context: 'An account held at a bank.',
      contextDari: 'یک حساب نگهداری شده در یک بانک.',
      difficulty: 'easy'),

  VocabWord(id: 'f07', german: 'das Girokonto', phonetic: '/ˈɡiːʁoˌkɔnto/', english: 'Current account / Checking account', dari: 'حساب جاری',
      category: 'Finanzen', tag: 'Banking',
      example: 'Für Gehaltszahlungen brauchen Sie ein Girokonto.',
      context: 'An everyday bank account used for income and payments in Germany.',
      contextDari: 'یک حساب بانکی روزمره برای درآمد و پرداخت‌ها در آلمان.',
      difficulty: 'medium'),

  VocabWord(id: 'f08', german: 'die IBAN', phonetic: '/iːˈbaːn/', english: 'IBAN (bank account number)', dari: 'IBAN / شماره حساب بین‌المللی',
      category: 'Finanzen', tag: 'Banking',
      example: 'Bitte teilen Sie mir Ihre IBAN mit.',
      context: 'International Bank Account Number, used for transfers in Europe.',
      contextDari: 'شماره حساب بانکی بین‌المللی، برای انتقال در اروپا استفاده می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'f09', german: 'die Ausgaben', phonetic: '/ˈaʊ̯sˌɡaːbən/', english: 'Expenses / Expenditures', dari: 'مخارج / هزینه‌ها',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Die Ausgaben diesen Monat sind sehr hoch.',
      context: 'Money spent on goods and services.',
      contextDari: 'پولی که برای کالاها و خدمات خرج می‌شود.',
      difficulty: 'easy'),

  VocabWord(id: 'f10', german: 'die Einnahmen', phonetic: '/ˈaɪ̯nˌnaːmən/', english: 'Income / Revenue', dari: 'درآمد / عواید',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Die Einnahmen des Unternehmens sind gestiegen.',
      context: 'Money received from business activities.',
      contextDari: 'پول دریافت شده از فعالیت‌های تجاری.',
      difficulty: 'easy'),

  VocabWord(id: 'f11', german: 'der Gewinn', phonetic: '/ɡəˈvɪn/', english: 'Profit', dari: 'سود / فایده',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Der Gewinn ist im dritten Quartal gestiegen.',
      context: 'Money earned after all costs are deducted.',
      contextDari: 'پول کسب شده پس از کسر تمام هزینه‌ها.',
      difficulty: 'easy'),

  VocabWord(id: 'f12', german: 'der Verlust', phonetic: '/fɛɐ̯ˈlʊst/', english: 'Loss', dari: 'ضرر / خسارت',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Das Unternehmen hat einen Verlust gemacht.',
      context: 'When costs are more than income.',
      contextDari: 'وقتی هزینه‌ها بیشتر از درآمد باشد.',
      difficulty: 'easy'),

  VocabWord(id: 'f13', german: 'das Budget', phonetic: '/byˈdʒeː/', english: 'Budget', dari: 'بودجه',
      category: 'Finanzen', tag: 'Planning',
      example: 'Wir haben das Budget für dieses Projekt überschritten.',
      context: 'An estimate of income and spending over a period.',
      contextDari: 'برآوردی از درآمد و هزینه‌ها در یک دوره.',
      difficulty: 'easy'),

  VocabWord(id: 'f14', german: 'die Buchhaltung', phonetic: '/ˈbuːxhaltʊŋ/', english: 'Accounting / Bookkeeping', dari: 'حسابداری',
      category: 'Finanzen', tag: 'Department',
      example: 'Die Buchhaltung prüft alle Ausgaben.',
      context: 'The department that manages financial records.',
      contextDari: 'بخشی که سوابق مالی را مدیریت می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'f15', german: 'der Kredit', phonetic: '/kʁeˈdiːt/', english: 'Loan / Credit', dari: 'قرضه / وام / کریدیت',
      category: 'Finanzen', tag: 'Banking',
      example: 'Ich habe einen Kredit bei der Bank beantragt.',
      context: 'Money borrowed that must be repaid with interest.',
      contextDari: 'پولی که قرض گرفته می‌شود و باید با بهره بازپرداخت شود.',
      difficulty: 'medium'),

  VocabWord(id: 'f16', german: 'der Zinssatz', phonetic: '/ˈt͡sɪnszat͡s/', english: 'Interest rate', dari: 'نرخ بهره / فیصدی سود',
      category: 'Finanzen', tag: 'Banking',
      example: 'Der aktuelle Zinssatz beträgt 3,5%.',
      context: 'The percentage charged on a loan or paid on savings.',
      contextDari: 'درصد شارژ شده روی وام یا پرداخت شده روی پس‌انداز.',
      difficulty: 'hard'),

  VocabWord(id: 'f17', german: 'die Quittung', phonetic: '/ˈkvɪtʊŋ/', english: 'Receipt', dari: 'رسید / قبض',
      category: 'Finanzen', tag: 'Document',
      example: 'Kann ich bitte eine Quittung haben?',
      context: 'A written acknowledgement that money has been paid.',
      contextDari: 'یک تأیید مکتوب که پول پرداخت شده.',
      difficulty: 'easy'),

  VocabWord(id: 'f18', german: 'der Kassenbon', phonetic: '/ˈkasnˌboːn/', english: 'Till receipt / Cash receipt', dari: 'رسید صندوق / فاکتور فروشگاه',
      category: 'Finanzen', tag: 'Document',
      example: 'Bewahren Sie den Kassenbon für die Buchhaltung auf.',
      context: 'The printed receipt you get from a shop.',
      contextDari: 'رسید چاپ شده که از یک دکان می‌گیرید.',
      difficulty: 'medium'),

  VocabWord(id: 'f19', german: 'die Abrechnung', phonetic: '/ˈapˌʁɛçnʊŋ/', english: 'Settlement / Statement of accounts', dari: 'تسویه حساب / صورتحساب',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Die monatliche Abrechnung kommt per E-Mail.',
      context: 'A detailed statement of financial transactions.',
      contextDari: 'یک صورت مفصل از تراکنش‌های مالی.',
      difficulty: 'medium'),

  VocabWord(id: 'f20', german: 'die Mahnung', phonetic: '/ˈmaːnʊŋ/', english: 'Payment reminder / Dunning notice', dari: 'یادآوری پرداخت / اخطار',
      category: 'Finanzen', tag: 'Document',
      example: 'Ich habe eine Mahnung wegen einer unbezahlten Rechnung erhalten.',
      context: 'A formal reminder to pay an overdue invoice.',
      contextDari: 'یک یادآوری رسمی برای پرداخت یک فاکتور معوق.',
      difficulty: 'hard'),

  VocabWord(id: 'f21', german: 'der Umsatz', phonetic: '/ˈʊmzat͡s/', english: 'Turnover / Sales revenue', dari: 'گردش مالی / فروش',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Der Umsatz ist im Vergleich zum Vorjahr gestiegen.',
      context: 'The total income from sales before costs are deducted.',
      contextDari: 'مجموع درآمد از فروش قبل از کسر هزینه‌ها.',
      difficulty: 'medium'),

  VocabWord(id: 'f22', german: 'die Liquidität', phonetic: '/likviditɛːt/', english: 'Liquidity / Cash flow', dari: 'نقدینگی',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Das Unternehmen hat Probleme mit der Liquidität.',
      context: 'The ability to meet short-term financial obligations.',
      contextDari: 'توانایی پرداخت تعهدات مالی کوتاه‌مدت.',
      difficulty: 'hard'),

  VocabWord(id: 'f23', german: 'der Jahresabschluss', phonetic: '/ˈjaːʁəsˌʔapʃlʊs/', english: 'Annual financial statement', dari: 'صورت مالی سالانه / ختم سال مالی',
      category: 'Finanzen', tag: 'Accounting',
      example: 'Der Jahresabschluss muss bis März fertig sein.',
      context: 'A formal financial report summarising the year\'s activity.',
      contextDari: 'یک گزارش مالی رسمی که فعالیت‌های سال را خلاصه می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'f24', german: 'die Spesenabrechnnung', phonetic: '/ˈʃpeːzənˌʔapʁɛçnʊŋ/', english: 'Expense report', dari: 'گزارش مخارج / فرم هزینه‌ها',
      category: 'Finanzen', tag: 'Document',
      example: 'Bitte reichen Sie die Spesenabrechnung bis Freitag ein.',
      context: 'A form submitted to claim reimbursement for work expenses.',
      contextDari: 'یک فرم که برای درخواست بازپرداخت هزینه‌های کاری ارسال می‌شود.',
      difficulty: 'hard'),

  // ═══════════════════════════════════════════════════════════════════════════
  // VERTRÄGE & RECHT  (Contracts & Legal)  — 22 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'v01', german: 'der Vertrag', phonetic: '/fɛɐ̯ˈtʁaːk/', english: 'Contract / Agreement', dari: 'قرارداد / موافقتنامه',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Bitte lesen Sie den Vertrag sorgfältig durch.',
      context: 'A legally binding agreement between two or more parties.',
      contextDari: 'یک توافق قانونی الزام‌آور بین دو یا چند طرف.',
      difficulty: 'easy'),

  VocabWord(id: 'v02', german: 'die Klausel', phonetic: '/ˈklaʊ̯zl̩/', english: 'Clause / Term', dari: 'ماده / بند / شرط',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Diese Klausel schützt beide Parteien.',
      context: 'A specific condition or provision within a contract.',
      contextDari: 'یک شرط یا مقرره خاص در یک قرارداد.',
      difficulty: 'hard'),

  VocabWord(id: 'v03', german: 'die Haftung', phonetic: '/ˈhaftʊŋ/', english: 'Liability', dari: 'مسئولیت قانونی',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Die Haftung ist auf 10.000 Euro begrenzt.',
      context: 'Legal responsibility for something that goes wrong.',
      contextDari: 'مسئولیت قانونی برای چیزی که اشتباه می‌رود.',
      difficulty: 'hard'),

  VocabWord(id: 'v04', german: 'die Kündigung', phonetic: '/ˈkʏndɪɡʊŋ/', english: 'Termination / Notice of cancellation', dari: 'فسخ / اخطار لغو',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Die Kündigung des Mietvertrags muss drei Monate vorher erfolgen.',
      context: 'The formal notice to end a contract or employment.',
      contextDari: 'اطلاعیه رسمی برای پایان دادن به یک قرارداد یا استخدام.',
      difficulty: 'medium'),

  VocabWord(id: 'v05', german: 'die Kündigungsfrist', phonetic: '/ˈkʏndɪɡʊŋsfʁɪst/', english: 'Notice period', dari: 'مهلت اخطار / دوره اطلاع قبلی',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Die Kündigungsfrist beträgt vier Wochen.',
      context: 'The period of time required before ending a contract.',
      contextDari: 'دوره زمانی که قبل از پایان دادن به یک قرارداد لازم است.',
      difficulty: 'hard'),

  VocabWord(id: 'v06', german: 'die Geheimhaltungsvereinbarung (NDA)', phonetic: '/ɡəˈhaɪ̯mhaltʊŋsfɛɐ̯ˌʔaɪ̯nbɑːʁʊŋ/', english: 'Non-disclosure agreement (NDA)', dari: 'توافقنامه محرمانگی / NDA',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Alle Mitarbeiter unterschreiben eine Geheimhaltungsvereinbarung.',
      context: 'A legal agreement to keep information confidential.',
      contextDari: 'یک توافق قانونی برای نگه داشتن اطلاعات محرمانه.',
      difficulty: 'hard'),

  VocabWord(id: 'v07', german: 'das Urheberrecht', phonetic: '/ˈʔuːɐ̯heːbɐˌʁɛçt/', english: 'Copyright', dari: 'حق چاپ / کپی‌رایت',
      category: 'Verträge & Recht', tag: 'Intellectual Property',
      example: 'Diese Fotos sind durch das Urheberrecht geschützt.',
      context: 'The legal right to be the only one to publish or reproduce a work.',
      contextDari: 'حق قانونی برای انتشار یا تولید مجدد یک اثر.',
      difficulty: 'hard'),

  VocabWord(id: 'v08', german: 'die Datenschutzerklärung', phonetic: '/ˈdaːtn̩ʃʊt͡sɛɐ̯ˌklɛːʁʊŋ/', english: 'Privacy policy / GDPR statement', dari: 'بیانیه حریم خصوصی / دیتنشوتز',
      category: 'Verträge & Recht', tag: 'GDPR',
      example: 'Bitte lesen Sie unsere Datenschutzerklärung.',
      context: 'A statement explaining how personal data is collected and used (GDPR).',
      contextDari: 'بیانیه‌ای که توضیح می‌دهد چگونه داده‌های شخصی جمع‌آوری و استفاده می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'v09', german: 'gültig', phonetic: '/ˈɡʏltɪç/', english: 'Valid / In force', dari: 'معتبر / دارای اعتبار',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Dieser Ausweis ist bis 2027 gültig.',
      context: 'Legally accepted or in effect.',
      contextDari: 'از نظر قانونی پذیرفته شده یا در اجرا.',
      difficulty: 'easy'),

  VocabWord(id: 'v10', german: 'ungültig', phonetic: '/ˈʊnˌɡʏltɪç/', english: 'Invalid / Void', dari: 'غیرمعتبر / باطل',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Der Vertrag ist ungültig, weil eine Unterschrift fehlt.',
      context: 'Not legally binding or accepted.',
      contextDari: 'از نظر قانونی الزام‌آور یا پذیرفته نشده.',
      difficulty: 'medium'),

  VocabWord(id: 'v11', german: 'die Einwilligung', phonetic: '/ˈaɪ̯nˌvɪlɪɡʊŋ/', english: 'Consent / Approval', dari: 'رضایت / موافقت',
      category: 'Verträge & Recht', tag: 'GDPR',
      example: 'Ihre Einwilligung zur Datenspeicherung ist erforderlich.',
      context: 'Permission given freely, especially for data processing under GDPR.',
      contextDari: 'اجازه‌ای که آزادانه داده می‌شود، به خصوص برای پردازش داده تحت GDPR.',
      difficulty: 'hard'),

  VocabWord(id: 'v12', german: 'der Schadensersatz', phonetic: '/ˈʃaːdn̩sɛɐ̯ˌzat͡s/', english: 'Damages / Compensation', dari: 'خسارت / جبران خسارت',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Er verlangt Schadensersatz wegen Vertragsverletzung.',
      context: 'Money claimed or awarded in compensation for a loss.',
      contextDari: 'پولی که به عنوان جبران خسارت ادعا یا اعطا می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'v13', german: 'die Gewährleistung', phonetic: '/ɡəˈvɛːɐ̯laɪ̯stʊŋ/', english: 'Warranty / Guarantee', dari: 'ضمانت / گارانتی',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Das Produkt hat zwei Jahre Gewährleistung.',
      context: 'A legal promise that a product will work as described.',
      contextDari: 'یک وعده قانونی که یک محصول طبق توضیحات کار می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'v14', german: 'die Laufzeit', phonetic: '/ˈlaʊ̯ft͡saɪ̯t/', english: 'Duration / Term (of contract)', dari: 'مدت / دوره قرارداد',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Die Laufzeit des Vertrags beträgt zwei Jahre.',
      context: 'The period of time a contract is in effect.',
      contextDari: 'دوره زمانی که یک قرارداد در اجرا است.',
      difficulty: 'medium'),

  VocabWord(id: 'v15', german: 'verlängern', phonetic: '/fɛɐ̯ˈlɛŋɐn/', english: 'To renew / To extend (a contract)', dari: 'تمدید کردن',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Möchten Sie den Vertrag verlängern?',
      context: 'To extend the period of a contract.',
      contextDari: 'تمدید دوره یک قرارداد.',
      difficulty: 'medium'),

  VocabWord(id: 'v16', german: 'der Ansprechpartner', phonetic: '/ˈanˌʃpʁɛçpaʁtnɐ/', english: 'Contact person / Point of contact', dari: 'شخص تماس / مسئول رابط',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Wer ist der Ansprechpartner für diesen Vertrag?',
      context: 'The designated person to contact regarding a matter.',
      contextDari: 'شخص تعیین شده برای تماس در مورد یک موضوع.',
      difficulty: 'medium'),

  VocabWord(id: 'v17', german: 'die Vertragsstrafe', phonetic: '/fɛɐ̯ˈtʁaːksˌʃtʁaːfə/', english: 'Contractual penalty', dari: 'جریمه قراردادی',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Bei Verspätung ist eine Vertragsstrafe fällig.',
      context: 'A fine payable if contract terms are breached.',
      contextDari: 'جریمه‌ای که در صورت نقض شرایط قرارداد پرداخت می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'v18', german: 'beidseitig', phonetic: '/ˈbaɪ̯tzaɪ̯tɪç/', english: 'Mutual / Bilateral', dari: 'دوطرفه / متقابل',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Der Vertrag ist beidseitig kündbar.',
      context: 'Involving or agreed by both parties.',
      contextDari: 'شامل یا توافق شده توسط هر دو طرف.',
      difficulty: 'hard'),

  VocabWord(id: 'v19', german: 'die Vollmacht', phonetic: '/ˈfɔlmaxt/', english: 'Power of attorney', dari: 'وکالتنامه',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Mit dieser Vollmacht kann er in meinem Namen handeln.',
      context: 'Legal authorisation to act on behalf of another person.',
      contextDari: 'اجازه قانونی برای عمل به نمایندگی از شخص دیگر.',
      difficulty: 'hard'),

  VocabWord(id: 'v20', german: 'der Auftraggeber', phonetic: '/ˈaʊ̯ftʁaːkˌɡeːbɐ/', english: 'Client / Principal / Commissioning party', dari: 'کارفرما / صاحب پروژه',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Der Auftraggeber verlangt wöchentliche Berichte.',
      context: 'The party who commissions work from a contractor.',
      contextDari: 'طرفی که از یک پیمانکار کار سفارش می‌دهد.',
      difficulty: 'hard'),

  VocabWord(id: 'v21', german: 'der Auftragnehmer', phonetic: '/ˈaʊ̯ftʁaːkˌneːmɐ/', english: 'Contractor / Service provider', dari: 'پیمانکار / ارائه‌دهنده خدمات',
      category: 'Verträge & Recht', tag: 'Contract',
      example: 'Der Auftragnehmer liefert bis Montag.',
      context: 'The party who carries out the commissioned work.',
      contextDari: 'طرفی که کار سفارش داده شده را انجام می‌دهد.',
      difficulty: 'hard'),

  VocabWord(id: 'v22', german: 'rechtskräftig', phonetic: '/ˈʁɛçtsˌkʁɛftɪç/', english: 'Legally binding / Final', dari: 'قانوناً معتبر / لازم‌الاجرا',
      category: 'Verträge & Recht', tag: 'Legal',
      example: 'Das Urteil ist ab sofort rechtskräftig.',
      context: 'Having full legal force and effect.',
      contextDari: 'دارای قوه و اثر کامل قانونی.',
      difficulty: 'hard'),

  // ═══════════════════════════════════════════════════════════════════════════
  // MARKETING & VERTRIEB  (Marketing & Sales)  — 22 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'mk01', german: 'die Zielgruppe', phonetic: '/ˈt͡siːlˌɡʁʊpə/', english: 'Target audience / Target group', dari: 'گروه هدف / مخاطبان هدف',
      category: 'Marketing & Vertrieb', tag: 'Strategy',
      example: 'Unsere Zielgruppe sind Berufseinsteiger.',
      context: 'The specific group of people a campaign aims to reach.',
      contextDari: 'گروه خاصی از مردم که یک کمپین به دنبال رسیدن به آنهاست.',
      difficulty: 'medium'),

  VocabWord(id: 'mk02', german: 'die Marke', phonetic: '/ˈmaʁkə/', english: 'Brand', dari: 'برند / نشان تجارتی',
      category: 'Marketing & Vertrieb', tag: 'Branding',
      example: 'Diese Marke ist weltweit bekannt.',
      context: 'A name, symbol or design identifying a product or company.',
      contextDari: 'یک نام، نماد یا طراحی که یک محصول یا شرکت را شناسایی می‌کند.',
      difficulty: 'easy'),

  VocabWord(id: 'mk03', german: 'der Wettbewerber', phonetic: '/ˈvɛtbəˌvɛʁbɐ/', english: 'Competitor', dari: 'رقیب',
      category: 'Marketing & Vertrieb', tag: 'Market',
      example: 'Wir beobachten die Aktivitäten unserer Wettbewerber.',
      context: 'A company or person competing in the same market.',
      contextDari: 'یک شرکت یا شخص که در همان بازار رقابت می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'mk04', german: 'das Angebot', phonetic: '/ˈanɡəboːt/', english: 'Offer / Quote / Proposal', dari: 'پیشنهاد / آفر / کوتیشن',
      category: 'Marketing & Vertrieb', tag: 'Sales',
      example: 'Ich schicke Ihnen ein Angebot bis Mittwoch.',
      context: 'A formal business proposal stating price and terms.',
      contextDari: 'یک پیشنهاد رسمی تجاری که قیمت و شرایط را بیان می‌کند.',
      difficulty: 'easy'),

  VocabWord(id: 'mk05', german: 'der Kunde / die Kundin', phonetic: '/ˈkʊndə/', english: 'Customer / Client', dari: 'مشتری',
      category: 'Marketing & Vertrieb', tag: 'Sales',
      example: 'Der Kunde ist zufrieden mit unserem Service.',
      context: 'A person who buys goods or services.',
      contextDari: 'شخصی که کالا یا خدمات می‌خرد.',
      difficulty: 'easy'),

  VocabWord(id: 'mk06', german: 'die Kundenzufriedenheit', phonetic: '/ˈkʊndən​t͡suːˌfʁiːdn̩haɪ̯t/', english: 'Customer satisfaction', dari: 'رضایت مشتری',
      category: 'Marketing & Vertrieb', tag: 'CRM',
      example: 'Die Kundenzufriedenheit steht bei uns an erster Stelle.',
      context: 'How happy customers are with a product or service.',
      contextDari: 'چقدر مشتریان از یک محصول یا خدمات خوشحال هستند.',
      difficulty: 'hard'),

  VocabWord(id: 'mk07', german: 'die Nachfrage', phonetic: '/ˈnaːxˌfʁaːɡə/', english: 'Demand', dari: 'تقاضا',
      category: 'Marketing & Vertrieb', tag: 'Market',
      example: 'Die Nachfrage nach diesem Produkt ist gestiegen.',
      context: 'The amount of a product customers want to buy.',
      contextDari: 'مقدار یک محصول که مشتریان می‌خواهند بخرند.',
      difficulty: 'medium'),

  VocabWord(id: 'mk08', german: 'das Alleinstellungsmerkmal (USP)', phonetic: '/ˈʔalaɪ̯nˌʃtɛlʊŋsmɛʁkmaːl/', english: 'Unique selling point (USP)', dari: 'مزیت رقابتی / USP',
      category: 'Marketing & Vertrieb', tag: 'Strategy',
      example: 'Was ist das Alleinstellungsmerkmal Ihres Produkts?',
      context: 'The feature that makes your product unique compared to competitors.',
      contextDari: 'ویژگی که محصول شما را در مقایسه با رقبا منحصربه‌فرد می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'mk09', german: 'der Absatz', phonetic: '/ˈapt͡sat͡s/', english: 'Sales (units sold)', dari: 'فروش / میزان فروش',
      category: 'Marketing & Vertrieb', tag: 'Sales',
      example: 'Der Absatz ist im letzten Quartal gestiegen.',
      context: 'The number of units of a product sold.',
      contextDari: 'تعداد واحدهای یک محصول فروخته شده.',
      difficulty: 'medium'),

  VocabWord(id: 'mk10', german: 'der Marktanteil', phonetic: '/ˈmaʁktˌʔantaɪ̯l/', english: 'Market share', dari: 'سهم بازار',
      category: 'Marketing & Vertrieb', tag: 'Strategy',
      example: 'Unser Marktanteil beträgt 25%.',
      context: 'The percentage of total market sales a company holds.',
      contextDari: 'درصد از مجموع فروش بازار که یک شرکت دارد.',
      difficulty: 'hard'),

  VocabWord(id: 'mk11', german: 'der Rabatt', phonetic: '/ʁaˈbat/', english: 'Discount', dari: 'تخفیف',
      category: 'Marketing & Vertrieb', tag: 'Pricing',
      example: 'Für Großbestellungen gewähren wir 10% Rabatt.',
      context: 'A reduction in the usual price of something.',
      contextDari: 'کاهش در قیمت معمول چیزی.',
      difficulty: 'easy'),

  VocabWord(id: 'mk12', german: 'der Auftragseingang', phonetic: '/ˈaʊ̯ftʁaːksˌʔaɪ̯nɡaŋ/', english: 'Incoming orders / Order intake', dari: 'سفارشات ورودی',
      category: 'Marketing & Vertrieb', tag: 'Sales',
      example: 'Der Auftragseingang ist diese Woche sehr gut.',
      context: 'New orders received by a company.',
      contextDari: 'سفارشات جدیدی که یک شرکت دریافت می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'mk13', german: 'die Werbung', phonetic: '/ˈvɛʁbʊŋ/', english: 'Advertising / Advertisement', dari: 'تبلیغات / آگهی',
      category: 'Marketing & Vertrieb', tag: 'Campaign',
      example: 'Die Werbung läuft auf allen Social-Media-Kanälen.',
      context: 'Paid promotion of a product or service.',
      contextDari: 'تبلیغ پولی یک محصول یا خدمات.',
      difficulty: 'easy'),

  VocabWord(id: 'mk14', german: 'die Kampagne', phonetic: '/kamˈpanjə/', english: 'Campaign', dari: 'کمپین / مبارزه تبلیغاتی',
      category: 'Marketing & Vertrieb', tag: 'Campaign',
      example: 'Wir planen eine neue Marketingkampagne für den Herbst.',
      context: 'A series of planned actions to promote a product.',
      contextDari: 'مجموعه‌ای از اقدامات برنامه‌ریزی شده برای ترویج یک محصول.',
      difficulty: 'medium'),

  VocabWord(id: 'mk15', german: 'der Preis', phonetic: '/pʁaɪ̯s/', english: 'Price', dari: 'قیمت',
      category: 'Marketing & Vertrieb', tag: 'Pricing',
      example: 'Wie hoch ist der Preis für dieses Modell?',
      context: 'The amount of money for which something is sold.',
      contextDari: 'مقدار پولی که یک چیز به آن قیمت فروخته می‌شود.',
      difficulty: 'easy'),

  VocabWord(id: 'mk16', german: 'verhandeln', phonetic: '/fɛɐ̯ˈhandl̩n/', english: 'To negotiate', dari: 'مذاکره کردن / چانه زدن',
      category: 'Marketing & Vertrieb', tag: 'Sales',
      example: 'Wir verhandeln gerade über den Preis.',
      context: 'To discuss terms in order to reach an agreement.',
      contextDari: 'بحث در مورد شرایط به منظور رسیدن به توافق.',
      difficulty: 'medium'),

  VocabWord(id: 'mk17', german: 'der Vertrieb', phonetic: '/fɛɐ̯ˈtʁiːp/', english: 'Sales / Distribution', dari: 'فروش / توزیع',
      category: 'Marketing & Vertrieb', tag: 'Department',
      example: 'Ich arbeite im Vertrieb.',
      context: 'The department or process of selling and distributing products.',
      contextDari: 'بخش یا فرآیند فروش و توزیع محصولات.',
      difficulty: 'medium'),

  VocabWord(id: 'mk18', german: 'der Lead', phonetic: '/liːd/', english: 'Lead / Potential customer', dari: 'لید / مشتری بالقوه',
      category: 'Marketing & Vertrieb', tag: 'CRM',
      example: 'Wir haben 50 neue Leads diese Woche generiert.',
      context: 'A potential customer who has shown interest.',
      contextDari: 'یک مشتری بالقوه که علاقه نشان داده است.',
      difficulty: 'medium'),

  VocabWord(id: 'mk19', german: 'die Conversion', phonetic: '/kənˈvɜːʃn̩/', english: 'Conversion (visitor to customer)', dari: 'تبدیل (بازدیدکننده به مشتری)',
      category: 'Marketing & Vertrieb', tag: 'Digital',
      example: 'Die Conversion-Rate liegt bei 3%.',
      context: 'The rate at which potential customers become actual buyers.',
      contextDari: 'نرخی که مشتریان بالقوه به خریداران واقعی تبدیل می‌شوند.',
      difficulty: 'hard'),

  VocabWord(id: 'mk20', german: 'der Kundenstamm', phonetic: '/ˈkʊndənˌʃtam/', english: 'Customer base / Client portfolio', dari: 'پایگاه مشتریان',
      category: 'Marketing & Vertrieb', tag: 'CRM',
      example: 'Unser Kundenstamm wächst stetig.',
      context: 'The total group of existing customers a business has.',
      contextDari: 'گروه کل مشتریان موجود که یک کسب‌وکار دارد.',
      difficulty: 'medium'),

  VocabWord(id: 'mk21', german: 'der Umsatzplan', phonetic: '/ˈʊmzat͡sˌplaːn/', english: 'Sales plan / Revenue target', dari: 'طرح فروش / هدف درآمدی',
      category: 'Marketing & Vertrieb', tag: 'Planning',
      example: 'Haben Sie den Umsatzplan für das nächste Quartal?',
      context: 'A planned target for sales revenue.',
      contextDari: 'یک هدف برنامه‌ریزی شده برای درآمد فروش.',
      difficulty: 'hard'),

  VocabWord(id: 'mk22', german: 'die Produkteinführung', phonetic: '/pʁoˈdʊktˌʔaɪ̯nfyːʁʊŋ/', english: 'Product launch', dari: 'راه‌اندازی محصول / لانچ محصول',
      category: 'Marketing & Vertrieb', tag: 'Campaign',
      example: 'Die Produkteinführung ist für März geplant.',
      context: 'The formal introduction of a new product to the market.',
      contextDari: 'معرفی رسمی یک محصول جدید به بازار.',
      difficulty: 'hard'),

];
