// ─── vocabulary_data_session3.dart ──────────────────────────────────────────
// Session 3 — 100 words across 4 new life-in-Germany categories
//
// HOW TO USE:
//   Append   ...vocabularyDataSession3   to the vocabularyData list
//   in vocabulary_data.dart.
//
// Categories added:
//   Bildung & Schule          — 25 words  (school, university, exams, degrees)
//   Visum & Behörden          — 26 words  (visa, residence permit, authorities)
//   Ausbildung & Praktikum    — 25 words  (vocational training, apprenticeship)
//   Jobsuche & Bewerbung      — 24 words  (job hunting, portals, interviews)
// ─────────────────────────────────────────────────────────────────────────────

import 'vocabulary_data.dart';

final vocabularyDataSession3 = <VocabWord>[

  // ═══════════════════════════════════════════════════════════════════════════
  // BILDUNG & SCHULE  (Education & School)  — 25 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'bs01', german: 'die Grundschule', phonetic: '/ˈɡʁʊntˌʃuːlə/', english: 'Primary school (grades 1–4)', dari: 'مکتب ابتدایی',
      category: 'Bildung & Schule', tag: 'School',
      example: 'Mein Kind geht in die Grundschule.',
      context: 'The first stage of school in Germany, for ages 6–10.',
      contextDari: 'اولین مرحله مکتب در آلمان، برای سنین ۶ تا ۱۰ سال.',
      difficulty: 'easy'),

  VocabWord(id: 'bs02', german: 'das Gymnasium', phonetic: '/ɡymˈnaːzi̯ʊm/', english: 'Grammar school / Academic high school', dari: 'مکتب عالی / ژیمناسیوم',
      category: 'Bildung & Schule', tag: 'School',
      example: 'Sie besucht das Gymnasium und möchte studieren.',
      context: 'The most academic secondary school track leading to the Abitur.',
      contextDari: 'مسیر تحصیلی دبیرستانی که به آبیتور منتهی می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'bs03', german: 'das Abitur', phonetic: '/abiˈtuːɐ̯/', english: 'A-levels / University entrance qualification', dari: 'دیپلم دبیرستان / ابیتور',
      category: 'Bildung & Schule', tag: 'Qualification',
      example: 'Mit dem Abitur kann man an der Universität studieren.',
      context: 'The final school exam in Germany that qualifies for university entry.',
      contextDari: 'امتحان نهایی مکتب در آلمان که برای ورود به دانشگاه واجد شرایط می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'bs04', german: 'die Universität', phonetic: '/univɛʁziˈtɛːt/', english: 'University', dari: 'دانشگاه / پوهنتون',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Ich studiere an der Universität München.',
      context: 'An institution of higher education offering bachelor\'s and master\'s degrees.',
      contextDari: 'یک نهاد آموزش عالی که مدارک لیسانس و ماستری ارائه می‌دهد.',
      difficulty: 'easy'),

  VocabWord(id: 'bs05', german: 'die Fachhochschule (FH)', phonetic: '/ˈfaxˌhoːxˌʃuːlə/', english: 'University of applied sciences', dari: 'دانشگاه علوم کاربردی',
      category: 'Bildung & Schule', tag: 'University',
      example: 'An der FH gibt es viele praxisorientierte Studiengänge.',
      context: 'A practical, career-focused type of university in Germany (Fachhochschule).',
      contextDari: 'یک نوع دانشگاه عملی و شغل‌محور در آلمان.',
      difficulty: 'medium'),

  VocabWord(id: 'bs06', german: 'der Studiengang', phonetic: '/ˈʃtuːdi̯ənˌɡaŋ/', english: 'Degree programme / Course of study', dari: 'رشته تحصیلی / برنامه درسی',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Welchen Studiengang haben Sie gewählt?',
      context: 'The specific academic programme a student is enrolled in.',
      contextDari: 'برنامه اکادمیک خاصی که یک دانشجو در آن ثبت‌نام کرده.',
      difficulty: 'medium'),

  VocabWord(id: 'bs07', german: 'das Semester', phonetic: '/zeˈmɛstɐ/', english: 'Semester / Term', dari: 'سمستر / نیم‌سال تحصیلی',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Das Wintersemester beginnt im Oktober.',
      context: 'A half-year academic period. Germany has Wintersemester and Sommersemester.',
      contextDari: 'یک دوره اکادمیک نیم‌سال. آلمان دارای سمستر زمستانی و تابستانی است.',
      difficulty: 'easy'),

  VocabWord(id: 'bs08', german: 'die Vorlesung', phonetic: '/ˈfoːɐ̯ˌleːzʊŋ/', english: 'Lecture', dari: 'لکچر / درس دانشگاهی',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Die Vorlesung beginnt um 9 Uhr im Hörsaal.',
      context: 'A formal university lecture, usually in a large hall (Hörsaal).',
      contextDari: 'یک لکچر رسمی دانشگاهی، معمولاً در یک سالن بزرگ.',
      difficulty: 'medium'),

  VocabWord(id: 'bs09', german: 'das Seminar', phonetic: '/zemiˈnaːɐ̯/', english: 'Seminar (small-group class)', dari: 'سمینار / کلاس گروه کوچک',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Im Seminar diskutieren wir die Texte.',
      context: 'A small-group class involving discussion and student participation.',
      contextDari: 'یک کلاس گروه کوچک که شامل بحث و مشارکت دانشجویان است.',
      difficulty: 'medium'),

  VocabWord(id: 'bs10', german: 'die Prüfung', phonetic: '/ˈpʁyːfʊŋ/', english: 'Exam / Test', dari: 'امتحان',
      category: 'Bildung & Schule', tag: 'Exams',
      example: 'Die Prüfung ist nächste Woche.',
      context: 'A formal test of knowledge or skills.',
      contextDari: 'یک آزمون رسمی دانش یا مهارت‌ها.',
      difficulty: 'easy'),

  VocabWord(id: 'bs11', german: 'die Hausarbeit', phonetic: '/ˈhaʊ̯sˌaʁbaɪ̯t/', english: 'Academic essay / Term paper', dari: 'مقاله اکادمیک / کار نوشتاری',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Ich muss bis Freitag die Hausarbeit abgeben.',
      context: 'A written academic assignment submitted as part of a course.',
      contextDari: 'یک تکلیف اکادمیک مکتوب که به عنوان بخشی از یک درس ارائه می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'bs12', german: 'das Stipendium', phonetic: '/ʃtiˈpɛndi̯ʊm/', english: 'Scholarship / Grant', dari: 'بورسیه تحصیلی',
      category: 'Bildung & Schule', tag: 'Funding',
      example: 'Sie hat ein Stipendium vom DAAD bekommen.',
      context: 'Financial support for studying, often from organisations like DAAD or foundations.',
      contextDari: 'حمایت مالی برای تحصیل، اغلب از سازمان‌هایی مانند DAAD.',
      difficulty: 'medium'),

  VocabWord(id: 'bs13', german: 'der BAföG', phonetic: '/ˈbeːfœk/', english: 'Student financial aid (German state loan)', dari: 'کمک مالی دولتی برای دانشجویان',
      category: 'Bildung & Schule', tag: 'Funding',
      example: 'Ich habe BAföG beantragt, um das Studium zu finanzieren.',
      context: 'German state financial aid for students (Bundesausbildungsförderungsgesetz), partly a loan.',
      contextDari: 'کمک مالی دولتی آلمانی برای دانشجویان، بخشی از آن وام است.',
      difficulty: 'hard'),

  VocabWord(id: 'bs14', german: 'die Anmeldung (Universität)', phonetic: '/ˈanˌmɛldʊŋ/', english: 'Enrolment / Registration (university)', dari: 'ثبت‌نام دانشگاه',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Die Anmeldung zum Studium läuft online.',
      context: 'The process of officially registering for a university programme.',
      contextDari: 'فرآیند ثبت‌نام رسمی برای یک برنامه دانشگاهی.',
      difficulty: 'easy'),

  VocabWord(id: 'bs15', german: 'der Numerus clausus (NC)', phonetic: '/ˈnuːmeʁʊs ˈklaʊ̯zʊs/', english: 'Grade threshold for university entry', dari: 'حد نصاب نمره برای ورود به دانشگاه',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Für Medizin gibt es einen strengen NC.',
      context: 'The minimum grade-point average required to be accepted into a competitive programme.',
      contextDari: 'حداقل معدل لازم برای پذیرش در یک رشته رقابتی.',
      difficulty: 'hard'),

  VocabWord(id: 'bs16', german: 'der Abschluss', phonetic: '/ˈapʃlʊs/', english: 'Degree / Qualification / Graduation', dari: 'مدرک تحصیلی / فارغ‌التحصیلی',
      category: 'Bildung & Schule', tag: 'Qualification',
      example: 'Er hat seinen Abschluss mit Auszeichnung gemacht.',
      context: 'The qualification awarded at the end of a study programme.',
      contextDari: 'مدرکی که در پایان یک برنامه تحصیلی اعطا می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'bs17', german: 'der Bachelor', phonetic: '/ˈbɛtʃəlɐ/', english: 'Bachelor\'s degree', dari: 'لیسانس / بکالوریا',
      category: 'Bildung & Schule', tag: 'Qualification',
      example: 'Ich mache gerade meinen Bachelor in Informatik.',
      context: 'A first undergraduate university degree (3–4 years).',
      contextDari: 'اولین مدرک دانشگاهی (۳–۴ سال).',
      difficulty: 'easy'),

  VocabWord(id: 'bs18', german: 'der Master', phonetic: '/ˈmaːstɐ/', english: 'Master\'s degree', dari: 'ماستری / فوق‌لیسانس',
      category: 'Bildung & Schule', tag: 'Qualification',
      example: 'Nach dem Bachelor möchte ich den Master machen.',
      context: 'A postgraduate university degree (1–2 years after Bachelor).',
      contextDari: 'مدرک تحصیلات تکمیلی (۱–۲ سال پس از لیسانس).',
      difficulty: 'easy'),

  VocabWord(id: 'bs19', german: 'die Anerkennung', phonetic: '/ˈanɛɐ̯ˌkɛnʊŋ/', english: 'Recognition / Accreditation (of qualifications)', dari: 'تأیید مدرک / معادل‌سازی',
      category: 'Bildung & Schule', tag: 'Qualification',
      example: 'Ich muss mein ausländisches Zeugnis anerkennen lassen.',
      context: 'The official process of having foreign qualifications recognised in Germany.',
      contextDari: 'فرآیند رسمی تأیید مدارک خارجی در آلمان.',
      difficulty: 'hard'),

  VocabWord(id: 'bs20', german: 'der Sprachkurs', phonetic: '/ˈʃpʁaːxˌkʊʁs/', english: 'Language course', dari: 'کورس زبان',
      category: 'Bildung & Schule', tag: 'Language',
      example: 'Ich besuche einen Deutschkurs am Volkshochschule.',
      context: 'A course to learn or improve a language.',
      contextDari: 'یک کورس برای یادگیری یا بهبود یک زبان.',
      difficulty: 'easy'),

  VocabWord(id: 'bs21', german: 'das Sprachzertifikat', phonetic: '/ˈʃpʁaːxˌt͡sɛʁtifiˌkaːt/', english: 'Language certificate', dari: 'سرتیفیکیت زبان',
      category: 'Bildung & Schule', tag: 'Language',
      example: 'Ein B2-Sprachzertifikat ist für das Studium erforderlich.',
      context: 'An official certificate proving language proficiency (e.g. Goethe, TestDaF, telc).',
      contextDari: 'یک گواهینامه رسمی که مهارت زبانی را اثبات می‌کند (مثلاً Goethe، TestDaF).',
      difficulty: 'medium'),

  VocabWord(id: 'bs22', german: 'die Volkshochschule (VHS)', phonetic: '/ˈfɔlksˌhoːxˌʃuːlə/', english: 'Adult education centre', dari: 'مرکز آموزش بزرگسالان / فولکسهوخشوله',
      category: 'Bildung & Schule', tag: 'Language',
      example: 'Die VHS bietet günstige Deutschkurse für alle Niveaus.',
      context: 'A public adult education centre in Germany offering affordable courses.',
      contextDari: 'یک مرکز آموزش بزرگسالان عمومی در آلمان که کورس‌های مقرون‌به‌صرفه ارائه می‌دهد.',
      difficulty: 'medium'),

  VocabWord(id: 'bs23', german: 'die Note', phonetic: '/ˈnoːtə/', english: 'Grade / Mark', dari: 'نمره / درجه',
      category: 'Bildung & Schule', tag: 'Exams',
      example: 'In Deutschland ist Note 1 die beste Note.',
      context: 'In Germany grades run from 1 (sehr gut/excellent) to 6 (ungenügend/fail).',
      contextDari: 'در آلمان نمرات از ۱ (عالی) تا ۶ (ردشدنی) است.',
      difficulty: 'easy'),

  VocabWord(id: 'bs24', german: 'die Immatrikulation', phonetic: '/ɪmatʁikʊlaˈt͡si̯oːn/', english: 'University enrolment / Matriculation', dari: 'ثبت‌نام رسمی دانشگاه',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Nach der Immatrikulation erhalten Sie Ihren Studentenausweis.',
      context: 'The formal process of being enrolled as a student at a university.',
      contextDari: 'فرآیند رسمی ثبت‌نام به عنوان دانشجو در یک دانشگاه.',
      difficulty: 'hard'),

  VocabWord(id: 'bs25', german: 'der Semesterbeitrag', phonetic: '/zeˈmɛstɐˌbaɪ̯tʁaːk/', english: 'Semester fee', dari: 'فیس سمستر / هزینه دانشگاه',
      category: 'Bildung & Schule', tag: 'University',
      example: 'Der Semesterbeitrag beträgt ca. 300 Euro und beinhaltet das Semesterticket.',
      context: 'A fee paid each semester that includes public transport in the city.',
      contextDari: 'هزینه‌ای که هر سمستر پرداخت می‌شود و حمل و نقل عمومی شهر را شامل می‌شود.',
      difficulty: 'hard'),

  // ═══════════════════════════════════════════════════════════════════════════
  // VISUM & BEHÖRDEN  (Visa & Government Authorities)  — 26 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'vi01', german: 'das Visum', phonetic: '/ˈviːzʊm/', english: 'Visa', dari: 'ویزا',
      category: 'Visum & Behörden', tag: 'Visa',
      example: 'Ich habe ein Visum für Deutschland beantragt.',
      context: 'An official permission to enter, stay or work in a country.',
      contextDari: 'اجازه رسمی برای ورود، اقامت یا کار در یک کشور.',
      difficulty: 'easy'),

  VocabWord(id: 'vi02', german: 'die Aufenthaltserlaubnis', phonetic: '/ˈaʊ̯fɛnthaltsɛɐ̯ˌlaʊ̯bnɪs/', english: 'Residence permit', dari: 'اجازه اقامت',
      category: 'Visum & Behörden', tag: 'Residence',
      example: 'Meine Aufenthaltserlaubnis läuft im März ab.',
      context: 'A permit allowing a non-EU citizen to live in Germany for a set period.',
      contextDari: 'مجوزی که به یک شهروند غیر اتحادیه اروپایی اجازه می‌دهد برای مدت معین در آلمان زندگی کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi03', german: 'die Niederlassungserlaubnis', phonetic: '/ˌniːdɐˈlasʊŋsɛɐ̯ˌlaʊ̯bnɪs/', english: 'Permanent residence permit', dari: 'اجازه اقامت دائم',
      category: 'Visum & Behörden', tag: 'Residence',
      example: 'Nach 5 Jahren kann man die Niederlassungserlaubnis beantragen.',
      context: 'An unlimited residence permit — a step toward permanent settlement in Germany.',
      contextDari: 'یک مجوز اقامت نامحدود — گامی به سوی استقرار دائمی در آلمان.',
      difficulty: 'hard'),

  VocabWord(id: 'vi04', german: 'die Ausländerbehörde', phonetic: '/ˈaʊ̯slɛndɐbəˌhøːʁdə/', english: 'Immigration office / Foreigners\' authority', dari: 'اداره اتباع خارجه',
      category: 'Visum & Behörden', tag: 'Authority',
      example: 'Ich habe einen Termin bei der Ausländerbehörde.',
      context: 'The local government office that handles visas and residence permits.',
      contextDari: 'دفتر دولتی محلی که ویزاها و اجازه‌های اقامت را مدیریت می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi05', german: 'das Einwohnermeldeamt', phonetic: '/ˈaɪ̯nvoːnɐˌmɛldeˌʔamt/', english: 'Registration office (for address)', dari: 'اداره ثبت آدرس',
      category: 'Visum & Behörden', tag: 'Authority',
      example: 'Ich muss mich innerhalb von zwei Wochen beim Einwohnermeldeamt anmelden.',
      context: 'The local office where everyone in Germany must register their home address.',
      contextDari: 'دفتر محلی که هر کس در آلمان باید آدرس خانه خود را در آن ثبت کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi06', german: 'der Reisepass', phonetic: '/ˈʁaɪ̯zəˌpas/', english: 'Passport', dari: 'پاسپورت / گذرنامه',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Mein Reisepass ist noch zwei Jahre gültig.',
      context: 'An official travel document issued by a government.',
      contextDari: 'یک سند سفر رسمی که توسط دولت صادر می‌شود.',
      difficulty: 'easy'),

  VocabWord(id: 'vi07', german: 'beantragen', phonetic: '/bəˈantʁaːɡn̩/', english: 'To apply for / To request', dari: 'درخواست دادن / تقاضا کردن',
      category: 'Visum & Behörden', tag: 'Action',
      example: 'Ich möchte eine Aufenthaltserlaubnis beantragen.',
      context: 'To formally apply for an official document or permit.',
      contextDari: 'رسماً درخواست دادن برای یک سند یا مجوز رسمی.',
      difficulty: 'medium'),

  VocabWord(id: 'vi08', german: 'verlängern', phonetic: '/fɛɐ̯ˈlɛŋɐn/', english: 'To extend / To renew (visa, permit)', dari: 'تمدید کردن',
      category: 'Visum & Behörden', tag: 'Action',
      example: 'Ich muss mein Visum verlängern.',
      context: 'To extend the validity of a visa or permit.',
      contextDari: 'تمدید اعتبار یک ویزا یا مجوز.',
      difficulty: 'medium'),

  VocabWord(id: 'vi09', german: 'ablaufen', phonetic: '/ˈapˌlaʊ̯fn̩/', english: 'To expire', dari: 'منقضی شدن / ختم شدن',
      category: 'Visum & Behörden', tag: 'Action',
      example: 'Mein Visum läuft nächsten Monat ab.',
      context: 'When a document is no longer valid after its expiry date.',
      contextDari: 'وقتی یک سند پس از تاریخ انقضا دیگر معتبر نیست.',
      difficulty: 'medium'),

  VocabWord(id: 'vi10', german: 'die Apostille', phonetic: '/apoˈstɪlə/', english: 'Apostille (document certification)', dari: 'آپوستیل / تأیید سند بین‌المللی',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Das Zeugnis muss mit einer Apostille beglaubigt werden.',
      context: 'An international certification confirming the authenticity of a document.',
      contextDari: 'یک گواهینامه بین‌المللی که صحت یک سند را تأیید می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi11', german: 'beglaubigen', phonetic: '/bəˈɡlaʊ̯bɪɡn̩/', english: 'To certify / To authenticate', dari: 'تصدیق کردن / مُهر رسمی زدن',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Ich brauche eine beglaubigte Kopie meines Abschlusszeugnisses.',
      context: 'To officially confirm a document is genuine, e.g. by a notary.',
      contextDari: 'تأیید رسمی که یک سند معتبر است، مثلاً توسط یک نوتاریوس.',
      difficulty: 'hard'),

  VocabWord(id: 'vi12', german: 'die Übersetzung', phonetic: '/yːbɐˈzɛt͡sʊŋ/', english: 'Translation', dari: 'ترجمه',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Ich brauche eine beglaubigte Übersetzung meines Reisepasses.',
      context: 'For visa applications, documents often need certified German translations.',
      contextDari: 'برای درخواست ویزا، اسناد اغلب به ترجمه‌های آلمانی تأیید شده نیاز دارند.',
      difficulty: 'medium'),

  VocabWord(id: 'vi13', german: 'die Botschaft', phonetic: '/ˈboːtʃaft/', english: 'Embassy', dari: 'سفارت',
      category: 'Visum & Behörden', tag: 'Authority',
      example: 'Das Visum muss bei der deutschen Botschaft beantragt werden.',
      context: 'The official representation of a country in another country.',
      contextDari: 'نمایندگی رسمی یک کشور در کشور دیگر.',
      difficulty: 'easy'),

  VocabWord(id: 'vi14', german: 'das Konsulat', phonetic: '/kɔnzuˈlaːt/', english: 'Consulate', dari: 'کنسولگری',
      category: 'Visum & Behörden', tag: 'Authority',
      example: 'Das Konsulat stellt Visa für kürzere Aufenthalte aus.',
      context: 'A smaller official representative office of a foreign country.',
      contextDari: 'یک دفتر نمایندگی رسمی کوچکتر از یک کشور خارجی.',
      difficulty: 'medium'),

  VocabWord(id: 'vi15', german: 'der Integrationskurs', phonetic: '/ɪntɛɡʁaˈt͡si̯oːnˌkʊʁs/', english: 'Integration course', dari: 'دوره ادغام / انتگراسیون',
      category: 'Visum & Behörden', tag: 'Integration',
      example: 'Der Integrationskurs umfasst Deutschkurs und Orientierungskurs.',
      context: 'A state-funded course for immigrants including German language and civic education.',
      contextDari: 'یک دوره تأمین مالی شده توسط دولت برای مهاجران شامل زبان آلمانی و آموزش مدنی.',
      difficulty: 'hard'),

  VocabWord(id: 'vi16', german: 'die Arbeitserlaubnis', phonetic: '/ˈaʁbaɪ̯tsɛɐ̯ˌlaʊ̯bnɪs/', english: 'Work permit', dari: 'اجازه کار',
      category: 'Visum & Behörden', tag: 'Work',
      example: 'Brauchen Sie eine Arbeitserlaubnis?',
      context: 'Official permission for a non-EU citizen to work in Germany.',
      contextDari: 'اجازه رسمی برای یک شهروند غیر اتحادیه اروپایی برای کار در آلمان.',
      difficulty: 'hard'),

  VocabWord(id: 'vi17', german: 'der Antrag', phonetic: '/ˈantʁaːk/', english: 'Application / Request (official)', dari: 'درخواست / عریضه',
      category: 'Visum & Behörden', tag: 'Action',
      example: 'Ich stelle einen Antrag auf Aufenthaltserlaubnis.',
      context: 'A formal written request to an authority.',
      contextDari: 'یک درخواست مکتوب رسمی به یک مرجع.',
      difficulty: 'medium'),

  VocabWord(id: 'vi18', german: 'die Wartezeit', phonetic: '/ˈvaʁtəˌt͡saɪ̯t/', english: 'Waiting period / Processing time', dari: 'زمان انتظار / مدت پروسه',
      category: 'Visum & Behörden', tag: 'Process',
      example: 'Die Wartezeit für einen Termin beträgt mehrere Wochen.',
      context: 'The time you must wait for an appointment or a decision.',
      contextDari: 'زمانی که باید برای یک وقت ملاقات یا تصمیم منتظر بمانید.',
      difficulty: 'medium'),

  VocabWord(id: 'vi19', german: 'der Aufenthaltstitel', phonetic: '/ˈaʊ̯fɛnthaltsˌtiːtl̩/', english: 'Residence title (general term)', dari: 'عنوان اقامت / تایتل اقامتی',
      category: 'Visum & Behörden', tag: 'Residence',
      example: 'Welchen Aufenthaltstitel haben Sie?',
      context: 'The general term for any official right to stay in Germany.',
      contextDari: 'اصطلاح عمومی برای هر حق اقامت رسمی در آلمان.',
      difficulty: 'hard'),

  VocabWord(id: 'vi20', german: 'die Meldebescheinigung', phonetic: '/ˈmɛldəbəˌʃaɪ̯nɪɡʊŋ/', english: 'Certificate of registration (proof of address)', dari: 'گواهی ثبت آدرس',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Die Meldebescheinigung brauche ich für die Kontoeröffnung.',
      context: 'Official document proving your registered address in Germany, needed for many applications.',
      contextDari: 'سند رسمی که آدرس ثبت‌شده شما را در آلمان اثبات می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi21', german: 'zuständig sein', phonetic: '/ˈt͡suːˌʃtɛndɪç zaɪ̯n/', english: 'To be responsible for / In charge of', dari: 'مسئول بودن / صلاحیت داشتن',
      category: 'Visum & Behörden', tag: 'Communication',
      example: 'Welches Amt ist für meinen Fall zuständig?',
      context: 'To be the correct authority or person responsible for a matter.',
      contextDari: 'مرجع یا شخص صحیح مسئول یک موضوع بودن.',
      difficulty: 'medium'),

  VocabWord(id: 'vi22', german: 'die Bescheinigung', phonetic: '/bəˈʃaɪ̯nɪɡʊŋ/', english: 'Certificate / Confirmation document', dari: 'گواهینامه / تأییدیه',
      category: 'Visum & Behörden', tag: 'Document',
      example: 'Ich brauche eine Bescheinigung vom Arbeitgeber.',
      context: 'An official written confirmation of a fact (employment, enrolment, etc.).',
      contextDari: 'یک تأیید مکتوب رسمی از یک واقعیت (استخدام، ثبت‌نام و غیره).',
      difficulty: 'medium'),

  VocabWord(id: 'vi23', german: 'nachweisen', phonetic: '/ˈnaːxˌvaɪ̯zn̩/', english: 'To prove / To demonstrate (officially)', dari: 'اثبات کردن / نشان دادن مدرک',
      category: 'Visum & Behörden', tag: 'Action',
      example: 'Sie müssen ausreichende Sprachkenntnisse nachweisen.',
      context: 'To provide official evidence or proof of something.',
      contextDari: 'ارائه مدرک رسمی یا دلیل برای چیزی.',
      difficulty: 'medium'),

  VocabWord(id: 'vi24', german: 'die Fiktionsbescheinigung', phonetic: '/fɪkˈt͡si̯oːnsbəˌʃaɪ̯nɪɡʊŋ/', english: 'Bridging document (while permit is being processed)', dari: 'سند موقت اقامت / فیکسیون',
      category: 'Visum & Behörden', tag: 'Residence',
      example: 'Solange mein Antrag läuft, habe ich eine Fiktionsbescheinigung.',
      context: 'A temporary document proving your right to stay while your application is pending.',
      contextDari: 'یک سند موقت که حق اقامت شما را در زمان انتظار برای تصمیم اثبات می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'vi25', german: 'die Einbürgerung', phonetic: '/ˈaɪ̯nbʏʁɡəʁʊŋ/', english: 'Naturalisation / Citizenship', dari: 'تابعیت / شهروندی',
      category: 'Visum & Behörden', tag: 'Citizenship',
      example: 'Nach acht Jahren kann ich die Einbürgerung beantragen.',
      context: 'The legal process of becoming a citizen of Germany.',
      contextDari: 'فرآیند قانونی تبدیل شدن به یک شهروند آلمانی.',
      difficulty: 'hard'),

  VocabWord(id: 'vi26', german: 'das Ausländerrecht', phonetic: '/ˈaʊ̯slɛndɐˌʁɛçt/', english: 'Immigration law', dari: 'قانون اتباع خارجه',
      category: 'Visum & Behörden', tag: 'Legal',
      example: 'Das Ausländerrecht regelt die Einreise und den Aufenthalt.',
      context: 'The body of German law governing residence and entry of foreign nationals.',
      contextDari: 'مجموعه قوانین آلمانی که اقامت و ورود اتباع خارجه را تنظیم می‌کند.',
      difficulty: 'hard'),

  // ═══════════════════════════════════════════════════════════════════════════
  // AUSBILDUNG & PRAKTIKUM  (Vocational Training & Internship)  — 25 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'au01', german: 'die Ausbildung', phonetic: '/ˈaʊ̯sbɪldʊŋ/', english: 'Vocational training / Apprenticeship', dari: 'آموزش مسلکی / اپرنتیسشیپ',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Ich mache eine Ausbildung zum Kaufmann.',
      context: 'A dual vocational training system combining workplace and school-based learning.',
      contextDari: 'یک سیستم آموزش مسلکی دوگانه که یادگیری در محیط کار و مدرسه را ترکیب می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'au02', german: 'der Ausbildungsbetrieb', phonetic: '/ˈaʊ̯sbɪldʊŋsbəˌtʁiːp/', english: 'Training company / Employer during apprenticeship', dari: 'شرکت آموزش‌دهنده / کارفرمای دوران اپرنتیسشیپ',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Mein Ausbildungsbetrieb ist eine mittelständische Firma.',
      context: 'The company where the practical part of the Ausbildung takes place.',
      contextDari: 'شرکتی که بخش عملی آموزش مسلکی در آن انجام می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'au03', german: 'die Berufsschule', phonetic: '/bəˈʁuːfsˌʃuːlə/', english: 'Vocational school', dari: 'مکتب مسلکی / مدرسه فنی',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'An der Berufsschule lerne ich die theoretischen Grundlagen.',
      context: 'The school component of the dual apprenticeship system.',
      contextDari: 'بخش مکتبی سیستم اپرنتیسشیپ دوگانه.',
      difficulty: 'medium'),

  VocabWord(id: 'au04', german: 'der Ausbilder / die Ausbilderin', phonetic: '/ˈaʊ̯sbɪldɐ/', english: 'Trainer / Mentor (during apprenticeship)', dari: 'مربی / استاد کارآموزی',
      category: 'Ausbildung & Praktikum', tag: 'People',
      example: 'Mein Ausbilder erklärt mir die Aufgaben.',
      context: 'The person responsible for supervising and training an apprentice.',
      contextDari: 'شخصی که مسئول نظارت و آموزش یک کارآموز است.',
      difficulty: 'medium'),

  VocabWord(id: 'au05', german: 'der Auszubildende (Azubi)', phonetic: '/ˈaʊ̯st͡suˌbɪldəndə/', english: 'Apprentice / Trainee', dari: 'کارآموز / شاگرد',
      category: 'Ausbildung & Praktikum', tag: 'People',
      example: 'Als Azubi verdiene ich 800 Euro im Monat.',
      context: 'A person undergoing vocational training (Ausbildung). Often called "Azubi".',
      contextDari: 'شخصی که در حال گذراندن آموزش مسلکی است. اغلب "Azubi" نامیده می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'au06', german: 'die Ausbildungsvergütung', phonetic: '/ˈaʊ̯sbɪldʊŋsfɛɐ̯ˌɡyːtʊŋ/', english: 'Apprenticeship allowance / Training pay', dari: 'کمک هزینه آموزشی / معاش دوران کارآموزی',
      category: 'Ausbildung & Praktikum', tag: 'Finance',
      example: 'Die Ausbildungsvergütung steigt jedes Jahr.',
      context: 'The monthly payment an apprentice receives during training.',
      contextDari: 'پرداخت ماهانه‌ای که یک کارآموز در دوران آموزش دریافت می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'au07', german: 'der Ausbildungsvertrag', phonetic: '/ˈaʊ̯sbɪldʊŋsfɛɐ̯ˌtʁaːk/', english: 'Apprenticeship contract', dari: 'قرارداد کارآموزی',
      category: 'Ausbildung & Praktikum', tag: 'Contract',
      example: 'Der Ausbildungsvertrag muss von beiden Seiten unterschrieben werden.',
      context: 'The legal contract between the apprentice and the training company.',
      contextDari: 'قرارداد قانونی بین کارآموز و شرکت آموزش‌دهنده.',
      difficulty: 'hard'),

  VocabWord(id: 'au08', german: 'das Praktikum', phonetic: '/ˈpʁaktikʊm/', english: 'Internship / Work placement', dari: 'انترنشیپ / کارآموزی',
      category: 'Ausbildung & Praktikum', tag: 'Internship',
      example: 'Ich mache ein Praktikum bei einer IT-Firma.',
      context: 'A temporary work placement to gain experience in a field.',
      contextDari: 'یک موقعیت کاری موقت برای کسب تجربه در یک حوزه.',
      difficulty: 'medium'),

  VocabWord(id: 'au09', german: 'der Praktikant / die Praktikantin', phonetic: '/pʁaktiˈkant/', english: 'Intern', dari: 'انترن / کارآموز',
      category: 'Ausbildung & Praktikum', tag: 'People',
      example: 'Als Praktikant helfe ich im Marketing-Team.',
      context: 'A person doing an internship.',
      contextDari: 'شخصی که در حال گذراندن انترنشیپ است.',
      difficulty: 'easy'),

  VocabWord(id: 'au10', german: 'die Abschlussprüfung', phonetic: '/ˈapʃlʊsˌpʁyːfʊŋ/', english: 'Final exam / Graduation exam', dari: 'امتحان ختم دوره / امتحان فارغ‌التحصیلی',
      category: 'Ausbildung & Praktikum', tag: 'Exams',
      example: 'Die Abschlussprüfung findet vor der IHK statt.',
      context: 'The final examination at the end of the Ausbildung, conducted by the Chamber of Commerce (IHK).',
      contextDari: 'امتحان نهایی در پایان آموزش مسلکی، توسط اتاق بازرگانی (IHK) برگزار می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'au11', german: 'die IHK (Industrie- und Handelskammer)', phonetic: '/iːhaːˈkaː/', english: 'Chamber of Commerce and Industry', dari: 'اتاق صنعت و بازرگانی',
      category: 'Ausbildung & Praktikum', tag: 'Organisation',
      example: 'Die IHK organisiert die Abschlussprüfungen.',
      context: 'The body that certifies vocational qualifications in Germany.',
      contextDari: 'نهادی که مدارک حرفه‌ای را در آلمان تأیید می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'au12', german: 'der Berufsberater', phonetic: '/bəˈʁuːfsˌbəˌʁaːtɐ/', english: 'Careers advisor / Vocational counsellor', dari: 'مشاور شغلی',
      category: 'Ausbildung & Praktikum', tag: 'Support',
      example: 'Der Berufsberater bei der Agentur für Arbeit hilft mir.',
      context: 'An advisor who helps people choose suitable careers or training.',
      contextDari: 'یک مشاور که به افراد کمک می‌کند مسیرهای شغلی یا آموزشی مناسب را انتخاب کنند.',
      difficulty: 'medium'),

  VocabWord(id: 'au13', german: 'die Umschulung', phonetic: '/ˈʊmˌʃuːlʊŋ/', english: 'Retraining / Career change training', dari: 'بازآموزی / آموزش تغییر شغل',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Nach dem Jobverlust mache ich eine Umschulung.',
      context: 'Training for a completely different profession, often funded by the employment agency.',
      contextDari: 'آموزش برای یک حرفه کاملاً متفاوت، اغلب توسط آژانس اشتغال تأمین مالی می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'au14', german: 'die Weiterbildung', phonetic: '/ˈvaɪ̯tɐˌbɪldʊŋ/', english: 'Further training / Continuing education', dari: 'آموزش تکمیلی / ارتقای مهارت',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Ich mache eine Weiterbildung zum Projektmanager.',
      context: 'Training to advance skills within the same or a related profession.',
      contextDari: 'آموزش برای پیشرفت مهارت‌ها در همان حرفه یا حرفه مرتبط.',
      difficulty: 'medium'),

  VocabWord(id: 'au15', german: 'der Bildungsgutschein', phonetic: '/ˈbɪldʊŋsˌɡuːtʃaɪ̯n/', english: 'Education voucher (from job centre)', dari: 'بُرگه آموزشی / ووچر تحصیلی',
      category: 'Ausbildung & Praktikum', tag: 'Funding',
      example: 'Mit dem Bildungsgutschein kann ich kostenlos einen Kurs besuchen.',
      context: 'A voucher from the German job centre (Agentur für Arbeit) covering the cost of training.',
      contextDari: 'یک ووچر از مرکز کاریابی آلمانی که هزینه آموزش را پوشش می‌دهد.',
      difficulty: 'hard'),

  VocabWord(id: 'au16', german: 'das Gesellenstück', phonetic: '/ɡəˈzɛlənˌʃtʏk/', english: 'Journeyman\'s piece / Qualifying work', dari: 'کار نهایی کارآموزی در حرفه‌های فنی',
      category: 'Ausbildung & Praktikum', tag: 'Exams',
      example: 'Der Tischler hat sein Gesellenstück fertiggestellt.',
      context: 'A piece of work made by a craftsperson to complete their apprenticeship.',
      contextDari: 'یک اثر کاری که توسط یک صنعتگر برای تکمیل کارآموزی ساخته می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'au17', german: 'der Gesellenbrief', phonetic: '/ɡəˈzɛlənˌbʁiːf/', english: 'Journeyman\'s certificate', dari: 'گواهینامه پایان کارآموزی صنعتی',
      category: 'Ausbildung & Praktikum', tag: 'Qualification',
      example: 'Nach der Prüfung erhält man den Gesellenbrief.',
      context: 'The certificate awarded on completion of a craft trade apprenticeship.',
      contextDari: 'گواهینامه‌ای که پس از تکمیل کارآموزی حرفه صنعتی اعطا می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'au18', german: 'betrieblich', phonetic: '/bəˈtʁiːplɪç/', english: 'Company-based / In-house', dari: 'سازمانی / داخل شرکت',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Die betriebliche Ausbildung findet im Unternehmen statt.',
      context: 'Relating to the practical, workplace part of training.',
      contextDari: 'مربوط به بخش عملی آموزش در محیط کار.',
      difficulty: 'medium'),

  VocabWord(id: 'au19', german: 'die Probezeit (Ausbildung)', phonetic: '/ˈpʁoːbəˌt͡saɪ̯t/', english: 'Trial period (apprenticeship)', dari: 'دوره آزمایشی (کارآموزی)',
      category: 'Ausbildung & Praktikum', tag: 'Contract',
      example: 'Die Probezeit der Ausbildung dauert drei Monate.',
      context: 'The initial period of an apprenticeship during which either party can end it.',
      contextDari: 'دوره اولیه کارآموزی که در طول آن هر طرف می‌تواند آن را پایان دهد.',
      difficulty: 'medium'),

  VocabWord(id: 'au20', german: 'das Berichtsheft', phonetic: '/bəˈʁɪçtsˌhɛft/', english: 'Training report booklet', dari: 'دفتر گزارش آموزشی',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Ich muss täglich das Berichtsheft ausfüllen.',
      context: 'A diary/log that apprentices must fill in daily to record what they learned.',
      contextDari: 'یک دفتر یادداشت که کارآموزان باید روزانه پُر کنند تا آنچه یاد گرفتند ثبت کنند.',
      difficulty: 'medium'),

  VocabWord(id: 'au21', german: 'der Facharbeiter', phonetic: '/ˈfaxˌaʁbaɪ̯tɐ/', english: 'Skilled worker / Qualified tradesperson', dari: 'کارگر ماهر / متخصص فنی',
      category: 'Ausbildung & Praktikum', tag: 'Qualification',
      example: 'Als Facharbeiter verdiene ich mehr als als Hilfskraft.',
      context: 'A worker who has completed vocational training in their trade.',
      contextDari: 'یک کارگر که آموزش مسلکی در حرفه خود را تکمیل کرده.',
      difficulty: 'medium'),

  VocabWord(id: 'au22', german: 'dual', phonetic: '/duˈaːl/', english: 'Dual (system)', dari: 'دوگانه (سیستم آموزش)',
      category: 'Ausbildung & Praktikum', tag: 'Training',
      example: 'Das duale Ausbildungssystem ist eine Besonderheit Deutschlands.',
      context: 'The dual system means learning happens both at work and at school simultaneously.',
      contextDari: 'سیستم دوگانه یعنی یادگیری به طور همزمان در محل کار و مکتب اتفاق می‌افتد.',
      difficulty: 'medium'),

  VocabWord(id: 'au23', german: 'der Meister', phonetic: '/ˈmaɪ̯stɐ/', english: 'Master craftsman / Meister', english: 'Master craftsman (advanced qualification)', dari: 'استاد / ماستر حرفه',
      category: 'Ausbildung & Praktikum', tag: 'Qualification',
      example: 'Nach dem Gesellenbrief kann man den Meister machen.',
      context: 'The highest vocational qualification in Germany, allowing you to train apprentices.',
      contextDari: 'بالاترین مدرک مسلکی در آلمان، که به شما اجازه می‌دهد کارآموز تربیت کنید.',
      difficulty: 'medium'),

  VocabWord(id: 'au24', german: 'der Praktikumsbericht', phonetic: '/ˈpʁaktikʊmsˌbəˌʁɪçt/', english: 'Internship report', dari: 'گزارش انترنشیپ',
      category: 'Ausbildung & Praktikum', tag: 'Internship',
      example: 'Am Ende muss ich einen Praktikumsbericht schreiben.',
      context: 'A written report summarising what was learned during an internship.',
      contextDari: 'یک گزارش مکتوب که خلاصه‌ای از آنچه در طول انترنشیپ یاد گرفته شده است.',
      difficulty: 'medium'),

  VocabWord(id: 'au25', german: 'freiwillig', phonetic: '/ˈfʁaɪ̯ˌvɪlɪç/', english: 'Voluntary / Unpaid (internship)', dari: 'داوطلبانه / بدون حقوق',
      category: 'Ausbildung & Praktikum', tag: 'Internship',
      example: 'Ich mache ein freiwilliges Praktikum neben dem Studium.',
      context: 'A voluntary internship done for experience, not required by a study programme.',
      contextDari: 'یک انترنشیپ داوطلبانه که برای کسب تجربه انجام می‌شود.',
      difficulty: 'easy'),

  // ═══════════════════════════════════════════════════════════════════════════
  // JOBSUCHE & BEWERBUNG  (Job Search & Applications)  — 24 words
  // ═══════════════════════════════════════════════════════════════════════════

  VocabWord(id: 'jb01', german: 'die Stellenanzeige', phonetic: '/ˈʃtɛlənˌʔant͡saɪ̯ɡə/', english: 'Job advertisement / Job listing', dari: 'آگهی شغلی',
      category: 'Jobsuche & Bewerbung', tag: 'Job Search',
      example: 'Ich habe die Stellenanzeige auf LinkedIn gesehen.',
      context: 'An advertisement for an available job position.',
      contextDari: 'یک آگهی برای یک موقعیت شغلی موجود.',
      difficulty: 'medium'),

  VocabWord(id: 'jb02', german: 'das Jobportal', phonetic: '/ˈdʒɔpˌpɔʁtaːl/', english: 'Job portal / Job website', dari: 'پورتال کاریابی / سایت شغلی',
      category: 'Jobsuche & Bewerbung', tag: 'Job Search',
      example: 'Ich suche auf Indeed und StepStone nach Jobs.',
      context: 'Websites like Indeed, StepStone, Xing, LinkedIn used to find jobs in Germany.',
      contextDari: 'وب‌سایت‌هایی مانند Indeed، StepStone، Xing، LinkedIn برای یافتن کار در آلمان.',
      difficulty: 'easy'),

  VocabWord(id: 'jb03', german: 'die Agentur für Arbeit', phonetic: '/aˈɡɛntuːɐ̯ fyːɐ̯ ˈaʁbaɪ̯t/', english: 'Federal Employment Agency', dari: 'آژانس اشتغال / آربایتس‌آمت',
      category: 'Jobsuche & Bewerbung', tag: 'Authority',
      example: 'Bei der Agentur für Arbeit kann ich mich als arbeitssuchend melden.',
      context: 'The German government agency that manages unemployment benefits and job placement.',
      contextDari: 'آژانس دولتی آلمان که مزایای بیکاری و یافتن شغل را مدیریت می‌کند.',
      difficulty: 'hard'),

  VocabWord(id: 'jb04', german: 'arbeitslos', phonetic: '/ˈaʁbaɪ̯tsˌloːs/', english: 'Unemployed', dari: 'بیکار',
      category: 'Jobsuche & Bewerbung', tag: 'Status',
      example: 'Ich bin seit drei Monaten arbeitslos.',
      context: 'Not having paid employment.',
      contextDari: 'نداشتن استخدام با حقوق.',
      difficulty: 'easy'),

  VocabWord(id: 'jb05', german: 'das Arbeitslosengeld', phonetic: '/ˈaʁbaɪ̯tsloːzənˌɡɛlt/', english: 'Unemployment benefit', dari: 'حقوق بیکاری',
      category: 'Jobsuche & Bewerbung', tag: 'Finance',
      example: 'Ich beziehe Arbeitslosengeld seit dem Jobverlust.',
      context: 'A state payment to people who lose their job in Germany.',
      contextDari: 'یک پرداخت دولتی به افرادی که شغل خود را در آلمان از دست می‌دهند.',
      difficulty: 'hard'),

  VocabWord(id: 'jb06', german: 'sich bewerben', phonetic: '/zɪç bəˈvɛʁbn̩/', english: 'To apply (for a job)', dari: 'درخواست دادن / اپلای کردن',
      category: 'Jobsuche & Bewerbung', tag: 'Action',
      example: 'Ich bewerbe mich auf die Stelle als Buchhalter.',
      context: 'To submit an application for a job.',
      contextDari: 'ارسال یک درخواست برای یک شغل.',
      difficulty: 'medium'),

  VocabWord(id: 'jb07', german: 'die Bewerbungsunterlagen', phonetic: '/bəˈvɛʁbʊŋsˌʔʊntɐˌlaːɡən/', english: 'Application documents', dari: 'اسناد درخواست کار',
      category: 'Jobsuche & Bewerbung', tag: 'Application',
      example: 'Zu den Bewerbungsunterlagen gehören Lebenslauf, Anschreiben und Zeugnisse.',
      context: 'The complete set of documents submitted with a job application.',
      contextDari: 'مجموعه کامل اسنادی که با یک درخواست کار ارسال می‌شود.',
      difficulty: 'hard'),

  VocabWord(id: 'jb08', german: 'die Einladung (zum Vorstellungsgespräch)', phonetic: '/ˈaɪ̯nˌlaːdʊŋ/', english: 'Invitation to interview', dari: 'دعوتنامه برای مصاحبه',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Ich habe eine Einladung zum Vorstellungsgespräch erhalten.',
      context: 'Being invited to attend a job interview after submitting an application.',
      contextDari: 'دعوت شدن برای شرکت در مصاحبه شغلی پس از ارسال درخواست.',
      difficulty: 'medium'),

  VocabWord(id: 'jb09', german: 'die Absage', phonetic: '/ˈapˌzaːɡə/', english: 'Rejection (from a job application)', dari: 'رد شدن / جواب منفی',
      category: 'Jobsuche & Bewerbung', tag: 'Application',
      example: 'Ich habe leider eine Absage erhalten.',
      context: 'A formal rejection letter or email from an employer.',
      contextDari: 'یک نامه یا ایمیل رسمی رد کردن از کارفرما.',
      difficulty: 'easy'),

  VocabWord(id: 'jb10', german: 'die Zusage', phonetic: '/ˈt͡suːˌzaːɡə/', english: 'Job offer / Acceptance', dari: 'قبولی / پیشنهاد شغلی',
      category: 'Jobsuche & Bewerbung', tag: 'Application',
      example: 'Ich habe eine Zusage für die Stelle bekommen!',
      context: 'A positive reply confirming you have been offered the position.',
      contextDari: 'یک پاسخ مثبت که تأیید می‌کند موقعیت شغلی به شما پیشنهاد شده.',
      difficulty: 'easy'),

  VocabWord(id: 'jb11', german: 'das Vorstellungsgespräch', phonetic: '/ˈfoːɐ̯ʃtɛlʊŋsɡəˌʃpʁɛːç/', english: 'Job interview', dari: 'مصاحبه کاری',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Das Vorstellungsgespräch war auf Englisch und Deutsch.',
      context: 'A formal meeting between a job candidate and employer to assess suitability.',
      contextDari: 'یک جلسه رسمی بین یک کاندید شغلی و کارفرما برای ارزیابی تناسب.',
      difficulty: 'medium'),

  VocabWord(id: 'jb12', german: 'die Gehaltsvorstellung', phonetic: '/ɡəˈhaltsfoːɐ̯ˌʃtɛlʊŋ/', english: 'Expected salary / Salary expectation', dari: 'انتظار معاش / پیشنهاد حقوق',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Wie ist Ihre Gehaltsvorstellung?',
      context: 'The salary a candidate expects to receive for the role.',
      contextDari: 'معاشی که یک کاندید انتظار دارد برای این نقش دریافت کند.',
      difficulty: 'hard'),

  VocabWord(id: 'jb13', german: 'die Stärken und Schwächen', phonetic: '/ˈʃtɛʁkən ʊnt ˈʃvɛçən/', english: 'Strengths and weaknesses', dari: 'نقاط قوت و ضعف',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Welche Stärken bringen Sie mit?',
      context: 'Classic interview questions in Germany asking about personal strengths and weaknesses.',
      contextDari: 'سوالات کلاسیک مصاحبه در آلمان درباره نقاط قوت و ضعف شخصی.',
      difficulty: 'medium'),

  VocabWord(id: 'jb14', german: 'Vollzeit', phonetic: '/ˈfɔlˌt͡saɪ̯t/', english: 'Full-time', dari: 'تمام‌وقت',
      category: 'Jobsuche & Bewerbung', tag: 'Work Type',
      example: 'Ich suche eine Vollzeitstelle mit 40 Stunden pro Woche.',
      context: 'Working the standard full number of hours (usually 38–40 hrs/week in Germany).',
      contextDari: 'کار در تعداد ساعت کامل استاندارد (معمولاً ۳۸–۴۰ ساعت در هفته در آلمان).',
      difficulty: 'easy'),

  VocabWord(id: 'jb15', german: 'Teilzeit', phonetic: '/ˈtaɪ̯lˌt͡saɪ̯t/', english: 'Part-time', dari: 'نیمه‌وقت',
      category: 'Jobsuche & Bewerbung', tag: 'Work Type',
      example: 'Ich arbeite Teilzeit, 20 Stunden pro Woche.',
      context: 'Working fewer hours than the standard working week.',
      contextDari: 'کار کردن با ساعات کمتر از هفته کاری استاندارد.',
      difficulty: 'easy'),

  VocabWord(id: 'jb16', german: 'unbefristet', phonetic: '/ˈʊnbəˌfʁɪstɪt/', english: 'Permanent / Open-ended (contract)', dari: 'دائمی / نامحدود (قرارداد)',
      category: 'Jobsuche & Bewerbung', tag: 'Contract',
      example: 'Ich suche eine unbefristete Stelle.',
      context: 'A contract with no fixed end date — the goal for most job seekers in Germany.',
      contextDari: 'یک قرارداد بدون تاریخ پایان مشخص — هدف اکثر کارجویان در آلمان.',
      difficulty: 'medium'),

  VocabWord(id: 'jb17', german: 'befristet', phonetic: '/bəˈfʁɪstɪt/', english: 'Fixed-term / Temporary (contract)', dari: 'موقت / مدت‌دار (قرارداد)',
      category: 'Jobsuche & Bewerbung', tag: 'Contract',
      example: 'Mein Vertrag ist auf ein Jahr befristet.',
      context: 'A contract that expires after a set period of time.',
      contextDari: 'یک قرارداد که پس از یک مدت زمان مشخص منقضی می‌شود.',
      difficulty: 'medium'),

  VocabWord(id: 'jb18', german: 'die Stellenbeschreibung', phonetic: '/ˈʃtɛlənbəˌʃʁaɪ̯bʊŋ/', english: 'Job description', dari: 'شرح وظایف / توضیح شغلی',
      category: 'Jobsuche & Bewerbung', tag: 'Job Search',
      example: 'Lesen Sie die Stellenbeschreibung sorgfältig.',
      context: 'A document describing the duties and requirements of a job.',
      contextDari: 'سندی که وظایف و الزامات یک شغل را توصیف می‌کند.',
      difficulty: 'medium'),

  VocabWord(id: 'jb19', german: 'die Initiativbewerbung', phonetic: '/ɪniˈt͡si̯aːtifbəˌvɛʁbʊŋ/', english: 'Unsolicited / Speculative application', dari: 'درخواست خودجوش / اپلای بدون آگهی',
      category: 'Jobsuche & Bewerbung', tag: 'Application',
      example: 'Ich sende eine Initiativbewerbung an Firmen, die mich interessieren.',
      context: 'Applying to a company even if they have not advertised a vacancy.',
      contextDari: 'درخواست دادن به یک شرکت حتی اگر آگهی شغلی نداده باشند.',
      difficulty: 'hard'),

  VocabWord(id: 'jb20', german: 'das Netzwerken', phonetic: '/ˈnɛt͡svɛʁkn̩/', english: 'Networking', dari: 'نتورکینگ / ارتباط‌سازی',
      category: 'Jobsuche & Bewerbung', tag: 'Job Search',
      example: 'Netzwerken auf LinkedIn ist für die Jobsuche sehr wichtig.',
      context: 'Building professional relationships to advance your career.',
      contextDari: 'ایجاد روابط حرفه‌ای برای پیشرفت شغلی.',
      difficulty: 'medium'),

  VocabWord(id: 'jb21', german: 'das Headhunting', phonetic: '/ˈhɛdˌhantɪŋ/', english: 'Headhunting / Executive search', dari: 'هدهانتینگ / شکار نیرو',
      category: 'Jobsuche & Bewerbung', tag: 'Recruitment',
      example: 'Ich wurde von einem Headhunter auf Xing kontaktiert.',
      context: 'When recruiters proactively approach candidates for senior positions.',
      contextDari: 'وقتی استخدام‌کنندگان فعالانه برای موقعیت‌های ارشد با کاندیداها تماس می‌گیرند.',
      difficulty: 'medium'),

  VocabWord(id: 'jb22', german: 'der Personalvermittler', phonetic: '/pɛʁzoˈnaːlfɛɐ̯ˌmɪtlɐ/', english: 'Recruitment agency / Staffing agency', dari: 'آژانس استخدام / کاریابی',
      category: 'Jobsuche & Bewerbung', tag: 'Recruitment',
      example: 'Ich habe meinen Job über einen Personalvermittler gefunden.',
      context: 'An agency that matches job seekers with employers.',
      contextDari: 'یک آژانس که کارجویان را با کارفرمایان تطبیق می‌دهد.',
      difficulty: 'hard'),

  VocabWord(id: 'jb23', german: 'das Vorstellungsgespräch vorbereiten', phonetic: '/ˈfoːɐ̯ʃtɛlʊŋsɡəˌʃpʁɛːç foːɐ̯bəˌʁaɪ̯tn̩/', english: 'To prepare for an interview', dari: 'آماده شدن برای مصاحبه',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Ich bereite mich intensiv auf das Vorstellungsgespräch vor.',
      context: 'Researching the company, practising answers, and preparing questions to ask.',
      contextDari: 'تحقیق در مورد شرکت، تمرین پاسخ‌ها و آماده کردن سوالات برای پرسیدن.',
      difficulty: 'medium'),

  VocabWord(id: 'jb24', german: 'die Probearbeit', phonetic: '/ˈpʁoːbəˌaʁbaɪ̯t/', english: 'Trial work day / Working interview', dari: 'روز کار آزمایشی',
      category: 'Jobsuche & Bewerbung', tag: 'Interview',
      example: 'Ich werde morgen zur Probearbeit eingeladen.',
      context: 'A trial day at the workplace before a hiring decision is made, common in Germany.',
      contextDari: 'یک روز آزمایشی در محل کار قبل از تصمیم استخدام، که در آلمان رایج است.',
      difficulty: 'medium'),

];
