/// This class lists the paths to all the JSON content files in the app.
///
/// It organizes the files by level (A1, A2, etc.) and category.
class ContentAssets {
  static const String vocabularyContentStamp = '2026-03-30-v5';

  /// This list contains all vocabulary files for level A1.
  static const List<String> vocabularyA1 = [
    'assets/content/vocabulary/A1/01_name_origin.json',
    'assets/content/vocabulary/A1/02_address_phone.json',
    'assets/content/vocabulary/A1/03_documents.json',
    'assets/content/vocabulary/A1/04_date_of_birth.json',
    'assets/content/vocabulary/A1/05_marital_status.json',
    'assets/content/vocabulary/A1/06_age_nationality.json',
    'assets/content/vocabulary/A1/07_languages.json',
    'assets/content/vocabulary/A1/08_important_phrases_personal.json',
    'assets/content/vocabulary/A1/09_registration_anmeldung.json',
    'assets/content/vocabulary/A1/10_residence_permit_visa.json',
    'assets/content/vocabulary/A1/11_appointments_authorities.json',
    'assets/content/vocabulary/A1/12_forms_documents_authorities.json',
    'assets/content/vocabulary/A1/13_offices_authorities.json',
    'assets/content/vocabulary/A1/14_tax_id_numbers.json',
    'assets/content/vocabulary/A1/15_insurance_authorities.json',
    'assets/content/vocabulary/A1/16_legal_procedures.json',
    'assets/content/vocabulary/A1/17_important_phrases_authorities.json',
    'assets/content/vocabulary/A1/30_train_bus.json',
    'assets/content/vocabulary/A1/31_ticket_booking.json',
    'assets/content/vocabulary/A1/32_directions.json',
    'assets/content/vocabulary/A1/33_delays_problems.json',
    'assets/content/vocabulary/A1/34_airport.json',
    'assets/content/vocabulary/A1/35_hotel.json',
    'assets/content/vocabulary/A1/36_luggage.json',
    'assets/content/vocabulary/A1/37_important_phrases_travel.json',
    'assets/content/vocabulary/A1/38_apartment_search.json',
    'assets/content/vocabulary/A1/39_rent_contract.json',
    'assets/content/vocabulary/A1/40_utilities.json',
    'assets/content/vocabulary/A1/41_cleaning.json',
    'assets/content/vocabulary/A1/42_landlord_tenant.json',
    'assets/content/vocabulary/A1/43_symptoms.json',
    'assets/content/vocabulary/A1/44_doctor_visit.json',
    'assets/content/vocabulary/A1/45_emergency.json',
    'assets/content/vocabulary/A1/46_appointments_health.json',
    'assets/content/vocabulary/A1/47_medicine.json',
    'assets/content/vocabulary/A1/48_pharmacy.json',
    'assets/content/vocabulary/A1/49_insurance_health.json',
    'assets/content/vocabulary/A1/50_body_parts.json',
    'assets/content/vocabulary/A1/51_important_phrases_health.json',
    'assets/content/vocabulary/A1/60_greetings_daily.json',
    'assets/content/vocabulary/A1/61_numbers_daily.json',
    'assets/content/vocabulary/A1/62_time_calendar.json',
    'assets/content/vocabulary/A1/63_food_drinks.json',
    'assets/content/vocabulary/A1/64_shopping_prices.json',
    'assets/content/vocabulary/A1/65_family_daily.json',
    'assets/content/vocabulary/A1/66_home_basics.json',
    'assets/content/vocabulary/A1/67_daily_actions.json',
    'assets/content/vocabulary/A1/68_common_objects.json',
    'assets/content/vocabulary/A1/69_feelings_states.json',
    'assets/content/vocabulary/A1/70_important_phrases_daily.json',
    'assets/content/vocabulary/A1/87_alphabet_spelling.json',
    'assets/content/vocabulary/A1/88_weather_seasons.json',
    'assets/content/vocabulary/A1/89_hobbies_leisure.json',
    'assets/content/vocabulary/A1/90_clothing_colors.json',
    'assets/content/vocabulary/A1/91_invitations_events.json',
    'assets/content/vocabulary/A1/92_rooms.json',
    'assets/content/vocabulary/A1/93_furniture.json',
    'assets/content/vocabulary/A1/94_repairs.json',
    'assets/content/vocabulary/A1/95_important_phrases_home.json',
  ];

  /// This list contains all vocabulary files for level A2.
  static const List<String> vocabularyA2 = [
    'assets/content/vocabulary/A2/18_application.json',
    'assets/content/vocabulary/A2/19_office_tasks.json',
    'assets/content/vocabulary/A2/20_company.json',
    'assets/content/vocabulary/A2/21_meetings.json',
    'assets/content/vocabulary/A2/22_email_communication.json',
    'assets/content/vocabulary/A2/25_work_schedule_shifts.json',
    'assets/content/vocabulary/A2/29_important_phrases_work.json',
    'assets/content/vocabulary/A2/53_exams_homework.json',
    'assets/content/vocabulary/A2/54_registration_enrollment.json',
    'assets/content/vocabulary/A2/57_school.json',
    'assets/content/vocabulary/A2/58_subjects.json',
    'assets/content/vocabulary/A2/59_important_phrases_education.json',
  ];

  static const List<String> vocabularyB1 = [
    'assets/content/vocabulary/B1/23_salary_projects.json',
    'assets/content/vocabulary/B1/24_contracts.json',
    'assets/content/vocabulary/B1/26_finance.json',
    'assets/content/vocabulary/B1/27_marketing.json',
    'assets/content/vocabulary/B1/28_hr.json',
    'assets/content/vocabulary/B1/52_university.json',
    'assets/content/vocabulary/B1/55_courses_modules.json',
    'assets/content/vocabulary/B1/56_deadlines.json',
    'assets/content/vocabulary/B1/71_software_app.json',
    'assets/content/vocabulary/B1/72_internet_data.json',
    'assets/content/vocabulary/B1/73_accounts_login.json',
    'assets/content/vocabulary/B1/74_computer_hardware.json',
    'assets/content/vocabulary/B1/75_security.json',
    'assets/content/vocabulary/B1/76_files_storage.json',
    'assets/content/vocabulary/B1/77_social_media.json',
    'assets/content/vocabulary/B1/78_programming.json',
    'assets/content/vocabulary/B1/79_important_phrases_technology.json',
  ];

  static const List<String> vocabularyB2 = [
    'assets/content/vocabulary/B2/80_formal_phrases.json',
    'assets/content/vocabulary/B2/81_opinions_arguments.json',
    'assets/content/vocabulary/B2/82_cause_result.json',
    'assets/content/vocabulary/B2/83_comparison.json',
    'assets/content/vocabulary/B2/84_condition_hypothesis.json',
    'assets/content/vocabulary/B2/85_linking_words.json',
    'assets/content/vocabulary/B2/86_important_phrases_abstract.json',
  ];

    static const List<String> exercisesA1 = [
    'assets/content/exercises/A1/01_personalpronomen.json',
    'assets/content/exercises/A1/02_praesens.json',
    'assets/content/exercises/A1/03_bestimmte_artikel.json',
    'assets/content/exercises/A1/04_unbestimmte_artikel.json',
    'assets/content/exercises/A1/05_zahlen_and_zeitangaben.json',
    'assets/content/exercises/A1/06_w-fragen.json',
    'assets/content/exercises/A1/07_ja_nein-fragen.json',
    'assets/content/exercises/A1/08_satzbau.json',
    'assets/content/exercises/A1/09_negation.json',
    'assets/content/exercises/A1/10_pluralbildung.json',
    'assets/content/exercises/A1/11_du_vs._sie.json',
    'assets/content/exercises/A1/12_das_wort_\'doch\'.json',
    'assets/content/exercises/A1/13_adjektive.json',
    'assets/content/exercises/A1/14_adjektive_grundlagen.json',
    'assets/content/exercises/A1/15_nominativ_and_akkusativ.json',
    'assets/content/exercises/A1/16_possessivartikel.json',
    'assets/content/exercises/A1/17_modalverben.json',
    'assets/content/exercises/A1/18_trennbare_verben.json',
    'assets/content/exercises/A1/19_imperativ.json',
    'assets/content/exercises/A1/20_praepositionen_akk_dat.json',
  ];
    static const List<String> exercisesA2 = [
    'assets/content/exercises/A2/01_perfekt.json',
    'assets/content/exercises/A2/02_praeteritum.json',
    'assets/content/exercises/A2/03_futur_i.json',
    'assets/content/exercises/A2/04_dativ.json',
    'assets/content/exercises/A2/05_nebensaetze.json',
    'assets/content/exercises/A2/06_relativsaetze_grundlagen.json',
    'assets/content/exercises/A2/07_infinitivkonstruktionen.json',
    'assets/content/exercises/A2/08_wechselpraepositionen.json',
    'assets/content/exercises/A2/09_verben_mit_praepositionen.json',
    'assets/content/exercises/A2/10_reflexive_verben.json',
    'assets/content/exercises/A2/11_adjektivdeklination.json',
    'assets/content/exercises/A2/12_komparativ_and_superlativ.json',
    'assets/content/exercises/A2/13_indefinitpronomen.json',
    'assets/content/exercises/A2/14_konjunktionen.json',
    'assets/content/exercises/A2/15_passiv_grundlagen.json',
    'assets/content/exercises/A2/16_imperativ_erweitert.json',
    'assets/content/exercises/A2/17_wortbildung.json',
    'assets/content/exercises/A2/18_demonstrativartikel.json',
    'assets/content/exercises/A2/19_adverbien.json',
    'assets/content/exercises/A2/20_der_genitiv.json',
  ];
    static const List<String> exercisesB1 = [
    'assets/content/exercises/B1/01_genitiv.json',
    'assets/content/exercises/B1/02_n-deklination.json',
    'assets/content/exercises/B1/03_plusquamperfekt.json',
    'assets/content/exercises/B1/04_futur_i_and_ii.json',
    'assets/content/exercises/B1/05_konjunktiv_ii.json',
    'assets/content/exercises/B1/06_konditionalsaetze.json',
    'assets/content/exercises/B1/07_indirekte_rede.json',
    'assets/content/exercises/B1/08_relativsaetze.json',
    'assets/content/exercises/B1/09_relativsaetze_fortgeschritten.json',
    'assets/content/exercises/B1/10_nebensaetze.json',
    'assets/content/exercises/B1/11_erweiterte_nebensaetze.json',
    'assets/content/exercises/B1/12_partizipien_als_adjektive.json',
    'assets/content/exercises/B1/13_nominalisierung.json',
    'assets/content/exercises/B1/14_wortstellung_fortgeschritten.json',
    'assets/content/exercises/B1/15_doppelter_infinitiv.json',
    'assets/content/exercises/B1/16_passiv.json',
    'assets/content/exercises/B1/17_praepositionalobjekte.json',
    'assets/content/exercises/B1/18_infinitivsaetze.json',
  ];
    static const List<String> exercisesB2 = [
    'assets/content/exercises/B2/01_konjunktiv_i.json',
    'assets/content/exercises/B2/02_konjunktiv_ii_fortgeschritten.json',
    'assets/content/exercises/B2/03_irreale_vergleichssaetze.json',
    'assets/content/exercises/B2/04_passiv.json',
    'assets/content/exercises/B2/05_passiversatzformen.json',
    'assets/content/exercises/B2/06_genitiv-praepositionen.json',
    'assets/content/exercises/B2/07_genitiv.json',
    'assets/content/exercises/B2/08_praepositionalobjekte.json',
    'assets/content/exercises/B2/09_erweiterte_nebensaetze_b2.json',
    'assets/content/exercises/B2/10_nebensaetze.json',
    'assets/content/exercises/B2/11_konnektoren.json',
    'assets/content/exercises/B2/12_doppelkonnektoren.json',
    'assets/content/exercises/B2/13_partizipialkonstruktionen.json',
    'assets/content/exercises/B2/14_nominalstil.json',
    'assets/content/exercises/B2/15_funktionsverbgefuege.json',
    'assets/content/exercises/B2/16_infinitivsaetze.json',
    'assets/content/exercises/B2/17_berichtswesen.json',
    'assets/content/exercises/B2/18_beschaffung.json',
    'assets/content/exercises/B2/19_marketing.json',
  ];
    static const List<String> exercisesC1 = [
    'assets/content/exercises/C1/01_modalpartikeln.json',
    'assets/content/exercises/C1/02_subjektive_modalverben.json',
    'assets/content/exercises/C1/03_nomen-verb-verbindungen.json',
    'assets/content/exercises/C1/04_erweiterte_passivformen.json',
    'assets/content/exercises/C1/05_weiterfuehrende_nebensaetze.json',
    'assets/content/exercises/C1/06_apposition.json',
    'assets/content/exercises/C1/07_komplexe_attribute.json',
    'assets/content/exercises/C1/08_textkohaerenz_and_diskursmarker.json',
    'assets/content/exercises/C1/09_nominalstil.json',
    'assets/content/exercises/C1/10_wissenschaftssprache.json',
    'assets/content/exercises/C1/11_diskursmarker.json',
    'assets/content/exercises/C1/12_praepositionen.json',
    'assets/content/exercises/C1/13_strategisches_management.json',
    'assets/content/exercises/C1/14_compliance.json',
    'assets/content/exercises/C1/15_arbeitsrecht.json',
    'assets/content/exercises/C1/16_finanzierung.json',
    'assets/content/exercises/C1/17_unternehmensfuehrung.json',
    'assets/content/exercises/C1/18_wirtschaftspolitik.json',
  ];

  /// This list combines all vocabulary files from all levels.
  static const List<String> vocabulary = [
    ...vocabularyA1,
    ...vocabularyA2,
    ...vocabularyB1,
    ...vocabularyB2,
    'assets/content/vocabulary/misc.json',
  ];

  static const List<String> exercises = [
    ...exercisesA1,
    ...exercisesA2,
    ...exercisesB1,
    ...exercisesB2,
    ...exercisesC1,
  ];

  static const List<String> grammarA1 = [
    'assets/content/grammar/A1/01_bestimmte_artikel.json',
    'assets/content/grammar/A1/02_pluralbildung.json',
    'assets/content/grammar/A1/03_unbestimmte_artikel.json',
    'assets/content/grammar/A1/04_satzbau.json',
    'assets/content/grammar/A1/05_negation.json',
    'assets/content/grammar/A1/06_zahlen_zeitangaben.json',
    'assets/content/grammar/A1/07_das_wort_doch.json',
    'assets/content/grammar/A1/08_personalpronomen.json',
    'assets/content/grammar/A1/09_du_vs_sie.json',
    'assets/content/grammar/A1/10_possessivartikel.json',
    'assets/content/grammar/A1/11_praesens.json',
    'assets/content/grammar/A1/12_modalverben.json',
    'assets/content/grammar/A1/13_trennbare_verben.json',
    'assets/content/grammar/A1/14_imperativ.json',
    'assets/content/grammar/A1/15_adjektive_grundlagen.json',
    'assets/content/grammar/A1/16_nominativ_akkusativ.json',
    'assets/content/grammar/A1/17_praepositionen_akk_dat.json',
  ];

  static const List<String> grammarA2 = [
    'assets/content/grammar/A2/01_wortbildung.json',
    'assets/content/grammar/A2/02_indefinitpronomen.json',
    'assets/content/grammar/A2/03_demonstrativartikel.json',
    'assets/content/grammar/A2/04_perfekt.json',
    'assets/content/grammar/A2/05_praeteritum.json',
    'assets/content/grammar/A2/06_futur_i.json',
    'assets/content/grammar/A2/07_passiv_grundlagen.json',
    'assets/content/grammar/A2/08_infinitivkonstruktionen.json',
    'assets/content/grammar/A2/09_reflexive_verben.json',
    'assets/content/grammar/A2/10_verben_mit_praepositionen.json',
    'assets/content/grammar/A2/11_imperativ_erweitert.json',
    'assets/content/grammar/A2/12_konjunktiv_ii.json',
    'assets/content/grammar/A2/13_adjektivdeklination.json',
    'assets/content/grammar/A2/14_komparativ_superlativ.json',
    'assets/content/grammar/A2/15_adverbien.json',
    'assets/content/grammar/A2/16_nebensaetze.json',
    'assets/content/grammar/A2/17_wechselpraepositionen.json',
    'assets/content/grammar/A2/18_relativsaetze_grundlagen.json',
    'assets/content/grammar/A2/19_dativ.json',
    'assets/content/grammar/A2/20_konjunktionen.json',
    'assets/content/grammar/A2/21_der_genitiv.json',
  ];

  static const List<String> grammarB1 = [
    'assets/content/grammar/B1/01_wortstellung_fortgeschritten.json',
    'assets/content/grammar/B1/02_plusquamperfekt.json',
    'assets/content/grammar/B1/03_futur_i_ii.json',
    'assets/content/grammar/B1/04_partizipien_als_adjektive.json',
    'assets/content/grammar/B1/05_nominalisierung.json',
    'assets/content/grammar/B1/06_doppelter_infinitiv.json',
    'assets/content/grammar/B1/07_konjunktiv_ii.json',
    'assets/content/grammar/B1/08_indirekte_rede.json',
    'assets/content/grammar/B1/09_relativsaetze_fortgeschritten.json',
    'assets/content/grammar/B1/10_erweiterte_nebensaetze.json',
    'assets/content/grammar/B1/11_konditionalsaetze.json',
    'assets/content/grammar/B1/12_genitiv.json',
    'assets/content/grammar/B1/13_n_deklination.json',
  ];

  static const List<String> grammarB2 = [
    'assets/content/grammar/B2/01_nominalstil.json',
    'assets/content/grammar/B2/02_konnektoren.json',
    'assets/content/grammar/B2/03_doppelkonnektoren.json',
    'assets/content/grammar/B2/04_passiv.json',
    'assets/content/grammar/B2/05_partizipialkonstruktionen.json',
    'assets/content/grammar/B2/06_passiversatzformen.json',
    'assets/content/grammar/B2/07_funktionsverbgefuege.json',
    'assets/content/grammar/B2/08_konjunktiv_i.json',
    'assets/content/grammar/B2/09_konjunktiv_ii_fortgeschritten.json',
    'assets/content/grammar/B2/10_erweiterte_nebensaetze_b2.json',
    'assets/content/grammar/B2/11_genitiv_praepositionen.json',
    'assets/content/grammar/B2/12_irreale_vergleichssaetze.json',
  ];

  static const List<String> grammarC1 = [
    'assets/content/grammar/C1/01_apposition.json',
    'assets/content/grammar/C1/02_komplexe_attribute.json',
    'assets/content/grammar/C1/03_textkohaerenz_diskursmarker.json',
    'assets/content/grammar/C1/04_erweiterte_passivformen.json',
    'assets/content/grammar/C1/05_subjektive_modalverben.json',
    'assets/content/grammar/C1/06_nomen_verb_verbindungen.json',
    'assets/content/grammar/C1/07_modalpartikeln.json',
    'assets/content/grammar/C1/08_weiterfuehrende_nebensaetze.json',
  ];

  static const List<String> grammar = [
    ...grammarA1,
    ...grammarA2,
    ...grammarB1,
    ...grammarB2,
    ...grammarC1,
  ];

  static const String vocabularyGroups = 'assets/content/vocabulary/groups.json';
  static const String vocabularyCategories = 'assets/content/vocabulary/categories.json';
}

